PaddlePaddle/benchmark

CycleGAN/paddle/train.py
CycleGAN/paddle/train.sh

This changing is related to https://github.com/PaddlePaddle/Paddle/pull/17036.
Speed is unchanged, i.e., 0.15s/batch on V100 GPU machine when using only 256MB workspace, but saving lots of gpu memory.

Refine gan gpu memory

---

NeuralMachineTranslation/Transformer/fluid/train/train.py

Single card speed: 4.080103 step/s -> 4.362021 step/s. Speedup ratio is :6.9%.
```
0.0.0
2019-04-23 11:43:50,459-INFO: Namespace(batch_size=4096, device='GPU', enable_ce=True, fetch_steps=100, local=True, opts=['dropout_seed', '10', 'learning_rate', '2.0', 'warmup_steps', '8000', 'beta2', '0.997', 'd_model', '512', 'd_inner_hid', '2048', 'n_head', '8', 'prepostprocess_dropout', '0.1', 'attention_dropout', '0.1', 'relu_dropout', '0.1', 'weight_sharing', 'True', 'pass_num', '100', 'model_dir', 'tmp_models', 'ckpt_dir', 'tmp_ckpts'], pool_size=200000, shuffle=False, shuffle_batch=False, sort_type='pool', special_token=['<s>', '<e>', '<unk>'], src_vocab_fpath='/ssd1/guosheng/transformer_1.1/gen_data/wmt16_ende_data_bpe/vocab_all.bpe.32000', sync=True, token_delimiter=' ', …
```

Update transformer model

---

Mask-RCNN/paddle/rcnn/train.py
PaddingRNN/lstm_paddle/train.py

`cache_expected_kernel` is deleted in Paddle's develop branch.

Refine the pe options for padding-rnn and mask-rcnn.

---

se-resnext/paddle/reader.py

if the buf_size is too large, There will be insufficient memory. If the program is in the docker, there will be a strange hang-up of the program.

Reduce the BUF_SIZE of se-resnext

---

scripts/analysis.py
static_graph/Detection/paddle/run_benchmark.sh
static_graph/Detection/pytorch/run_detectron.sh

#233 没有验证所有的检测模型。这个PR对他们进行了验证，4个检测模型的解析结果如下：
- Cascade-RCNN
```
+ python /work/benchmark/scripts/analysis.py --filename /work/benchmark/static_graph/Detection/pytorch/cascade_fpn_rcnn_speed_1_sp --keyword json_stats: --separator '' --position -1 --base_batch_size 2 --skip_steps 2 --model_mode 0 --model_name cascade_fpn_rcnn --run_mode sp --index analysis --gpu_num 1 --range -1
Extract 76 records: separator=; position=-1
average latency of 76 steps, skip 0 step:
Avg: 0.389 s/step
FPS: 5.140 samples/s
average latency of 76 steps, skip 2 steps:
Avg: 0.237 s/step
Min: 0.234 s/step
Max: 0.263 s/step
FPS: 8.424 samples/s
FINAL_RESULT=8.424
{"index": "analysis", "log_file": "/work/benchmark/static_graph/Detection/pytorch/cascade_fpn_rcnn_speed_1_sp", "gpu_num": 1, "model_name": …
```

Update script files of detection models.

---

static_graph/Mask-RCNN/paddle/run_benchmark.sh
static_graph/Transformer/paddle/run_benchmark.sh
static_graph/deeplabv3+/paddle/run_benchmark.sh

因易用性需要，Auto growth显存分配策略已于https://github.com/PaddlePaddle/Paddle/pull/21837 默认打开，但有个别模型会因此最大batch size会下降。经与Paddle core team讨论，在个别模型benchmark中打开naive_best_fit原策略。

Add FLAGS_allocator_strategy=naive_best_fit to some models

---

static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh

https://github.com/PaddlePaddle/models/pull/4252 中，language_model添加了`enable_auto_fusion`参数，以打开fusion_group的功能。本PR在脚本中设置`--enable_auto_fusion=True`，以在Benchmark系统中打开fusion_group功能。
注意：Paddle中fusion_group功能没有cherry-pick的1.7分支中。

Enable fusion_group for PaddingRNN

---

Inference/c++/ernie/mkldnn/README.md

One parameter is missed in ernie accuracy benchmark command. Here is the fix. @bingyanghuang  @luotao1

Fix the ernie accuracy command in README.md

---

static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh

在Benchmark用的cuda10的docker环境里面，会出现找不到nvrtc库的错误、以及编译失败的问题，因此暂时先关闭fusion_group功能，等修复了再打开。

Disable fusion_group for PaddingRNN.

---

api/accuracy/assign.py
api/accuracy/cast.py
api/accuracy/concat.py
api/accuracy/elementwise_mul.py
api/accuracy/fc.py
api/accuracy/pool2d.py
api/accuracy/reshape.py
api/accuracy/softmax.py
api/accuracy/softmax_with_cross_entropy.py

This PR benchmark accuracy between paddle and tensorflow API， including:
assign fc reshape concat pool2d cast softmax_with_cross_entropy softmax elementwise_mul

Add accuracy benchmark between paddle and tensorflow API

---

api/common/paddle_api_benchmark.py
api/paddle/abs.py
api/paddle/elementwise_mul.py
api/paddle/main.py
api/paddle/run.sh
api/tensorflow/abs.py
api/tensorflow/elementwise_mul.py
api/tensorflow/main.py
api/tensorflow/run.sh

elementwise_mul和grad在一些broadcast的情况，性能表现不正常。
- Paddle的profiler结果
```
Event                                Calls       Total       CPU Time (Ratio)        GPU Time (Ratio)        Min.        Max.        Ave.        Ratio.
thread0::fetch                       300         2305.62     1204.518357 (0.522428)  1101.096985 (0.477572)  0.285183    45.8856     7.68538     0.97407
GpuMemcpySync:GPU->CPU             300         2297.03     1195.933500 (0.520643)  1101.096985 (0.479357)  0.26762     45.848      7.65677     0.970443
thread0::elementwise_mul             100         23.7226     16.769691 (0.706907)    6.952947 (0.293093)     0.171141    4.42502     0.237226    0.0100223
thread0::elementwise_mul_grad        100         21.9666     5.858711 (0.266710)     16.107847 (0.733290)    0.202275 …
```

Add the performance test of elementwise_mul

---

api/common/paddle_api_benchmark.py
api/paddle/abs.py
api/paddle/conv2d_transpose.py
api/paddle/main.py
api/paddle/run.sh

conv2d_tranpose当前只有cudnn版本支持float16类型。而**float16类型的性能比float32差上很多**。以下是该PR中添加的conv2d_transpose在不同情况下的profile数据。
conv2d_transpose op的所有配置：
```
I0313 02:25:06.001768 17773 conv_transpose_op.cc:145] input: 1, 1, 80, 63
I0313 02:25:06.001809 17773 conv_transpose_op.cc:146] filter: 1, 1, 3, 32
I0313 02:25:06.001821 17773 conv_transpose_op.cc:150] output: {1, 1, 80, 1008}
I0313 02:25:06.001827 17773 conv_transpose_op.cc:151] groups: 1
I0313 02:25:06.001832 17773 conv_transpose_op.cc:152] output_size: {}
I0313 02:25:06.001838 17773 conv_transpose_op.cc:153] dilations: {1, 1}
I0313 02:25:06.001844 17773 conv_transpose_op.cc:154] strides: {1, 16}
I0313 02:25:06.001850 17773 conv_transpose_op.cc:155] paddings: {1, 8}
I0313 02:25:06.001857 17773 conv_transpose_op.cc:156] is_test: 0
I0313 …
```

Add api benchmark for conv2d_transpose.

---

api/paddle/conv2d.py

既然`conv2d_transpose`的前向是调用`cudnnConvolutionBackwardData`来计算的，这个PR里面构造了和https://github.com/PaddlePaddle/benchmark/pull/331 中对应的conv2d的测试，测试结果如下：
- float32类型，profiler结果
```
Event                         Calls       Total       CPU Time (Ratio)        GPU Time (Ratio)        Min.        Max.        Ave.        Ratio.
thread0::fetch                300         78.5796     74.478601 (0.947810)    4.101045 (0.052190)     0.034396    0.586047    0.261932    0.425027
GpuMemcpySync:GPU->CPU      300         75.3874     71.286402 (0.945600)    4.101045 (0.054400)     0.026945    0.573778    0.251291    0.407761
thread0::conv2d_grad          100         75.9718     19.653840 (0.258699)    56.317981 (0.741301)    0.741165    1.10181     0.759718    0.410921
thread0::conv2d               100 …
```

Add api benchmark for conv2d.

---

api/accuracy/batch_norm.py

修改paddle batch_norm输入数据格式为NHWC，CPU端误差在0.0004。

modify batch_norm parameters in api accuracy

---

api/common/api_param.py
api/common/paddle_api_benchmark.py
api/common/tensorflow_api_benchmark.py
api/tests/fc.py
api/tests/fc_param.json
api/tests/feeder.py
api/tests/main.py

Implement dynamic params in API test (FC as an example)：
- 测试fc所有配置，执行命令：
python fc.py --framework=both --check_output=True --json_file=fc_param.json
- 测试fc第0个配置，执行命令：
python fc.py --framework=both --check_output=True --json_file=fc_param.json --pos=0
- FC的TF暂未对齐

Implement dynamic params in API test (FC as an example)

---

api/common/api_param.py
api/common/paddle_api_benchmark.py
api/common/tensorflow_api_benchmark.py
api/tests/abs.py
api/tests/common_import.py
api/tests/concat.py
api/tests/conv2d.py
api/tests/examples/concat.json
api/tests/examples/conv2d.json
api/tests/examples/expand.json
api/tests/examples/fc.json
api/tests/examples/fill_constant.json
api/tests/examples/reduce_mean.json
api/tests/examples/scale.json
api/tests/examples/unsqueeze.json
api/tests/expand.py
api/tests/fc.py
api/tests/fill_constant.py
api/tests/reduce_mean.py
api/tests/run.sh
api/tests/scale.py
api/tests/sigmoid.py
api/tests/square.py
api/tests/unsqueeze.py

- 支持tensorflow 2.0.0以上的版本。`TensorflowAPIBenchmarkBase`封装了一个`placeholder`函数，方便组网代码的编写。
- 简化`import`语句，将公共的部分抽取到一个`common_import.py`文件中。
- 更新了`conv2d`的测试脚本。**说明：`conv2d`没有支持所有不同类型的参数配置，比如padding支持的参数类型可以为int、list、str，后面需要强化**。
- 支持输入类型为`list of Variable`，更新`concat`的测试脚本

Update the support of tensorflow

---

api/common/api_param.py
api/tests/examples/conv2d.json

#361 的修改引入了一个bug，即从json文件中读进来的字符是unicode编码的，不应该用`isinstance(item, str)`来判断，而需要改成`isinstance(item, unicode)`。

Correct the transformation of unicode string.

---

api/common/api_param.py
api/common/utils.py
api/common/white_list.py
api/tests/dropout.py
api/tests/examples/conv2d.json
api/tests/examples/dropout.json
api/tests/main.py
scripts/run_test.sh

- 支持参数类型是`tuple`
- 调整函数名：`test_main_without_json`支持不通过json配置进行测试，有一些op（比如控制流），不能通过json来配置，可以调用`test_main_without_json`
- 调整测试一个json文件中多个配置的代码。
- 精度检查失败时改成直接挂掉。
- 添加白名单功能，像dropout这种具有随机性的op，可以记录在白名单里面。
- 即使没有修改op测试脚本，因为有可能修改了测试框架的代码，因此也需要测试abs、fc进行验证。
- 测试的op需要去重。
- api/tests目录下，main、feeder、common_ops三个文件不是op测试，需要排除
- 若op的json配置文件中存在多个配置时，则都需要测试

Support parse of tuple and enhance the codes of testing all configs in a json file

---

api/common/no_need_args.py
api/json/clear_params.py

使用inspect获取API的参数列表，检查json中是否缺少参数、移除json中多余的参数。
一些处理的log如下：
- conv2d，bias_attr代表是否有bias、act是否需要支持，需要确定下。
```
-- Processing results/conv2d.json: including 23 configs.
API: conv2d , ArgSpec(args=['input', 'num_filters', 'filter_size', 'stride', 'padding', 'dilation', 'groups', 'param_attr', 'bias_attr', 'use_cudnn', 'act', 'name', 'data_format'], varargs=None, keywords=None, defaults=(1, 0, 1, None, None, None, True, None, None, 'NCHW'))
Argument param_attr is not set.
Argument bias_attr is not set.
Argument act is not set.
Remove num_channels (type: long, value: 3).
Remove l_type (type: string, value: conv2d).
Remove channel_last (type: bool, value: False).
```
- batch_norm
```
-- Processing results/batch_norm.json: including 53 configs.
API: batch_norm , ArgSpec(args=['input', 'act', …
```

Use inspect to check and remove params in json config.

---

api/tests/examples/exp.json
api/tests/exp.py

Paddle和TensorFlow都使用eigen实现exp。
- paddle的nvprof结果
```
CUDA_VISIBLE_DEVICES is None, set to CUDA_VISIBLE_DEVICES=0
API params of <exp> {
x_shape: [16, 10, 100, 100]
}
/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py:1089: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
warnings.warn(error_info)
W0428 07:51:05.465719  2422 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.0
W0428 07:51:05.470433  2422 device_context.cc:271] device: 0, cuDNN Version: 7.5.
{
framework: "paddle",
version: "0.0.0",
name: "exp",
device: "GPU",
speed: { repeat: 100, start: 10, end: 90, total: …
```

Add script file to benchmark exp

---

api/tests/conv2d.py

```
API params of <conv2d> {
groups: 32
act: relu
filter_shape: [128, 128, 3, 3]
data_format: NCHW
input_shape: [64, 128, 56, 56]
padding: 1
use_cudnn: True
input_dtype: float32
dilation: 1
stride: 1
num_filters: 128
filter_size: [3, 3]
num_channels: 128
}
```
这种配置下，num_filter_channels = num_channels // groups = 128 // 32 = 4，但是原始的计算中直接取了num_channels=128。导致如下错误：
```
ValueError: Variable filter has been created before. the previous shape is (128L, 128L, 3L, 3L); the new shape is (128, 4, 3, 3). They are not matched.
```

fix config bug for conv2d

---

api/tests/conv2d.py

```
Traceback (most recent call last):
File "conv2d.py", line 143, in <module>
test_main(PDConv2d(), TFConv2d(), config=Conv2dConfig())
File "/workspace/new-benchmark/benchmark/api/tests/main.py", line 188, in test_main
test_main_without_json(pd_obj, tf_obj, config)
File "/workspace/new-benchmark/benchmark/api/tests/main.py", line 229, in test_main_without_json
tf_outputs = run_tensorflow(args.task, tf_obj, args, feed_list)
File "/workspace/new-benchmark/benchmark/api/tests/main.py", line 156, in run_tensorflow
profile=profile)
File "../common/tensorflow_api_benchmark.py", line 165, in run
run_metadata=run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
run_metadata_ptr)
File …
```

fix test code of conv2d for tf

---

api/json/select_configs.md
api/json/select_configs.py

通过运行Op的测试脚本，得到了json文件中所有配置运行后的log，该脚本根据前向、反向的log信息，对所有配置进行分组
- 用法示例： 
```
python select_configs.py \
--op_name conv \
--log_file conv2d.log \
--json_file ../tests/examples/conv2d.json \
--output_file ./conv2d.json
```

select configs from json

---

api/json/select_configs.md
api/json/select_configs.py

修改获取运行log的命令：保存log时，去除log中无用信息。例如原始输出为：
```
I0508 08:40:36.164196 22388 conv_cudnn_op.cu:142] use_cudnn=true data_format=NCHW groups=1 is_exhaustive_search=0 is_sys_pad=1 input_shape=[64, 3, 224, 224] filter_size=[7, 7] op=conv
I0508 08:40:36.179255 22388 conv_cudnn_op.cu:442] use_cudnn=true data_format=NCHW groups=1 is_exhaustive_search=0 is_sys_pad=1 input_shape=[64, 3, 224, 224] filter_size=[7, 7] op=conv_grad
I0508 08:40:37.576503 22388 conv_cudnn_op.cu:142] use_cudnn=true data_format=NHWC groups=1 is_exhaustive_search=0 is_sys_pad=1 input_shape=[64, 56, 56, 64] filter_size=[1, 1] op=conv
I0508 08:40:37.579442 22388 conv_cudnn_op.cu:442] use_cudnn=true data_format=NHWC groups=1 is_exhaustive_search=0 is_sys_pad=1 input_shape=[64, 56, 56, 64] filter_size=[1, 1] op=conv_grad
``` …

modify command for saving logs

---

api/common/api_param.py
api/tests/batch_norm.py
api/tests/examples/batch_norm.json
api/tests/main.py

batch_norm支持使用json配置初始化参数：
- tf的该API没有data_layout或者data_format参数，默认的计算格式为NHWC，因此若配置中的数据格式为NCHW，则通过设置`run_tf=False`，不运行TF的测试。同时会打出warning
```
---- Initialize APIConfig from ./examples/batch_norm.json, config_id = 0.
API params of <batch_norm> {
data_layout: NCHW
do_model_average_for_mean_and_var: True
epsilon: 1e-05
axes: [0]
use_global_stats: True
input_shape: [16, 256]
is_test: True
num_channels: 256
input_dtype: float32
momentum: 0.9
run_tf: False
atol: 1e-06
act: relu
in_place: True
}
/workspace/benchmark/api/tests/main.py:235: UserWarning: This config is not supported by TensorFlow.
warnings.warn("This config is not supported by TensorFlow.")
```
- json文件中的很多param，在tf的API中并没有，因此组网中也未使用，例如：
- `act `
- `do_model_average_for_mean_and_var `
- `in_place …

fix batch_norm to support api benchmark

---

.gitignore
api/common/api_param.py
api/common/paddle_api_benchmark.py
api/common/tensorflow_api_benchmark.py
api/common/utils.py
api/tests/main.py
api/tests/run.sh
scripts/run_test.sh

拆分自#308 ，将其中一些与计时方式修改无关的代码拆离出来，方便review。
这个PR主要包含以下工作：
- 清理benchmark基类实现，移除无用的代码
- 将性能测试的结果改成用`json.dumps`后输出，修改后输出如下：
```json
{"framework": "paddle", "version": "0.0.0", "name": "abs", "device": "GPU", "speed": {"repeat": 1, "begin": 0, "end": 1, "total": 7.61103630065918}}
```
- 更新CI上的tf版本，并修改了grep的匹配规则，只匹配`api/tests`目录下的`.py`文件。这个PR CI中匹配到的修改文件如下：
```
++ grep 'api/tests.*.py$'
+ HAS_MODIFIED_API_TEST=api/tests/main.py
```

Polish codes of basic benchmark class and update tensorflow version to 2.0 in ci

---

api/tests/main.py

`run_with_executor`参数已经从args里面移除了，但是main实现里面任务类型为speed，还引用了该参数，导致speed任务非正常退出。

Remove the error reference to args.run_with_executor.

---

api/tests/cond.py
api/tests/examples/cond.json

添加API:`fluid.layers.cond`的测试脚本，CPU的输出结如下：
```
---- Initialize APIConfig from examples/cond.json, config_id = 0.
API params of <cond> {
dtype: float32
shape: [10, 10, 100, 100]
run_tf: True
atol: 1e-06
x_shape: [1]
}
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
warnings.warn(error_info)
{"framework": "paddle", "version": "1.8.0", "name": "cond", "device": "CPU", "speed": {"repeat": 1, "begin": 0, "end": 1, "total": 6.284236907958984}}
API params of <cond> {
dtype: float32
shape: [10, 10, 100, 100]
run_tf: True
atol: 1e-06
x_shape: [1]
}
2020-05-18 …
```

Add script file to benchmark cond

---

api/tests/examples/switch_case.json
api/tests/switch_case.py

添加API:`fluid.layers.switch_case`的测试脚本，CPU的输出结如下：
```
---- Initialize APIConfig from examples/switch_case.json, config_id = 0.
API params of <switch_case> {
y_dtype: float32
y_shape: [16, 256, 6, 6]
input_shape: [1]
input_dtype: int32
run_tf: True
atol: 1e-06
x_shape: [16, 256, 6, 6]
}
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
warnings.warn(error_info)
{"framework": "paddle", "version": "1.8.0", "name": "switch_case", "device": "CPU", "speed": {"repeat": 1, "begin": 0, "end": 1, "total": 1.2700557708740234}}
API params of <switch_case> {
y_dtype: float32
y_shape: …
```

Add script file to benchmark switch_case

---

api/common/paddle_api_benchmark.py
api/common/tensorflow_api_benchmark.py
api/tests/main.py

主要工作：通过配置`--profiler "pyprof"`，可使用cProfile进行分析，结果直接输出。
- paddle
```
W0522 02:48:49.505357  2429 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.1
W0522 02:48:49.511164  2429 device_context.cc:273] device: 0, cuDNN Version: 7.6.
1180004 function calls (1170004 primitive calls) in 56.462 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
10000    0.055    0.000   56.444    0.006 ../common/paddle_api_benchmark.py:139(_run_main_iter)
10000    0.034    0.000   56.389    0.006 /usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/executor.py:890(run)
10000    0.285    0.000   56.355    0.006 /usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/executo …
```

Enable profiling using cProfile.

---

api/common/paddle_api_benchmark.py
api/common/tensorflow_api_benchmark.py
api/common/utils.py
api/tests/launch.py
api/tests/main.py
api/tests/run.sh
scripts/run_test.sh

实现统一的`launch.py`函数，作为OP测试的入口。执行流程如下
- 当use_gpu为True、task为speed、profiler为none时，op测试脚本会执行两遍：
- 执行shell命令`nvprof python xxx.py ...`，使用nvprof来获取GPU kernel总的执行时间gpu_time。
- 将gpu_time作为argument传递到下一次执行
- 执行shell命令`python xxx.py ...`，获取运行总时间。
- 其他情况，则只执行shell命令`python xxx.py ...`，获取相关测试信息。
- 比如abs测试，可通过launch.py入口统一启动，这样speed任务便可获得相应的总执行时间和gpu时间。执行命令为：
```python
python -m launch abs.py \
--task "speed" \
--framework "paddle" \
--json_file ${filename} \
--config_id ${config_id} \
--check_output False \
--profiler "none" \
--backward False \
--use_gpu True \
--repeat 1000 \
--log_level 0`
```
- 依旧支持直接启动op的测试脚本，只是这种方式无法获得gpu执行时间。
- abs log如下
```
run command: nvprof /usr/local/python2.7.15/bin/python abs.py --task speed --framework paddle --json_file examples/abs.json --config_id 0 --check_output …
```

Integrate nvprof to parse the gpu time.

---

Inference/c++/ernie/mkldnn/README.md

Update mkldnn ernie doc. For now check out develop, later I will change it to 2.0-alpha

update mkldnn ernie doc for 2.0-alpha

---

api/json/run.sh
api/json/select_configs.md
api/json/select_configs.py

增加过滤方案2：通过直接解析json中的配置进行筛选。目前该筛选脚本支持解析log或者解析json进行配置的筛选。待完善的功能：
Example：
- conv：`python select_configs.py       --input_json_file ./conv2d.json       --output_json_file ./conv2d.json --ignored_params act num_filters`
```
ignored_params: ['act', 'num_filters'].
==============================config_groups==============================
config 0: filter_size=1 data_format=NCHW padding=0 use_cudnn=True groups=1 stride=2 dilation=1 , total: 3.
shape 0: 4-D is_power_of_2=F, total: 3. Select 3 config_ids: [20, 14, 8]. The shapes are: [[16, 1024, 14, 14]] [[16, 512, 28, 28]] [[16, 256, 56, 56]]
config 1: filter_size=1 data_format=NCHW padding=0 use_cudnn=True groups=1 stride=1 dilation=1 , total: 21.
shape 0: 4-D is_power_of_2=F, total: 21. Select 3 config_ids: [19, 17, 30]. The shapes are: [[16, …
```

select configs by parsing json

---

api/common/api_param.py
api/common/feeder.py
api/common/paddle_api_benchmark.py
api/common/tensorflow_api_benchmark.py
api/common/utils.py
api/tests/accuracy.py
api/tests/common_import.py
api/tests/conv2d.py
api/tests/conv2d_transpose.py
api/tests/examples/conv2d_transpose.json
api/tests/main.py
api/tests/pad2d.py
api/tests/slice.py
api/tests/softmax_with_cross_entropy.py

对齐了以下几个op的计算：
- accuracy，tf的label要求是one-hot tensor，因此可以先调用`tf.one_hot`对label进行转换，计算结果可对齐，但时间不好对比。
- conv2d_transpose，tf的conv2d_transpose要求必须设置output_size，但依据paddle的输出shape设置了output_size之后，运行还是出错。待下个PR解决。
- pad2d，paddle的pad2d输入是4-D的，实际只padding 2个维度，即在H、W这两个维度上进行padding；tf的pad可支持任意维度的输入，输入是4-D时，paddings的形状应为[4, 2]，不padding的维度上值应设置为0。且`tf.pad`的`paddings`参数，必须用`tf.constant`定义。
- slice，使用方式不对，config中的begin和size，是tf对应参数的值（不是shape）。
- softmax_with_cross_entropy，同accuracy，且必须设置`reduction='none'`。

Correct the usage of several ops

---

api/common/__init__.py
api/tests/__init__.py
api/tests/common_import.py
api/tests/launch.py
api/tests/run.sh
scripts/run_test.sh

master分支代码，若在`benchmark/api/tests/deploy`目录下面命令`python ../launch.py ../abs.py ...`，会出现如下错误：
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
File "../launch.py", line 21, in <module>
from common import utils
ImportError: No module named common
```
为了支持在不同的目录执行op测试，这个PR做了以下3个工作：
1. common目录下新增`__init__.py`文件
2. common_import.py和launch.py里面引入common目录模块时，将相对路径`..`改成绝对路径
3. 支持在别的目录直接运行tests目录下的run.sh，比如在`benchmark/api`目录下直接执行命令`./tests/run.sh`

Support running op test in different directory.

---

api/deploy/main_control.sh

Paddle 和 tensorflow框架的accuracy的结果是一致的。可以只跑Paddle部分。

remove accuracy of tensorflow

---

api/json/run.sh
api/json/select_configs.py

**问题描述**：修复配置筛选脚本的几个bug
- shape不超过3个时，之前未进行去重，另外会导致打印信息不全。
修改后的结果：
```
processing API: cast
ignored_params: [].
Total config of input json: 37
==============================config_groups==============================
config 0: dtype=bool , total: 1.
shape 0: 2-D is_power_of_2=F, total: 1. Select 1 config_ids: [2]. The shapes are: [[16, 1785]]
config 1: dtype=int64 , total: 1.
shape 0: 2-D is_power_of_2=T, total: 1. Select 1 config_ids: [6]. The shapes are: [[16, 1]]
config 2: dtype=float32 , total: 31.
shape 0: 2-D is_power_of_2=T, total: 9. Select 3 config_ids: [20, 24, 35]. The shapes are: [[16, 1]] [[16, 1024]] [[4096, 1024]]
shape 1: 3-D is_power_of_2=T, total: 1. Select 1 config_ids: [26]. The shapes are: [[16, 16, 1024]]
shape 2: 4-D is_power_of_2=F, total: 1. Select 1 config_ids: …
```

fix bug of selected shapes

---

api/json/clear_params.py
api/json/process_json.py
api/json/unify_optional_params.py
api/tests/configs/argsort.json
api/tests/configs/case.json
api/tests/configs/cond.json
api/tests/configs/conv2d.json
api/tests/configs/conv2d_transpose.json
api/tests/configs/cumsum.json
api/tests/configs/depthwise_conv2d.json
api/tests/configs/elementwise.json
api/tests/configs/expand.json
api/tests/configs/pool2d.json
api/tests/configs/softmax.json
api/tests/configs/switch_case.json

paddle里面，有一些op有use_cudnn熟悉，可以配置是否调用cudnn。cudnn大部分情况下都有很好的性能，但也有些情况下，性能比paddle原生的CUDA实现性能差。op benchmark希望能系统地测试和比较paddle原生CUDA实现与cudnn实现的性能。
这个PR实现一个脚本，可以遍历所有op的json配置，当发现op有use_cudnn参数时，自动在json配置中插入一个与当前use_cudnn值相反的配置。
```
$  python unify_optional_params.py --json_path=./results --output_dir=./results_unified/
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
There are 56 configs under /work/benchmark/api/json/results.
-- Processing /work/benchmark/api/json/results/accuracy.json: including 2 configs.
-- Operator accuracy does not have use_cudnn argument. Skipped.
-- Writing 2 unified configs back to /work/benchmark/api/json/results_unified/accuracy.json.
-- Processing /work/benchmark/api/json/results/activation.json: including 2 configs.
-- Operator activation does …
```

Append a config with opposite value for use_cudnn in op's configs.

---

api/common/paddle_api_benchmark.py

speed任务时，返回的stats词典中的初始值被覆盖了，会出现找不到key 'framework'的错误。

Fix bug a rewriting the returned status.

---

api/common/special_op_list.py
api/deploy/collect_api_info.py
api/deploy/main_control.sh
api/tests/assign.py
api/tests/cast.py
api/tests/sequence_mask.py

- 一些op没有注册对应的grad op，这种情况op benchmark不测试反向的功能和性能。暂时通过一个list记录没有grad的op。
- 这是op运行最长时间为10min，否则将视为hang住了。
- 若设置timeout时间为60s，log如下：
```
$ bash ./deploy/main_control.sh ./tests/configs . cpu accuracy
[1]: api_name=instance_norm, name=instance_norm, json_file=./tests/configs/instance_norm.json, num_configs=1, json_id=0
[1-1][2020-06-09 02:43:02] device=cpu, backward=F, ./instance_norm-paddle_cpu_accuracy_forward_0.txt, time=3925 ms    ...... SUCCESS
[1-2][2020-06-09 02:44:02] device=cpu, backward=T, ./instance_norm-paddle_cpu_accuracy_backward_0.txt, time=60005 ms  ...... **TIMEOUT**
```
- 将timeout时间设置为10min，意外地发现instance_norm grad可以跑出结果。
```
$ bash ./deploy/main_control.sh ./tests/configs . cpu accuracy
[1]: api_name=instance_norm, name=instance_norm, …
```

Complete the operator list which do not have grad operators.

---

api/tests/while_loop.py

添加`tf.compat.v1.disable_v2_behavior()`使`while_loop`的测试脚本能在tf-2.0中正常运行。

Fix while_loop bug

---

api/common/paddle_api_benchmark.py
api/common/special_op_list.py
api/common/tensorflow_api_benchmark.py
api/common/utils.py
api/deploy/api_info.txt
api/deploy/main_control.sh
api/tests/arg.py
api/tests/cond.py
api/tests/configs/elementwise.json
api/tests/conv2d.py
api/tests/conv2d_transpose.py
api/tests/gather.py
api/tests/launch.py
api/tests/main.py
api/tests/pool2d.py
api/tests/run.sh
api/tests/sequence_mask.py
api/tests/switch_case.py
api/tests/while_loop.py
scripts/run_test.sh

这个PR主要根据op benchmark平台上的展示结果，修复了一些问题：
- 修改精度不满足时的输出，确保dict是log的最后一行。
- dict中添加backward字段，调用了`append_gradients`接口才认为是在执行backward。
- TODO：打开`self.__backward == config.backward`的检查，组网代码中没有调用`append_gradients`接口的op，运行参数也不能设置`backward=True`
- `argmax`、`argmin`没有反向op，加入`NO_BACKWARD_OPS`。
- 获取一些基本信息，包括
- benchmark最新的commit以及该commit的时间
- paddle的commit和版本号
- tensorflow的版本号
- fix一些tf不会生成梯度的case
- elementwise_add，最后一个config中x、y是int类型，这种情况下梯度没有意义
- gather的index输入没有梯度
- cond、switch_case中用于比较的变量没有梯度
- fix一些op的脚本问题
由于CI环境的改变，导致CI检查一直不通过，故这个PR也进行了更新：
- 每次都强制重新安装pip，避免安装tensorflow找不到2.0以上版本的问题
- 每次拉取paddle最新的安装包进行更新

Improve the testing and reocrding of backward running

---

api/common/api_param.py
api/common/paddle_api_benchmark.py
api/common/tensorflow_api_benchmark.py
api/common/utils.py
api/deploy/main_control.sh
api/run_op_benchmark.sh
api/tests/case.py
api/tests/main.py
scripts/run_test.sh

这个PR做了以下修改：
- 修改`list<Variable>`类型的parameters格式。summary.py在解析op运行log的时候，会截取最后一行的dict，并且size不能超过1024。一些特殊的case，比如concat，拼合201个shape为[1]的变量，因为parameters超出了1024的长度限制，导致不能正常解析。另外，parameters太长展示效果也不好。因此当多个输入的dtype、shape都一样时，改成如下格式：
```
"parameters": "input (list<Variable>[201]) - dtype: float32, shape: [1]; \naxis (int): 0\n"
```
- 修复backward值获取的bug。类A的`__member`成员，使用hasattr判断时，需指定属性名为`_A__member`。
- `total = avg_runtime - avg_walltime`，设置total最小值为0.001，避免total出现极小值、甚至是负数的情况。
- CPU测试时，必须设置环境变量`export CUDA_VISIBLE_DEVICES=""`，否则tf都是使用GPU运行的。

Enhance the tesing and checking of CPU performance and fix serveral op scripts

---

api/common/special_op_list.py
api/tests/clip_by_norm.py
api/tests/configs/clip_by_norm.json
api/tests/elementwise.py
api/tests/examples/clip_by_norm.json
api/tests/run.sh

@phlrain 反馈，clip_by_norm CPU非常慢，甚至比使用多个小OP组合的计算速度还要慢很多。测试代码如下：
```python
import paddle.fluid as fluid
import numpy as np
import time
def local_clip( input, norm):
sq = fluid.layers.square( input )
sum1 = fluid.layers.reduce_sum( sq )
n = fluid.layers.sqrt( sum1)
if n.numpy()  > norm:
return input / n.numpy()
else:
return input
with fluid.dygraph.guard(fluid.CPUPlace() ):
a = np.random.uniform( -1.0, 1.0, (1000, 300)).astype("float32")
a = fluid.dygraph.to_variable( a )
print( a.shape )
start = time.time()
b = fluid.layers.clip_by_norm(a, 1.0) 
print( "cost", time.time() - start )
start = time.time()
b = local_clip( a, 1.0 )
print( "local cost", time.time() - start )
```
运行结果为：
OP Benchmark测得的时间：
| op | CPU Time | GPU Time | parameters |
|---|---|---|---|
| clip_by_norm | 56950.334 | 0.275 …

Add script of clip_by_norm.

---

api/common/api_param.py
api/common/utils.py
api/tests/configs/conv2d.json
api/tests/configs/matmul.json
api/tests/configs/reduce.json
api/tests/conv2d.py
api/tests/conv2d_transpose.py
api/tests/elementwise.py
api/tests/main.py
api/tests/matmul.py
api/tests/reduce.py
api/tests/run.sh
api/tests/sequence_mask.py

这个PR主要进行一下修改：
- 有些op，Paddle和TensorFlow的计算结果的shape不完全相同，比如gather_1。这个PR对结果的检查方式做了一些调整，修改成：除了reshape、squeeze、unsqueeze之外，输出结果squeeze之后的shape相同即可，并且通过log进行提示。
```
AssertionError: The 0-the output's shape is different, (16, 256, 14, 14) vs (16, 1, 256, 14, 14).
```
- 修复一些脚本错误，比如：
- elementwise不应设置act
- sequence_mask的maxlen参数，支持Variable类型
- 一些存在累加求和操作的op，输入变量的feed范围应设置成[-1, 1]
- 给一些配置设置atol，应尽量避免在op测试脚本中统一设置atol
- 将CI的测试目录切换到configs

Enhance scripts for several ops

---

api/common/tensorflow_api_benchmark.py

原因：跑CPU程序时，TF默认打满所有CPU，而Paddle只使用1个。导致CPU两者性能数据差比较多。详细分析见 https://github.com/PaddlePaddle/Paddle/issues/18665#issuecomment-513780210
本PR：
- 在CPU测试时，使TF也只使用1个CPU。以abs_0配置的CPU前向为例子（单位ms）
|   测试条件  | Paddle  | TF| 备注|
|  ----  | ----  |----  |----  |
| 虚拟机develop分支  | 555 | 1.45
| 物理机develop分支  | 20 |26 | TF的cpu利用率740%
| 物理机develop分支  | 20 |72 | TF的cpu利用率100% 
- 为了不影响GPU测试，用`use_gpu`进行判断。

change TF use one cpu core

---

api/common/utils.py
api/deploy/op_benchmark_unit.py
api/deploy/summary.py
api/deploy/write_excel.py
api/deploy/write_text.py
scripts/run_test.sh

这个PR主要有以下修改：
- 将summary.py拆分成4个文件
- summary.py，全量op测试结果的提取、写入数据库、以及summary的主流程
- op_benchmark_unit.py，一些基本单位的操作，包括统计比较结果
- write_excel.py，写excel相关的实现
- write_text.py，写文本文件相关的实现
- 强化了summary功能，现在支持case_level的汇总统计、op_level的汇总统计、每个op的汇总统计，具体如下：
- 修复了gpu_time计算的bug

Split summary.py to four files and enhance summary of different level.

---

api/common/api_param.py
api/common/feeder.py
api/common/paddle_api_benchmark.py
api/common/tensorflow_api_benchmark.py
api/common/utils.py

由于TF 2.2.0以后不再发布Python2.7版本的[whl包](https://pypi.org/project/tensorflow/2.2.0/#files)，因此为了测试最新TF版本的性能，OP Benchmark需要支持Python3。

Support python3.

---

scripts/static_graph_models.sh

* 模型训练显存爆的问题在[#25140](https://github.com/PaddlePaddle/Paddle/pull/25140/files)里修复，故而将对应模型再次开启训练
* CycleGAN 与Pix2pix 模型训练较快，无法及时抓取到CPU 利用率和GPU 利用率，故而增大训练iter数

 fixed out of mem

---

api/tests/configs/elementwise.json

增加一种elementwise的广播配置，该配置来自ERNIE AMP训练，性能不符合预期。

Add a config to elementwise ops: [512, 896, 4, 12] and [512, 896, 4, 1], float32 and float16.

---

api/common/api_param.py
api/tests/configs/matmul.json
api/tests/conv2d.py
api/tests/elementwise.py
api/tests/main.py

- matmul增加6个配置，分别对比以下几种配置的性能：float32 vs float16、float16 MNK是否8的倍数。
- elementwise_pow不支持float16数据类型，对于数据类型是float16的配置，APIConfig里面标记为disabled。

Add several configs for matmul.

---

api/common/feeder.py
api/common/utils.py
api/deploy/op_benchmark_unit.py
api/deploy/summary.py
api/deploy/write_excel.py
api/tests/configs/resize_bilinear.json
api/tests/configs/resize_nearest.json
api/tests/conv2d.py
api/tests/conv2d_transpose.py
api/tests/resize_bilinear.py
api/tests/resize_nearest.py

- conv2d系列op，paddle的filter存储格式是NCHW，tf的filter存储格式是HWNC。当前的实现，不支持对fetch tensor进行permute，所以conv2d反向测试时，不能fetch filter_grad，导致tf反向没有计算filter_grad、但paddle算了，因此计时比较不公平。采取的解决方法是：
- 在正确性比较时，自动对所有的可能的permutation进行比较。
- 添加resize_nearest、resize_bilinear两个op的测试脚本。
- 调整了excel的输出内容和格式，包括：
- case_name按照op_type、case_id的顺序输出
- 速度比较结果换成中文输出
- 正确性比较结果，直接输出diff

Support auto permutation for output when outputs shape are different.

---

api/deploy/docker_run.sh
api/deploy/main_control.sh

支持并行跑CPU op benchmark：
- 使用绑核操作，将每个Op示例绑到一个CPU核上运行，达到并行跑Cpu benchmark的效果。
- 绑多少核：< 物理核，假设有20个物理核，不能全部用满。因为有额外的线程是用于读数据的，全部用满会导致性能急剧下降。
以下是在20核的6148物理机上，绑15核并行跑出来的abs-0效果
| abs-0   | 前向ms  |反向ms|
|  ----  | ----  |----|
| paddle  | 281.54 |928.81
| tensorflow  | 329.31 |791.66
以下是显示在性能网站，在v100虚拟机上，串行跑出来的abs-0效果
| abs-0   | 前向ms  |反向ms|
|  ----  | ----  |----|
| paddle  | 546.82 |1644.69
| tensorflow  | 511.56 |1179.83
可以看到，两个数据的比例是一致的。

Enable parallel execution On CPU op benchmark

---

api/tests/configs/transpose.json

ERNIE DOC AMP训练中transpose存在性能问题，根据perm参数的不同，从模型中选取了两种占比较高的配置：
- perm=[2, 3, 0, 1]会调用TilingSwapDim1And2 cuda kernel
- perm=[1, 2, 0, 3]会调用Eigen

Add API config for transpose

---

api/tests/configs/slice.json

ERNIE DOC模型中发现：AMP训练下slice_grad的反向GPU时间和FP32训练下基本一致，FP16性能需要优化。
添加的配置为模型中占比最高的一种

add fp16 API config for slice

---

api/tests/configs/cumsum.json

原来的配置可能是因为size太大，会导致运行失败，故减小size。

Reduce the size of cumsum's input.

---

api/tests/configs/conv2d.json

添加2个conv2d的配置。主要参数：
```
input (Variable) - dtype: float32, shape: [2, 512, 129, 129]
act (string): None
data_format (string): NCHW
dilation (tuple): [16, 16]
filter_size (tuple): [3, 3]
groups (int): 1
num_filters (int): 512
padding (tuple): [0, 0]
stride (tuple): [1, 1]
```
- GPU Kernel时间
| 测试类型 | paddle | tf2.3 |
|---|---|---|
| use_cudnn=True, backward=False | 6.5492 ms | 6.5767 ms |
| use_cudnn=False, backward=False | 7.8169 ms | - |
| use_cudnn=True, backward=True | 169.8235 ms | 21.5862 ms |
| use_cudnn=False, baclward=True | 34.2407 ms | - |
- paddle，use_cudnn=True，backward=False
```
run command: nvprof /root/.virtualenvs_cuda10.1/paddle_py37/bin/python /work/benchmark/api/tests/conv2d.py --task speed --framework paddle --json_file /work/benchmark/api/tests/configs/conv2d.json …
```

Add two configs of conv2d.

---

api/common/api_param.py
api/common/feeder.py
api/deploy/summary.py
api/json/clear_params.py
api/tests/accuracy.py
api/tests/batch_norm.py
api/tests/conv2d.py
api/tests/conv2d_transpose.py
api/tests/depthwise_conv2d.py
api/tests/embedding.py
api/tests/fc.py
api/tests/gather.py
api/tests/main.py
api/tests/one_hot.py
api/tests/pool2d.py
api/tests/resize_nearest.py
api/tests/sequence_mask.py
api/tests/softmax_with_cross_entropy.py

- op测试的json配置在模型组网阶段收集到的，因此会存在很多-1，这些-1在运行时通常都会被实际使用的batch_size替换。master的做法是把这个-1都替换成了16，实际可能需要测试一些不同的batch_size，因此添加参数`unknown_dim`，允许通过参数`--unknown_dim 128`来设置不同的batch_size。
- summary.py在解析log文件中的json输出时，默认json是在log文件的最后一行。升级到py3.7和tf2.3之后，tf的log文件最后几行如下，json不在最后一行，因此解析失败。这个PR对json解析进行了加强，会尝试从最后一行往上追溯，直到解析到json格式的输出，或者遍历到最后一行。
```
...
{"name": "abs", "backward": true, "consistent": true, "num_outputs": 2, "diff": 0.0, "parameters": "x (Variable) - dtype: float32, shape: [1]\n"}
/usr/local/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py:546: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
class IteratorBase(collections.Iterator, trackable.Trackable, …
```

Add an argument "unknown_dim" to allow to replace -1 in variable's shape and polish the parse of json output of log.

---

api/tests_v2/abs.py
api/tests_v2/configs/activation.json
scripts/run_test.sh

为了测试 paddle 2.0 的API性能，目前新建路径：api/tests_v2
- 新增 abs 2.0 测试脚本和参数

add abs 2.0 tests

---

api/common/special_op_list.py
api/tests_v2/run.sh
ci/scripts/check_approval.sh

1. Add approval check for api/common/special_op_list.py. 
CI will fail when no reviewers approval this PR.
When reviewer approval.
2. Set default value True of `backward`.

Set backward default True and add approval for special_op_list.py

---

api/common/paddle_api_benchmark.py
api/tests_v2/transpose.py

As the title.
Also fixed a bug that `paddle_api_benchmark.py` uses `sys.stderr.write` but did not import `sys`
This PR doesn't contain the config file `transpose.json` because I found it already existed.

Add Transpose to OP Benchmark

---

api/tests_v2/configs/histogram.json
api/tests_v2/histogram.py

add histogram 2.0 test
paddle.histogram 开发的时候对照的是torch.histc，计算方式也等同于numpy.histogram和matlab.histc (可以参考 https://www.cnblogs.com/qinduanyinghua/p/12105979.html)；
然而TensorFlow中tf.summary.histogram的定义也相同，但是返回值是True/False，直方图的结果需要通过tf.summary.FileWriter写入文件，然后用tensorboard命令载入改文件之后进行图形化显示，具体例子可以参考
https://github.com/tensorflow/tensorboard/blob/master/docs/r1/histograms.md
所以无法直接将 paddle.histogram 和 tf.summary.histogram的性能进行对比，这个PR只实现了Paddle的PaddleAPIBenchmark，将config.run_tf设置成了False。

add histogram 2.0 test

---

api/common/special_op_list.py
api/tests_v2/configs/unique.json
api/tests_v2/unique.py

- 只添加了Paddle的API，因为该接口不能与TF对齐：
该接口默认返回值是会排序的，输出元素按升序排序
但是TF的返回值不排序，也就是文档中所说的：输出中元素的顺序就是该元素在x中出现的顺序
- 该OP没有反向

add unique API

---

api/common/special_op_list.py
api/common/tensorflow_api_benchmark.py
api/tests/run.sh

- 修复topk反向计算问题。
- 分析：paddle反向计算结果为2个tensor，tf的反向计算结果为3个tensor，多出了一个全0 tesnor。

fix topk bugs

---

api/common/special_op_list.py
api/tests_v2/configs/equal_all.json
api/tests_v2/equal_all.py

因为equal_all OP在2.0开发时是对齐pytorch的equal，返回的结果只有一个元素值，如果所有相同位置的元素相同返回True，否则返回False；而TF中没有相同功能的API，因此无法与TF进行精度对齐。所以该PR支实现了`Paddle的PaddleAPIBenchmark`，将 `config.run_tf `设置成了 `False`。

Add benchmark for equal_all

---

api/common/special_op_list.py
api/tests_v2/configs/top_k_v2.json
api/tests_v2/top_k_v2.py

由于top_k_v2的tf中反向计算的加入问题，导致在精度对齐的时候，top_k_v2对三个输出进行对齐（除了top_k_v2本身的输出values和indices，还有反应计算的一个tensor）。该PR暂时未添加反向部分只对top_k_v2的前向进行对齐。除此之外，top_k_v2输出的indices的类型是与pytorch对齐的int64，但tf的indices是int32.

Add the benchmark for top_k_v2

---

api/deploy/collect_api_info.py
api/deploy/main_control.sh
api/tests_v2/isfinite_nan_inf_v2.py

main_control.sh脚本增加test_dir参数，可以选择op脚本的测试路径
- bash main_control.sh test_dir  json_config_dir  output_dir gpu_id  cpu|gpu|both  speed|accuracy|both  op_list_file
collect_api_info.py 收集支持op，参数信息
-  python collect_api_info.py --info_dir=tests_v2  --info_file=op_info_v2.txt  --support_api_file=op_list_v2.txt

Add run script of all op in test_v2

---

api/tests_v2/affine_grid.py
api/tests_v2/configs/affine_grid.json

affine_grid在tensorflow中没有官方的实现。
affine_grid主要被用在STN中，在tensorflow的STN实现中，一般是用小op组装得到的affine_grid，例如： https://github.com/kevinzakka/spatial-transformer-network/blob/master/stn/transformer.py#L95

Add benchmark for affine grid op

---

api/tests_v2/relu6.py
api/tests_v2/softplus.py

add relu6 and softplus
relu6:
[tensorflow][relu6] relu6 {
run_tf: True
alias_config: [tensorflow][activation] activation {
x_shape: [16, 128, 257, 257]
}
repeat: 5000
atol: 1e-06
}
[paddle][relu6] relu6 {
run_tf: True
alias_config: [paddle][activation] activation {
x_shape: [16, 128, 257, 257]
}
repeat: 5000
atol: 1e-06
}
{"name": "relu6", "backward": true, "consistent": true, "num_outputs": 2, "diff": 0.0, "parameters": "x (Variable) - dtype: float32, shape: [16, 128, 257, 257]\n"}
softplus:
[tensorflow][softplus] softplus {
run_tf: True
alias_config: [tensorflow][activation] activation {
x_shape: [16, 128, 257, 257]
}
repeat: 5000
atol: 1e-06
}
[paddle][softplus] softplus {
run_tf: True
alias_config: [paddle][activation] activation { …

Add relu6 and softplus

---

api/common/special_op_list.py
api/tests_v2/bernoulli.py
api/tests_v2/configs/bernoulli.json

As the title
Result of lcoal run:
```
Backward is not surported for bernoulli in Paddle. It is actually running the forward test.
---- The 0-the output's data type is different, float32 vs int32.
---- The 0-th output (shape: (16, 1785), data type: float32) has diff. The maximum diff is 1.000000e+00, offset is 1: 1.0 vs 0. atol is 1.00e-06.
The output is not consistent.
{"name": "bernoulli", "backward": false, "consistent": false, "num_outputs": 1, "diff": 1.0, "parameters": "x (Variable) - dtype: float32, shape: [16, 1785]\n"}
```
1. The `dtype` diff is by design. Paddle returns the same dtype as input, while Tensorflow always returns int32.
2. The `value` diff is possible since it is a random number related API.

add bernoulli test

---

api/common/special_op_list.py
api/tests_v2/lstm.py

add lstm tests
- lstm目前2.0接口使用class类，框架暂不支持。待新的LSTM添加paddle.nn.functional接口后换成新的接口测试。因此暂时保留老版本的layers接口。
- tensorflow和目前layers接口不能对齐。目前kernel正确使用方式是支持padding数据，但是使用老接口不支持此功能，因此暂时不能与TF对齐。
- 怀疑因为新的c++ kernel增加了多个中间过程的输入输出，所以反向计算会出现问题。暂时去除反向。

add lstm tests

---

scripts/static_graph_models.sh

*  paddle 切换默认动态图后，detection [静态图转换PR ](https://github.com/PaddlePaddle/PaddleDetection/pull/1498)暂未合入
先前[fetch 上述PR 后合入master](https://github.com/PaddlePaddle/benchmark/pull/625)的方式不可取
在实际训练静态图时，默认分支是
故而报错找不到train.py
*  解决：
在静态图detection 目录里check到master （此时会在最新commit），并reset到特定commit，再fetch 上述PR ，在本地merge到master

fix_detection_1009

---

api/tests_v2/configs/logical.json
api/tests_v2/configs/logical_not.json
api/tests_v2/configs/reduce.json
api/tests_v2/configs/softmax_with_cross_entropy.json
api/tests_v2/configs/squeeze.json
api/tests_v2/logical.py
api/tests_v2/logical_not.py
api/tests_v2/reduce.py
api/tests_v2/scale.py
api/tests_v2/shape.py
api/tests_v2/softmax_with_cross_entropy.py
api/tests_v2/softsign.py
api/tests_v2/squeeze.py

- logical:  logical_and, logical_or
- logical_not
-  reduce:  reduce_mean, reduce_sum, reduce_prod
- scale
- shape 
- softmax_with_cross_entropy 
- softsign
- squeeze

Move 1.8 tests to 2.0 tests 

---

api/tests/run.sh
api/tests_v2/run.sh
ci/scripts/run_test.sh

- 多卡机器资源中，GPU使用分配的设备，没有分配时使用默认“0”：
`[ -z "$CUDA_VISIBLE_DEVICES" ] && export CUDA_VISIBLE_DEVICES="0"`
- 顺带修复错误信息中小问题；

Using CUDA_VISIBLE_DEVICES=0 while there is not a default ID number.

---

api/tests/while_loop.py
api/tests_v2/while_loop.py

Refine the error of while_loop in backward calculation. More information please refer to [icafe427](http://newicafe.baidu.com/v5/issue/paddle-perf-427/show).

Refine the error of while_loop in backward calculation

---

api/tests_v2/configs/avg_pool2d.json
api/tests_v2/configs/max_pool2d.json

为了能够更好的对齐1.8和2.0的op性能测试结果，将2.0 中avg_pool2d和max_pool2d的配置和1.8中 pool2d的配置对齐。
- avg_pool2d：第0个对应pool2d第0，1个配置；第1个对应pool2d4，5个配置；第2个对应pool2d6,7个配置；
- max_pool2d：第0个对应pool2d第2，3个配置。

fix pool2d configs

---

api/tests_v2/expand_as.py
api/tests_v2/while_loop.py

修复因为paddle删除部分alias导致的脚本运行错误。
- case已使用的正确别名
- 删除paddle.nn.while_loop
- 删除paddle.fill_constant

fix bug of remove alias in paddle

---

api/common/api_param.py
api/common/launch.py
api/deploy/api_info.txt
api/deploy/api_info_v2.txt
api/deploy/collect_api_info.py
api/tests/configs/cumsum.json
api/tests_v2/configs/cumsum.json

- 减少cumsum_1的repeat次数，避免测试时timeout。
- collect_api_info.py中无法获取DivideConfig类，因此需为APIConfig实现一个静态类，递归地收集所有层次的subclass的信息。
https://github.com/PaddlePaddle/benchmark/blob/95272d6edd12787442607c3283fc458f77c1ba4a/api/deploy/collect_api_info.py#L46

Change repeat of cumsum_1 to 100 to avoid timeout and support to collect the subclasses recursively.

---

api/tests_v2/configs/conv_transpose2d.json
api/tests_v2/conv_transpose2d.py

- conv_transpose2d的当前实现中，tf测试强制将data_format转换成NHWC。tf接口gpu是支持NCHW的，cpu不支持，因此脚本中需使用NCHW进行测试。
https://github.com/PaddlePaddle/benchmark/blob/0481cab10bb12257093c7e431e7993f6c0d72467/api/tests_v2/conv_transpose2d.py#L78-L79

conv_transpose2d supports NCHW for tf.

---

api/common/api_param.py
api/common/main.py
api/common/utils.py
api/deploy/op_benchmark_unit.py
api/deploy/summary.py
api/tests/common_import.py
api/tests/conv2d.py
api/tests/conv2d_transpose.py
api/tests/elementwise.py
api/tests/run.sh
api/tests_v2/batch_norm.py
api/tests_v2/common_import.py
api/tests_v2/conv2d.py
api/tests_v2/conv_transpose2d.py
api/tests_v2/elementwise.py
api/tests_v2/elementwise_with_axis.py
api/tests_v2/remainder.py
api/tests_v2/run.sh

- Paddle op的CPU kernel都不支持`float16`数据类型，因此：
- 为基类APIConfig实现一个默认的disable()函数，CPU测试时disable所有float16的配置。
- disable的配置也输出一个json字符串，便于summary脚本中过滤disable的配置
- 修改后输出如下：
```
---- Initialize APIConfig from /work/benchmark/api/tests_v2/configs/accuracy.json, config_id = 0.
Warning:
1. This config is disabled because float16 is not supported for accuracy on CPU.
{"name": "accuracy", "device": "CPU", "backward": false, "disabled": true, "parameters": "input (Variable) - dtype: float16, shape: [16, 3]\nlabel (Variable) - dtype: int64, shape: [16, 1]\ntotal (Variable) - dtype: int64, shape: []\ncorrect (string): None\nk (int): 1\n"}
```
- tf的conv类的op，CPU运行时都不支持NCHW，因此标记`run_tf=False`。输出如下：
```
Warning:
1. tf is disabled because the tf's conv ops currently only supports the NHWC tensor format on the …
```

Implement a default disabled() to disable the float16 configs for CPU and disable the tf's conv tests when data_format is NCHW. 

---

api/deploy/main_control.sh

`ps -opid | grep $task_pid`用来判断任务是否执行完成，当任务pid属于`ps -opid`中当前bash进程pid的子符串，如：
任务pid为312，当前bash进程pid为3127
那么这个判断就出现了错误，可以在grep时添加`-w`参数来完全匹配任务pid，从而避免上述问题。

Fix main_control.sh run blocking error.

---

api/common/utils.py
api/tests_v2/configs/dropout.json
api/tests_v2/configs/elementwise.json
api/tests_v2/dropout.py

- 修复check_outputs中对于随机性OP的处理逻辑。随机性OP的执行结果。当前的代码，随机性OP即使加入了RANDOM_OPS_LIST，CI依旧会挂，CI log如下：
```
2020-10-26 12:07:27 ---- Warning: The 0-th output (shape: (16, 36864), data type: float32) has diff. The maximum diff is 2.000000e+00, offset is 504454: 0.0 vs 1.9999995. atol is 1.00e-06.
2020-10-26 12:07:27 ---- Warning: The 1-th output (shape: (16, 36864), data type: float32) has diff. The maximum diff is 2.000000e+00, offset is 4: 0.0 vs 2.0. atol is 1.00e-06.
2020-10-26 12:07:27 ---- Warning: The output is not consistent, but dropout is in the white list.
2020-10-26 12:07:27 {"name": "dropout", "device": "GPU", "backward": true, "consistent": false, "num_outputs": 2, "diff": 2.0, "parameters": "x (Variable) - dtype: float32, shape: [16, 36864]\naxis (string): None\nmode (string): …
```

Change dropout to test the CI.

---

api/tests/lstm.py
api/tests_v2/lstm.py

[lstm只支持运行在GPU设备上](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/lstm_cn.html#lstm)
- before:
```
----------------------
Error Message Summary:
----------------------
UnimplementedError: CPU is not support for this kernel now. Will be add in the future (at /workspace/paddle/fluid/operators/cudnn_lstm_op.cc:292)
[operator < cudnn_lstm > error]
```
- after:
```
Warning:
1. lstm is disabled because it is only supported run on GPU, now is CPU.
```

lstm only runs on GPU

---

api/deploy/api_info_v2.txt
api/tests/configs/embedding.json
api/tests/configs/reshape.json
api/tests/fc.py
api/tests_v2/configs/conv2d_transpose.json
api/tests_v2/configs/conv3d_transpose.json
api/tests_v2/configs/depthwise_conv2d_transpose.json
api/tests_v2/configs/embedding.json
api/tests_v2/configs/reshape.json
api/tests_v2/conv2d_transpose.py
api/tests_v2/conv3d_transpose.py
api/tests_v2/depthwise_conv2d_transpose.py

做了如下修改：
1. conv_transpose2d-> conv2d_transpose。
2. conv_transpose3d-> conv3d_transpose。
3. depthwise_conv_transpose2d-> depthwise_conv2d_transpose
4. embedding_1/embedding_2/reshape_0 配置增加repeat次数。
- embedding_1，再增加repeat次数，反向会超时:
```
GPU activities:   94.02%  2.88333s    850001  3.3920us  2.8800us  13.536us  void paddle::operators::LookupTableV2<float, int=256, int=4, int=80, bool=1>(float*, paddle::operators::LookupTableV2<float, int=256, int=4, int=80, bool=1> const *, long const *, long, long, long, long)
5.98%  183.26ms         9  20.362ms  1.7600us  183.23ms  [CUDA memcpy HtoD]
percent: 0.94; gpu_time: 2883.3300 ms; calls: 850001; function: void paddle::operators::LookupTableV2<float, int=256, int=4, int=80, …
```

fix conv names and repeat times

---

api/tests_v2/conv3d_transpose.py

修复conv3d_transpose 名称改变导致的脚本运行错误。
本地执行可通过：
```
Gradients:  [var input@GRAD : fluid.VarType.LOD_TENSOR.shape(16, 3, 8, 8, 8).astype(VarType.FP32), var filter@GRAD : fluid.VarType.LOD_TENSOR.shape(3, 6, 3, 3, 3).astype(VarType.FP32)]
{"framework": "paddle", "version": "0.0.0", "name": "conv3d_transpose", "device": "GPU", "backward": true, "speed": {"repeat": 1, "begin": 0, "end": 1, "total": 0.2689361572265625, "wall_time": 0.06937980651855469, "total_include_wall_time": 0.3383159637451172, "gpu_time": 0.42686056458511545}, "parameters": "input (Variable) - dtype: float32, shape: [16, 3, 8, 8, 8]\nact (string): None\ndata_format (string): NCDHW\ndilation (int): 1\nfilter_size (int): 3\ngroups (string): None\nnum_filters (int): 6\noutput_size (list): [10, 10, 10]\npadding (int): 0\nstride …
```

fix conv3d_transpose api name

---

api/tests/embedding.py

```
----------------------
Error Message Summary:
----------------------
Error: op lookup_table_v2 does not have kernel for data_type[::paddle::platform::float16]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1081)
[operator < lookup_table_v2 > error]
```
CI日志中能正确打出warning

lookup_table don't support float16 on CPU

---

api/tests/pool2d.py

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingGradOp only supports NHWC on device type CPU
[[node gradients/avg_pool_grad/AvgPoolGrad (defined at /benchmark/api/common/tensorflow_api_benchmark.py:247) ]]
```
api/tests目录下存在问题，但tests_v2目录下已修改正确。
log中可以正确打印出warning

TF AvgPoolingOp only supports NHWC on device type CPU

---

api/tests_v2/batch_norm.py

tests的batch_norm测试脚本中设置了is_test=False，即要测试的是train模式的batch_norm的性能。tests_v2的batch_norm测试脚本中，training参数写死成了False，json配置中的training参数设置的是True，脚本中应该使用config.training来设置training参数。

Change batch_norm to use config.training to set training mode.

---

api/common/main.py

原来更新repeat的逻辑，是config的repeat大小设置大于命令行的repeat设置才更新。
cumsum_1的config repeat=100, 全量脚本的repeat设置为1000，所以全量脚本跑cumsum时，repeat没有更新。

fix cumsum repeat iteration

---

api/tests_v2/configs/elementwise.json

前向测试结果如下：
- paddle
```
run command: nvprof /work/.virtualenvs_cuda10.1/paddle_py37/bin/python /work/benchmark/api/tests_v2/elementwise.py --task speed --framework paddle --json_file /work/benchmark/api/tests_v2/configs/elementwise.json --config_id 7 --check_output False --profiler none --backward False --use_gpu True --repeat 1000 --allow_adaptive_repeat False --log_level 0 --api_name add
GPU activities:   93.05%  138.60ms      1001  138.46us  138.27us  139.14us  void paddle::operators::CommonForwardBroadcastCUDAKernel<paddle::operators::AddFunctor<paddle::platform::float16, void>, paddle::platform::float16, paddle::platform::float16>(int const *, int const , int const , void const *, void const , …
```

Add an elementwise config from bert-base model.

---

api/tests/configs/activation.json
api/tests_v2/configs/activation.json

shape为[1]的activation操作，即使在网络中真实存在，也只有几us的时间，基本不会影响网络训练或预测的性能，因此删除该配置。

Delete the config of activation whose shape is [1], because it is no use for performance improvement.

---

api/deploy/main_control.sh
ci/scripts/op_benchmark.config

1. 添加`ci/scripts/op_benchmark.config`作为映射配置，其中
- `PADDLE_FILENAME_OP_MAP`表示从Paddle源文件到op的映射；
- `BENCHMARK_APINAME_OP_MAP`表示从op到benchmark测试api的映射；
2. 在`api/deploy/main_control.sh`添加打印失败日志逻辑，用于Paddle repo op性能测试流水线打印运行失败的日志；

Add config for Paddle repo op benchmark ci

---

api/common/launch.py
api/common/main.py
api/common/paddle_dynamic_api_benchmark.py
api/common/pytorch_api_benchmark.py
api/dynamic_tests_v2/abs.py
api/dynamic_tests_v2/activation.py
api/dynamic_tests_v2/cast.py
api/dynamic_tests_v2/relu.py

- 简化动态图API的测试框架，使得动态图可以沿用静态图的测试代码，只需要实现一个`build_graph`函数。
- 增加几个测试脚本：cast、relu、activation
- 修复launch.py中，解析nvprof log中GPU Activities的bug，该bug导致GPU Activities log少打印了一行

Simplify the benchmark framework of dynamic apis

---

api/dynamic_tests_v2/softmax.py

softmax 准确度log：
```
---- Initialize APIConfig from /home/gaowei/tests/benchmark/api/tests_v2/configs/softmax.json, config_id = 0.
{"name": "softmax", "device": "GPU", "backward": true, "consistent": true, "num_outputs": 2, "diff": 5.654449131142769e-10, "parameters": "x (Variable) - dtype: float32, shape: [16, 1000]\naxis (int): -1\n"}
```

add softmax dynamic tests

---

api/common/feeder.py
api/common/main.py
api/common/paddle_dynamic_api_benchmark.py
api/common/pytorch_api_benchmark.py
api/dynamic_tests_v2/linear.py
api/dynamic_tests_v2/matmul.py
api/tests/configs/layer_norm.json
api/tests/layer_norm.py
api/tests_v2/configs/layer_norm.json

- 优化反向测试，以abs为例
- paddle当前实现的nvprof
```
GPU activities:   82.68%  1.44750s        11  131.59ms  126.28ms  172.14ms  [CUDA memcpy DtoH]
13.19%  230.89ms         8  28.862ms  1.7280us  230.88ms  [CUDA memcpy HtoD]
1.29%  22.601ms        11  2.0546ms  2.0273ms  2.0763ms  void Eigen::internal::EigenMetaKernel<Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, int=1, int=1, int>, int=16, Eigen::MakePointer>, Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_product_op<float const , float const >, Eigen::TensorMap<Eigen::Tensor<float const , int=1, int=1, int>, int=16, Eigen::MakePointer> const , Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_sign_op<float const , bool=0>, …
```

Enhance the testing framework in dynamic mode

---

api/deploy/main_control.sh
api/deploy/summary.py
api/deploy/write_excel.py
api/dynamic_tests_v2/common_import.py
api/dynamic_tests_v2/cross_entropy.py
api/dynamic_tests_v2/gelu.py
api/dynamic_tests_v2/ones_like.py
api/dynamic_tests_v2/transpose.py
api/run_op_benchmark.sh
api/tests_v2/bert_base/cross_entropy.json
api/tests_v2/bert_base/dropout.json
api/tests_v2/bert_base/elementwise.json
api/tests_v2/bert_base/gelu.json
api/tests_v2/bert_base/layer_norm.json
api/tests_v2/bert_base/linear.json
api/tests_v2/bert_base/matmul.json
api/tests_v2/bert_base/ones_like.json
api/tests_v2/bert_base/softmax.json
api/tests_v2/bert_base/transpose.json
api/tests_v2/common_import.py

- 2.0的elementwise API不支持设置axis，原op测试脚本中会先对短的shape进行unsqueeze。比如X是[M, N]、Y是[N]时，Y会被unsqueeze成[1, N]。这两种配置下，paddle会选择不同的kernel来执行，且Y是[1, N]比[N]慢一倍。这个PR修改了unsqueeze_short逻辑，在这种情况下避免对Y进行unsqueeze。
- 补充bert模型里面的gelu、transpose测试脚本。
- 新增cross_entropy的测试脚本，但是目前还不能正确地运行。
- 上传bert-base中的op配置，方便大家测试。

Polish the script to run and summary all tests and add gelu, transpose.

---

api/common/paddle_dynamic_api_benchmark.py
api/common/pytorch_api_benchmark.py

移除动态图op反向性能测试，组网中的fill_constant操作。
- 优化后pytorch的nvprof如下
```
run command: nvprof /work/.virtualenvs_cuda10.1/paddle_py37/bin/python /work/benchmark/api/dynamic_tests_v2/abs.py --task speed --framework pytorch --testing_mode dynamic --json_file /work/benchmark/api/tests_v2/configs/abs.json --config_id 0 --check_output False --profiler none --backward True --use_gpu True --repeat 10 --allow_adaptive_repeat False --log_level 0
GPU activities:   82.33%  235.89ms         1  235.89ms  235.89ms  235.89ms  [CUDA memcpy HtoD]
7.31%  20.945ms        11  1.9041ms  1.9034ms  1.9051ms  void at::native::vectorized_elementwise_kernel<int=4, at::native::MulFunctor<float>, at::detail::Array<char*, int=3>>(int, float, …
```

Remove the fill_constant in backward test.

---

api/tests_v2/configs/dropout.json

添加一组bert中的dropout配置[32, 128, 768]
- FP32
```
GPU activities:   51.97%  38.688ms      1001  38.649us  37.664us  44.191us  void paddle::operators::VectorizedRandomGenerator<float, unsigned char, int=4>(unsigned long, unsigned long, float, float const *, unsigned char*, paddle::operators::VectorizedRandomGenerator<float, unsigned char, int=4>*, bool, unsigned long)
44.69%  33.266ms      1001  33.233us  32.448us  34.304us  void paddle::operators::DropoutGradCUDAKernel<float, unsigned char, int=4>(float const *, unsigned char const *, paddle::operators::DropoutGradCUDAKernel<float, unsigned char, int=4>, long, paddle::operators::DropoutGradCUDAKernel<float, unsigned char, int=4>*)
3.31%  2.4602ms         8  307.52us …
```

add dropout config

---

ci/scripts/op_benchmark.config

1. 添加Paddle repo源文件OP->benchmark repo测试脚本映射；
2. 添加白名单`SKIP_OP_MAP`用于忽略一部分OP测试；

Add mapping config for Paddle repo PR-CI-OP-benchmark

---

ci/scripts/op_benchmark.config

`pull_box_sparse`和`setitem`没有测试脚本，暂时disable。

disable pull_box_sparse and setitem quikly

---

ci/scripts/op_benchmark.config

skip conv_transpose op

---

api/common/main.py
api/common/special_op_list.py
api/common/utils.py

-  maximum, minimun, argsort 3个与pytorch对齐，跟tf不能对齐 (相同数值的输入，返回的不一样)。
- 去除掉随机op。bernoulli, dropout

fix tensorflow maximum, minimun accuracy

---

ci/scripts/op_benchmark.config

1. 移除`activation_op.cu`中`pow`的op映射；
2. 新增`conv_op.cu.cc`对应`depthwise_conv2d`，`conv2d`，`conv3d`的op映射；
3. 跳过`inplace_abn`、`lstmp`对应op测试；

add mapping config of PR-CI-OP-benchmark

---

ci/scripts/op_benchmark.config

1. `top_k`，`expand_as`属于1.8对应op，跳过这两个op测试；
2. 添加`conv_cudnn_op.cu.cc`对应op映射关系；

Add mapping config and skip ops belong to 1.8

---

api/deploy/collect_api_info.py
api/deploy/summary.py
api/deploy/write_excel.py

- summary时，从log文件名中获取compare_framework，从而不需要通过参数手动设置。
- 修复解析json结果时的一个bug：`if gpu_time_key and data["speed"].get("gpu_time", None):`，当gpu_time是0的时候，该if语句也会判为False，从而解析不到数据。
- 精简excel操作的代码，提取公共函数，并且consistent为False时，将excel中的单元格标记成红色。

Abstract the compare_framework from log and fix a bug of parsing json result when gpu_time is zero.

---

api/tests_v2/configs/tril.json
api/tests_v2/configs/triu.json
api/tests_v2/tril.py
api/tests_v2/triu.py

add tril and triu tests
由于竞品 Tensorflow 只在 2.4.0 中才有类似接口，tf.experimental.numpy.tril (https://www.tensorflow.org/api_docs/python/tf/experimental/numpy/tril?hl=pt-br%2Fjetpack)，而 benchmark 中使用的是 2.3.0 版本，这里需要关闭相关的测试，但是保留相关代码，以备 tf 升级后使用。

add tril and triu tests

---

scripts/auto_run_paddle.sh

* 每个任务每个模式均做创建根目录和代码拉取处理，并删除上一次任务的残存文件，避免相同repo不同分支引入的bug

Update benchmark path

---

api/tests_v2/configs/elementwise.json

modify atol for elementwise ops

---

api/tests_v2/configs/conv3d.json
api/tests_v2/conv3d.py

因为https://github.com/PaddlePaddle/Paddle/pull/30512 ，新增conv3d的测试脚本。这个pr暂时只添加paddle的测试，tf对齐的测试后续再依据需求添加。

Add benchmarking script for conv3d.

---

api/deploy/main_control.sh

优化`main_control.sh`逻辑，支持指定case id运行测试。
一般情况下`api_info.txt`每行第一列为API名，如果需要指定具体的配置运行，可以使用`API:case-id`的形式。

run test with specfied case id

---

dynamic_graph/lac/paddle/run_benchmark.sh
dynamic_graph/transformer/paddle/run_benchmark.sh
scripts/dynamic_graph_models.sh

**可暂缓合入**
* 动态图transformer_base 模型切换到2.0 API
* 1.8 分支基于测试得一下结果：
* 
1.8 在 iwslt14 上数据偏大主要是句子的长度的影响，batch size 4096 是一个最大的限制值，限制一个 batch 内的 token 的数目，token 这里可以理解是词的数目。也可以看到使用 iwslt14 的时候，有的 batch 会很快，有的 batch 很慢，也是因为这个限制，有的 batch 计算量实际较大，有的较小，导致不同的 batch 之间时间上差异大。较快的 batch 也就拉高了 step/s 计算的平均值。
* 更新lac 脚本

Update transformer base dy

---

api/dynamic_tests_v2/affine_grid.py
api/dynamic_tests_v2/bernoulli.py
api/dynamic_tests_v2/interp_area.py
api/dynamic_tests_v2/interp_bicubic.py
api/dynamic_tests_v2/interp_bilinear.py
api/dynamic_tests_v2/interp_linear.py
api/dynamic_tests_v2/interp_nearest.py
api/dynamic_tests_v2/interp_trilinear.py
api/dynamic_tests_v2/inverse.py
api/dynamic_tests_v2/normalize.py

add interp_area、interp_nearest、interp_linear、interp_bilinear、interp_bicubic、interp_trilinear、inverse、normalize、affine_grid、bernoulli
说明：paddle.inverse前向与torch精度未对齐，[DLTP-21639](https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-21639/show?cid=5&spaceId=23205&from=email&noticeStatistics=53380086)
paddle.nn.functional.affine_grid在config=0下，backward与pytorch精度未对齐，[[DLTP-21638]](https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-21638/show?cid=5&spaceId=23205&from=email&noticeStatistics=53379174)

add pytorch test case

---

api/tests_v2/configs/interp_bilinear.json

增加deeplabv3+中的一个耗时的配置，主要是反向的KeBilinearInterpBw耗时较多
```
run command: nvprof /root/anaconda3/envs/py36/bin/python /workspace/benchmark/api/tests_v2/interp_bilinear.py --task speed --framework paddle --json_file /workspace/benchmark/api/tests_v2/configs/interp_bilinear.json --config_id 6 --check_output False --profiler none --backward True --use_gpu True --repeat 1 --allow_adaptive_repeat False --log_level 0
GPU activities:   98.71%  32.686ms         2  16.343ms  16.270ms  16.416ms  void paddle::operators::KeBilinearInterpBw<float>(float*, unsigned long, unsigned long, unsigned long, unsigned long, paddle::operators::KeBilinearInterpBw<float> const *, unsigned long, unsigned long, unsigned long, unsigned long, unsigned …
```

add interp_bilinear config

---

api/dynamic_tests_v2/adaptive_avg_pool2d.py
api/tests_v2/configs/adaptive_avg_pool2d.json

add adaptive_avg_pool2d.py in dynamice_tests_v2 and add config for adaptive_avg_pool2d
test results:
```
[pytorch][adaptive_avg_pool2d] 
adaptive_avg_pool2d { 
run_tf: True 
run_torch: True 
repeat: 5000 
data_format: NCHW 
output_size: [32, 32] 
x_shape: [4, 2048, 64, 64] 
x_dtype: float32 
atol: 1e-06 } 
[paddle][adaptive_avg_pool2d] 
adaptive_avg_pool2d { 
run_tf: True 
run_torch: True 
repeat: 5000 
data_format: NCHW 
output_size: [32, 32] 
x_shape: [4, 2048, 64, 64] 
x_dtype: float32 
atol: 1e-06 }
{"name": "adaptive_avg_pool2d", "device": "GPU", "backward": true, "consistent": true, "num_outputs": 2, "diff": 0.0, "parameters": "x (Variable) - dtype: float32, shape: [4, 2048, 64, 64]\ndata_format (string): NCHW\noutput_size (list): [32, 32]\n"}
[pytorch][adaptive_avg_pool2d] …
```

add adaptive_avg_pool2d.py in dynamice_tests_v2

---

static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh

* 更新fp16 下的FLAGS_conv_workspace_size_limit 值
* 由于 [PR-30959](https://github.com/PaddlePaddle/Paddle/pull/30959 )   导致静态图resent50 bs208 fp16 pure& amp 单卡任务OOM  ，经 @zhangting2020 排查，根因在于该 PR对fp16类型的卷积算法开启了search功能，search的这个接口因为是根据环境变量FLAGS_conv_workspace_size_limit预先分配内存，所以这个环境变量值较大，就会引起OOM。测试调小该flag到1500，模型能正常运行，速度上和PR前设置4000持平

update_fp16_flag, test=document_fix

---

ci/scripts/op_benchmark.config

添加`pool` OP对应测试API脚本映射关系。
失败CI日志：https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/2444063/job/3431236

add Paddle repo op benchmark ci config mapping

---

api/common/special_op_list.py
api/tests_v2/configs/where_index.json
api/tests_v2/where_index.py

Ops
作用：
添加`paddle.fluid.core.ops.where_index`算子的test script
起因：
现benchmark缺乏`where_index` op的test script，导致CI的op benchmark一直失败
要点：
1. 由于`paddle.fluid.core.ops.where_index`的参数为tensor，不能直接调用。所以只能通过`paddle.fluid.layers.where`来间接调用该op，后者在实现中实际调用的就是`paddle.fluid.core.ops.where_index`。
2. 根据[where_index_op.cc#L56](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/where_index_op.cc#L56)显示，`where_index`不用计算反向梯度，因此需要将`where_index`加入`api/common/special_op_list.py`

benchmark add where_index op test script

---

ci/scripts/op_benchmark.config

修复OP `top_k_v2`到API `topk`映射关系配置错误。

fix op benchmark config error

---

ci/scripts/op_benchmark.config

修复OP性能测试CI使用的配置文件中`interpolate_op.cu`映射错误问题。
对于单文件对应多个测试API时，应仅添加在`PADDLE_FILENAME_OP_MAP`中。

fix interpolate_op.cu file config error

---

.gitmodules
dynamic_graph/seg_models/paddle/run_benchmark.sh
scripts/dynamic_graph_models.sh

* update PaddleSeg from develop f400b02 to **benchmark** ae911056a115e86d1234cc095988c69d318764d0
* 同模型RD 沟通，Seg 当前静态图需监控benchmark 分支，当框架的amp 和分布式训练稳定后 切到develop
* 动态图当前使用develop 分支，新提的动态图修改也会到该分支，所以动态图还是develop 监控
* 动态图数据(export FLAGS_cudnn_exhaustive_search=1)(单位 images/s)【动态图bs 为每张卡的bs，num_worker为每个卡的数值】：
*  flag 开启时
* deeplab 单卡 5.983 八卡 39.725
* hrnet 单卡 7.516 八卡 42.299
*  flag 未开启时
* deeplab 单卡3.477 八卡 25.124
* hrnet 单卡 7.023 八卡 41.121
* 静态图数据见#940

update_seg_models and dynamic scripts, test=document_fix

---

ci/scripts/run_test.sh

修复CI中`pre-commit`进行代码风格检查没有具体提示信息错误：
- `pre-commit install`前先`pre-commit uninstall`，避免历史数据影响当前的检查；
- 代码风格错误信息为空时，不管是否存在其他错误，均认为检查通过，不影响CI结果；

fix pre-commit run error

---

static_graph/seg_models/paddle/run_benchmark.sh

平台上hrnet静态图单卡的性能是7.388 images/s。
PaddleSeg中静态图使用老版本的DataLoader，底层基于py_reader op，训练是需要设置`--use_mpio`参数，才会使用multiprocess_reader并使用NUM_WORKER个进程来读取数据。设置了`--use_mpio`参数后，hrnet单卡训练性能可达到11.773 images/s。

Enable the use of multi-processes for data loading.

---

api/common/api_param.py
api/dynamic_tests_v2/batch_norm.py
api/tests_v2/configs/batch_norm.json

- 减少动态图batch_norm测试脚本中，反复定义和初始化running_mean和running_var的开销，具体原因在脚本中有解释。

Avoid initializing running_mean and running_var repeatly in batch_norm script.

---

api/dynamic_tests_v2/dist.py
api/tests_v2/configs/dist.json
api/tests_v2/dist.py

x_shape=[1000, 1000], y_shape=[1000, 1000], p=2
- torch
```
GPU activities:   41.79%  4.8713ms       303  16.076us  14.944us  17.216us  void at::native::vectorized_elementwise_kernel<int=4, at::native::AddFunctor<float>, at::detail::Array<char*, int=3>>(int, float, at::native::AddFunctor<float>)
17.76%  2.0702ms         2  1.0351ms  755.68us  1.3146ms  [CUDA memcpy HtoD]
16.93%  1.9734ms       202  9.7690us  9.3440us  14.304us  void at::native::unrolled_elementwise_kernel<at::native::MulFunctor<float>, at::detail::Array<char*, int=3>, OffsetCalculator<int=2, unsigned int>, OffsetCalculator<int=1, unsigned int>, at::native::memory::LoadWithoutCast, at::native::memory::StoreWithoutCast>(int, float, …
```

add dist op

---

api/tests_v2/configs/compare.json

According to [Paddle PR33086](https://github.com/PaddlePaddle/Paddle/pull/33086), adding current test case to avoid bugs undetected.

Addint test case for bugs detection in compare op.

---

scripts/pr_run_paddle.sh

修复指定PR运行时，遗漏nvidia-dali第三方库安装，导致部分模型运行失败。

fix pr run script loss nvidia-dali install

---

scripts/dynamic_graph_models.sh

修复PPOCR模型运行时，额外包含了pooch第三方库会导致模型运行失败的问题。

fix dynamic models PPOCR_mobile_2.0, test=document_fix

---

dynamic_graph/seq2seq/paddle/run_benchmark.sh

修复seq2seq benchmark在模型训练完成后，eval时显存OOM的问题。

fix seq2seq eval memory overused

---

dynamic_graph/gan_models/paddle/run_benchmark.sh
scripts/dynamic_graph_models.sh

修复benchmark动态图失败任务：
1. seq2seq模型失败是运行时间过程，导致被kill，修改方式，运行的epoch次数从2修改到1。
2. gan模型是针对CycleGAN模型时，配置文件中没有validate字段，主动传入后会导致运行异常。

fix_seq2seq_and_gan model benchmark failed

---

scripts/docker_run.sh
scripts/dynamic_graph_models.sh
scripts/static_graph_models.sh

20210723：nlp API不兼容升级，导致模型报错；暂时使用paddlenlp=2.0.5版本；后续进行子库代码升级

Update nlp version 0723

---

api/dynamic_tests_v2/conv2d.py

Fix the warning message of data_format in conv2d.py while testing pytorch framework,  owing to that pytorch does not support "nhwc"  type convolution operation.

[Fix message]: Fix the warning message of data_format in conv2d.py

---

.gitmodules
comparision_system/README.md

remove models, test=document_fix

---

api/tests_v2/model_configs/bmm.json
api/tests_v2/model_configs/conv1d.json
api/tests_v2/model_configs/depthwise_conv2d.json
api/tests_v2/model_configs/dropout.json
api/tests_v2/model_configs/elementwise_div.json
api/tests_v2/model_configs/elementwise_mul.json
api/tests_v2/model_configs/gelu.json
api/tests_v2/model_configs/group_norm.json
api/tests_v2/model_configs/index_select.json
api/tests_v2/model_configs/layer_norm.json
api/tests_v2/model_configs/slice.json
api/tests_v2/model_configs/softmax.json
api/tests_v2/model_configs/transpose.json
api/tests_v2/model_configs/unsqueeze.json

添加dropout、dropout_grad 、depthwise_conv2d、depthwise_conv2d_grad 、elementwise_mul_grad、elementwise_div_grad、gelu_grad、unsqueeze2_grad、slice_grad、layer_norm、layer_norm_grad、bmm、transpose、log_softmax、group_norm、conv1d 算子耗时配置

add time-consuming configuration of general model

---

api/common/main.py
api/dynamic_tests_v2/run.sh
api/run_op_benchmark.sh
api/tests_v2/model_configs/bmm.json
api/tests_v2/model_configs/cast.json
api/tests_v2/model_configs/dropout.json
api/tests_v2/model_configs/elementwise_div.json

1. 允许统一通过FLAGS_cudnn_exhaustive_search开启paddle和pytorch的cudnn conv穷举搜索。
2. 新增的通用模型op配置里面，有很多配置初始化HtoD占比太高，需要增大repeat，本pr中修改了几个配置。
3. 删掉elementwise，输入x、y的shape都是[1]的配置，这样的配置对于指导算子性能优化没有意义。

Allow to enable exhaustive search for paddle and pytorch with environ flags and adjust repeat for several configs.

---

api/dynamic_tests_v2/batch_norm.py
api/dynamic_tests_v2/transpose.py

添加batch_norm、transpose前向flop、byte的计算函数。
batch_norm log如下：
```cpp
Namespace(allow_adaptive_repeat=False, api_name=None, backward=False, config_id=1, convert_to_fp16=False, framework='paddle', gpu_time=15.986928104575165, json_file='/work/benchmark/api/tests_v2/configs/batch_norm.json', log_level=0, profiler='none', repeat=1000, task='speed', testing_mode='dynamic', unknown_dim=16, use_gpu=True)
[paddle][batch_norm] batch_norm {
run_tf: True
run_torch: True
data_format: NCHW
epsilon: 1e-05
training: True
momentum: 0.9
x_shape: [16, 32768]
atol: 1e-06
num_channels: 32768
param_dtype: float32
}
{"framework": "paddle", "version": "0.0.0", "name": "batch_norm", "device": "GPU", "backward": false, "speed": {"repeat": 1000, "begin": 10, "end": 990, "total": 0.10284671978074678, …
```

Enable the compute of gflop and byte for batch_norm, transpose.

---

scripts/benchmark_ci/model_ci.sh

* fix model_benchmark_ci,test=document_fix

fix model_benchmark_ci,test=document_fix

---

api/common/launch.py
api/common/paddle_api_benchmark.py
api/common/pytorch_api_benchmark.py
api/run_op_benchmark.sh

这个PR尝试实现2个功能：
1. Ampere架构上不再支持`nvporf`，需要使用`nsys`代替，来获取Kernel的GPU时间。使用nsys需要注意2点：(1) nsys非系统自带，需要提前手动安装好（2）nsys输出的日志中，Kernel和Memory分开统计，但Kernel和Memory操作都算算子的开销，因此需要统计到gpu_time中。输出如下：
```bash
$ bash run.sh concat
-- Current directory: /work/benchmark/api/dynamic_tests_v2
-- Entering /work/benchmark/api/common
-- Current directory: /work/benchmark/api/common
run command: git rev-parse HEAD
run command: git show -s --format=%ad
-- Current directory: /work/benchmark/api/dynamic_tests_v2
===========================================================================
-- paddle version             : 0.0.0
-- paddle commit              : 8da9eff4e49820e993a47da9555ec96ef70fa70c
-- pytorch version            : 1.11.0.dev20211223+cu113
-- benchmark commit           : …
```

Try to enable precise count of gpu_time with nvprof and use nsight to get gpu_time for ampere gpu.

---

api/common/launch.py
api/run_op_benchmark.sh

修复#1203 中，设置`--profiler nvprof`以获取准确的`gpu_time`碰到的问题。还是代码的问题，在原来的`args`中没有`--profiler`时，未能成功地设置`--profiler nvprof`。

Correct the setting of profiler to nvprof to get precise gpu_time.

---

scripts/auto_run_paddle.sh
scripts/dynamic_graph_models.sh
submodule.yaml

* update nlp from b15382b to 719485c674ca94dc142bbaa23b2c7777ca152f4b
*  update submodule rules[init paddle submodule only]
* firx video bugs

update nlp, update submodule init rules, fix video bugs

---

api/deploy/write_excel.py
api/dynamic_tests_v2/elementwise.py
api/tests_v2/elementwise.py

修复https://github.com/PaddlePaddle/benchmark/pull/1184#discussion_r779994622 ，maximum和minimum已经支持了float16，故不再disable。

Enable the float16 cases for maximum, minimum and divide.

---

api/tests/conv1d.py
api/tests/conv2d.py
api/tests/conv2d_transpose.py
api/tests/conv3d.py
api/tests/conv3d_transpose.py
api/tests/deformable_conv.py
api/tests/depthwise_conv2d.py
api/tests/depthwise_conv2d_transpose.py
api/tests/interp_area.py
api/tests/interp_bicubic.py
api/tests/interp_bilinear.py
api/tests/interp_linear.py
api/tests/interp_nearest.py
api/tests/interp_trilinear.py
api/tests/linear.py

迁移第6批动、静态图统一测试脚本。
CI执行情况如下：
```
2022-02-19 20:53:54 [ci/scripts/run_test.sh:132] [FATAL] ============================================
2022-02-19 20:53:54 [ci/scripts/run_test.sh:133] [FATAL] Summary problems:
2022-02-19 20:53:54 [ci/scripts/run_test.sh:139] [FATAL] There is 1 error: API test error.
2022-02-19 20:53:54 [ci/scripts/run_test.sh:141] [FATAL] ============================================
2022-02-19 20:53:54 [ci/scripts/run_test.sh:149] [FATAL] === API test error - Please fix the failed API tests accroding to fatal log:
2022-02-19 20:53:54 [ci/scripts/run_test.sh:150] [FATAL] tests/conv3d(Run on CPU) tests/depthwise_conv2d(Run on GPU) tests/depthwise_conv2d(Run on CPU) tests/interp_linear(Run on GPU) tests/interp_trilinear(Run on GPU) tests/linear(Run on GPU) tests/linear(Run on …
```

Add the 6-th part of unified tests.

---

api/dynamic_tests_v2/poisson.py
api/dynamic_tests_v2/segment_pool.py
api/tests_v2/configs/segment_pool.json

```python
===========================================================================
-- paddle version             : 0.0.0
-- paddle commit              : 051544b6e8af9cef61ba9870b4ab39af40875ce3
-- pytorch version            : 1.8.2+cu102
-- benchmark commit           : 02e0f11b3274e2c299c68ed4a4dc8bd4d4cac9cb
-- benchmark last update time : Fri Mar 4 04:17:08 2022 +0000
===========================================================================
run command: nvidia-smi -L
run command: nvprof --profile-from-start off /usr/local/bin/python /workspace/benchmark/api/dynamic_tests_v2/segment_pool.py --task speed --framework paddle --testing_mode dynamic --json_file /workspace/benchmark/api/tests_v2/configs/segment_pool.json --config_id 0 --profiler nvprof --backward True --use_gpu True …
```

Add segment pool benchmark. test=document_fix

---

api/dynamic_tests_v2/maxout.py
api/dynamic_tests_v2/put_along_axis.py
api/dynamic_tests_v2/take_along_axis.py
api/tests_v2/configs/maxout.json
api/tests_v2/configs/put_along_axis.json
api/tests_v2/configs/take_along_axis.json

add benchmark for maxout/put_along_axis/take_along_axis
测试结果已添加。

add benchmark for maxout/put_along_axis/take_along_axis

---

api/dynamic_tests_v2/nll_loss.py
api/dynamic_tests_v2/selu.py
api/tests_v2/configs/nll_loss.json
api/tests_v2/configs/selu.json

为 selu 和 nll_loss 添加了 op benchmark
selu 测试结果： 
nll_loss 测试结果：

[OpBenchmark] add op_benchmark for  selu, nll_loss

---

api/dynamic_tests_v2/cumprod.py
api/tests_v2/configs/cumprod.json

[Op Benchmark] add cumprod op benchmark

---

api/dynamic_tests_v2/shard_index.py
api/tests_v2/configs/shard_index.json

添加 shard_index 算子 benchmark 测试脚本，TF和touch中无该算子的对照。

Add shard_index op benchmark

---

api/tests_v2/configs/p_norm.json

Add benchmark for frobenius_norm OP, test result:

Add benchmark for frobenius_norm OP

---

.gitmodules
frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/prepare.sh

1. 防止req的deps覆盖torch 1.8，因此将torch安装顺序后置并设为强制安装
2. TimeSformer链接从git@更新为https
3. TimeSformer用pip安装代替build develop.
4. 预训练模型链接更换，加快下载速度

update TimeSformer and prepare.sh

---

api/common/api_param.py
api/common/paddle_op_benchmark.py
api/common/tensorflow_op_benchmark.py
api/common/utils.py
api/tests/activation.py
api/tests/common_import.py
api/tests/compare.py
api/tests/elementwise.py
api/tests/isfinite_nan_inf.py
api/tests/reduce.py
api/tests/reduce_all_any.py
api/tests/relu.py
api/tests/run.sh

1. tf移除1.15.0以下的版本支持，要求必须大于1.15.0。
2. 支持tf测试的精确计时。
3. 统一测试脚本里面，对一些复杂情况添加tf测试的支持。

Enhance the static mode of unified tests.

---

api/tests_v2/batch_norm.py
api/tests_v2/configs/batch_norm.json
api/tests_v2/while_loop.py

1. 更新tf的batch_norm测试脚本，支持NCHW测试。
2. 删除while_loop测试脚本中，低于1.15.0版本的代码。

Update batch_norm and while_loop tests for tf.

---

api/dynamic_tests_v2/matrix_rank.py
api/tests_v2/configs/matrix_rank.json

添加matrix_rank op测试脚本
matrix_rank 迁移前
[paddle][matrix_rank] matrix_rank {
run_tf: True
run_torch: True
tol: 0.01
hermitian: False
x_shape: [5, 24, 10, 10]
atol: 1e-06
}
{"framework": "paddle", "version": "0.0.0", "name": "matrix_rank", "device": "GPU", "backward": false, "speed": {"repeat": 1000, "begin": 10, "end": 990, "total": 47.527849917509116, "wall_time": 0, "total_include_wall_time": 47.527849917509116, "gpu_time": 31.667926565874733}, "parameters": "x (Variable) - dtype: float32, shape: [5, 24, 10, 10]\nhermitian (bool): False\ntol (float): 0.01\n"}
matrix_rank迁移后
[paddle][matrix_rank] matrix_rank {
run_tf: True
run_torch: True
tol: 0.01
hermitian: False
x_shape: [5, 24, 10, 10]
atol: 1e-06
}
{"framework": "paddle", "version": "0.0.0", "name": …

add benchmark for matrix_rank,test=document_fix

---

api/dynamic_tests_v2/multiplex.py
api/dynamic_tests_v2/qr.py
api/tests_v2/configs/multiplex.json
api/tests_v2/configs/qr.json

This pr adds multiplex and qr benchmark.
multiplex result：
qr result:

add multiplex and qr benchmark

---

ci/scripts/op_benchmark.config

Paddle中存在一个文件对应多个OP的情况，需要添加文件名到OP名的映射，OP Benchmark CI才能测试到相应的算子。
OP从operators迁移到phi目录后，文件命名方式都不一样了，因此需要修改映射的map。
本PR修改了`conv`和`tril_triu`的映射。

Update the map of directory name to apis of conv.

---

api/common/launch.py
api/common/tensorflow_op_benchmark.py

添加一个参数`profile_from_start`，允许从程序开始就profile，以便做一些性能调试，比如观察conv是否开启了exhaustive search。

Add a argument to allow profile from start for debuging purpose.

---

api/deploy/collect_api_info.py
api/deploy/main_control.sh
api/dynamic_tests_v2/deformable_conv.py
api/run_op_benchmark.sh

修复一键运行脚本run_op_benchmark.sh无法启动全量测试的问题。https://github.com/PaddlePaddle/benchmark/pull/1410 给main_control.sh新增了OP_NAME参数，默认值为"None"，run_op_benchmark.sh没有设置该参数，导致生成的op_list为空。

Fix the failure of running all scripts and update torch's version.

---

Inference/c++/ernie/inference.cc

This PR fixes ernie script. In our validation system we are using this Ernie script for testing. Because Ernie model is unreasonably setting a output tensor persistable,  pass `constant_folding_pass` throwing an error.

Correct Ernie script 

---

api/dynamic_tests_v2/cross_entropy.py
api/tests/cross_entropy.py
api/tests_v2/configs/cross_entropy.json
ci/scripts/op_benchmark.config
ci/scripts/run_test.sh

Paddle主repo中OP Benchmark CI报错如下：
CI链接：https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/6746927/job/18870645
op benchmark中测试脚本为softmax_with_cross_entropy，故改名。

Rename  softmax_with_cross_entropy to cross_entropy.

---

api/tests_v2/configs/lerp.json

该配置在文生图模型中用到，性能差于pytorch 150+倍。详情如下：
**[16, 1, 1, 1] [16, 3, 224, 224]**
- paddle
```
run command: nvprof --profile-from-start off /work/.virtualenvs_cuda11.2/paddle_py38/bin/python /work/benchmark/api/dynamic_tests_v2/lerp.py --task speed --framework paddle --testing_mode dynamic --json_file /work/benchmark/api/tests_v2/configs/lerp.json --config_id 2 --profiler nvprof --backward True --use_gpu True --repeat 1000 --allow_adaptive_repeat False --unknown_dim 16 --log_level 0
GPU activities:   99.86%  165.087s      1000  165.09ms  164.94ms  169.69ms  void Eigen::internal::EigenMetaKernel<Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, int=4, int=1, long>, int=0, Eigen::MakePointer>, …
```

Change the 2-nd config of lerp.

---

ci/scripts/op_benchmark.config
ci/scripts/run_test.sh

1. 修复CI问题，更新nightly编译Paddle WHL包的下载链接。
2. 增加`arg_min_max_kernel.cu`到`argmax`、`argmin`的映射，修复Paddle主repo中OP Benchmark CI无法正确识别和测试argmax、argmin性能的问题：

Fix CI and add the mapping of argmin and argmax.

---

api/common/api_param.py
api/common/benchmark.py
api/common/pytorch_op_benchmark.py
api/dynamic_tests_v2/gather.py
api/dynamic_tests_v2/run.sh
api/tests/allclose.py
api/tests/gather.py
api/tests/run.sh
api/tests/test_main.py
api/tests_v2/configs/allclose.json
api/tests_v2/configs/gather.json
api/tests_v2/gather.py
api/tests_v2/run.sh
ci/scripts/run_test.sh

1. 增加`build_graph`的默认实现，通过在json中配置paddle_api、torch_api的函数签名（包括参数列表，并且paddle与pytorch的参数需要一一对应），自动加载、调用相应函数，目前只支持前向。

Add default implementation of build_graph.

---

api/common/special_op_list.py
api/deploy/op_benchmark_unit.py
api/deploy/write_excel.py
api/run_op_benchmark.sh

全量测试脚本`run_op_benchmark.sh`支持通过第4个参数，设置只跑cpu或gpu测试；相应地`summary.py`解析脚本生成excel时，也支持只生成cpu、gpu的选项卡数据。

Support only run gpu.

---

api/dynamic_tests_v2/group_norm.py
api/tests_v2/configs/group_norm.json
ci/scripts/run_test.sh

#1164 此PR在group_norm脚本中加入了对torch的版本判断，但是ci中不会安装和运行torch，因此会报错

Fix ci problem in GroupNorm and add more configs

---

api/tests/eigh.py

Eigh API反向传播的时候，使用单独的W或者V对X求导都是没有意义的.

fix eigh backward test case

---

scripts/benchmark_ci/model_ci.sh
scripts/benchmark_ci/run_models.sh

add resnet_bs64_fp16 for model_benchmark_ci

add resnet_bs64_fp16 for model_benchmark_ci

---

api/common/api_param.py
api/common/benchmark.py
api/common/launch.py
api/common/paddle_op_benchmark.py
api/common/special_op_list.py
api/tests/activation.py
api/tests/batch_norm.py
api/tests/concat.py
api/tests/expand_as.py
api/tests/set_value.py
api/tests/size.py
api/tests/slice.py
api/tests/split.py
api/tests/stack.py
api/tests/unstack.py
api/tests_v2/configs/set_value.json
api/tests_v2/configs/size.json

本PR工作如下：
- 主体执行和日志解析部分：
- 调整日志解析部分，nsight命令执行返回不成功也尝试去解析日志，解析成功则返回GPU时间。
- 解析GPU时间外层添加try-except，防止字符串转float报错而退出
- 测试脚本部分
- 添加set_value torch测试类；set_value因不存在反向算子，故加入no_backward_list
- 添加激活函数swish的测试
- size算子的调用从fluid接口改成`paddle.numel`
- 添加concat、split、stack、unstack算子flop和gbs的计算
- expand_as、slice显式调用`contiguous()`调用，关闭view机制，以获得真实的kernel时间。

Disable view for some torch api tests.

---

api/tests/fused_rotary_position_embedding.py
api/tests_v2/configs/fused_rotary_position_embedding.json

Add test fused_rope api and configs
results:
| dims of q | dims of k| cached_sin_cos | use_neox_rotary_style | dtype | average_time (ms) |
|:-:|:-:|:-:|:-:|:-:|:-:|
| [4, 4096, 32, 128] | [4, 4096, 32, 128] | True | False | float32 | 1.6308 |
| [4, 4096, 32, 128] | [4, 4096, 4, 128] | True | False | float32 | 0.70488 |
| [4, 4096, 32, 128] | [4, 4096, 32, 128] | True | True | float32 | 1.5846 |
| [4, 4096, 32, 128] | [4, 4096, 4, 128] | True | True | float32 | 0.65717 |
NOTE: `average_time` indicates the average time cost of testing 1000 times

Add fused_rope benchmark

---

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/llama/benchmark_common/run_benchmark.sh

llama模型，如果worker=0，会导致线程间gil锁竞争。影响模型性能。

benchmark llama worker=1
