PaddingRNN/lstm_paddle/args.py, PaddingRNN/lstm_paddle/logs/log_infer_gpu_1.txt, PaddingRNN/lstm_paddle/logs/log_infer_gpu_32.txt, PaddingRNN/lstm_paddle/train.py
In the current implementation of PaddingRNN, infer is done by calling the `eval` function, which run the whole main_program, see
https://github.com/PaddlePaddle/benchmark/blob/2ce1cea026ed08a3d7d75cfec554000197c54c3e/PaddingRNN/lstm_paddle/train.py#L222-L224
I add profiler and the profiling result is:
```
------------------------->     Profiling Report     <-------------------------
Place: All
Time unit: ms
Sorted by total time in descending order in the same thread
Event                                             Calls       Total       CPU Time (Ratio)        GPU Time (Ratio)        Min.        Max.        Ave.        Ratio.      
thread4::sum                                      84650       21461.1     8349.927323 (0.389073)  13111.131332 (0.610927) 0.017111    51.2725     0.253527 …
```
=> Refine the timing of PaddingRNN and optimize the infer implementation.

CycleGAN/paddle/layers.py, CycleGAN/paddle/train.sh
=> Make cycle gan faster

CycleGAN/paddle/train.py, PaddingRNN/lstm_paddle/train.py
Also merged conflict and use yapf to format python train.py script.
Help reviewers:
A lot of changes in this PR are format change. 
The multi-card changes are code blocks with "if device_count > 1 and args.parallel:"
=> Add multi-card to PaddingRNN

deeplabv3+/paddle/README.md, deeplabv3+/paddle/data_utils.py, deeplabv3+/paddle/reader.py, deeplabv3+/paddle/train.py, deeplabv3+/tensorflow/README.md, deeplabv3+/tensorflow/readme.md, deeplabv3+/tensorflow/run.sh
在@qingqing01 的帮助下，使用python的multiprocessing优化数据读取和预处理部分。该修改仅用于当前测试。待`models`下面deeplabv3+同步更新了之后，将以models下面的为准。
=> Speedup the training of deeplab using multiprocessing to read data, and refine the run.sh.

PaddingRNN/lstm_paddle/lm_model.py, PaddingRNN/lstm_paddle/run.sh, PaddingRNN/lstm_paddle/train.py
Fix compile time shape of PaddingRNN model.
=> Modify padding rnn model

se-resnext/paddle/dist_utils.py, se-resnext/paddle/run_with_multi_process.sh, se-resnext/paddle/train.py
TODO: How to split training data for multi-procession.
=> Use multi-process to train se_resnext

Mask-RCNN/paddle/rcnn/train.py, auto_run_paddle.sh
Reverts PaddlePaddle/benchmark#89
=> Revert "Revert multi process in mask rcnn"

PaddingRNN/lstm_paddle/lm_model.py, PaddingRNN/lstm_paddle/train.py
This PR depends on https://github.com/PaddlePaddle/Paddle/pull/17236 .
=>  Optimize PaddingRNN using fused_elementwise_activation op.

PaddingRNN/lstm_paddle/run.sh
Reverts PaddlePaddle/benchmark#93
=> Revert "Disbale gc flags for PaddingRNN."

PaddingRNN/lstm_paddle/lm_model.py, PaddingRNN/lstm_paddle/run.sh
This depends on https://github.com/PaddlePaddle/Paddle/pull/18041
=> Set "save_intermediate_out=False" for fused_elewise_activation API.

GAN_models/PaddleGAN/run.sh
Usage:
```
bash run.sh train speed Pix2pix
bash run.sh train speed DCGAN
bash run.sh train speed CGAN
```
=> Add GAN model benchmark script

STGAN/paddle/run_stgan.sh, STGAN/tensorflow/run_stgan.sh, StarGAN/paddle/run_stargan.sh, StarGAN/pytorch/run_stargan.sh
=> adjust discriminator time to 1 in stargan and stgan

se-resnext/paddle/run.sh
usage:
```
bash run.sh speed 32 sp ResNet50
bash run.sh speed 32 sp ResNet101
bash run.sh speed 32 sp SE_ResNeXt50_32x4d
```
=> Add resnet50 and resnet101

Inference/c++/ernie/CMakeLists.txt, Inference/c++/ernie/inference.cc, Inference/c++/ernie/run.sh
- fix iomp link
- 添加threads 设置。
当前threads设为20. 速度可以到62.57ms
```
Load 10 samples from /home/tangjian/paddle-benchmark-tj/Inference/c++/ernie/seq128_data/test_ds_10
I0821 13:13:34.897656  3389 inference.cc:353] Run 10 samples, average latency: 68.0183 ms per sample.
I0821 13:13:34.897750  3389 inference.cc:358] Run 9 samples, average latency [exclude 1 warmup steps]: 62.5753 ms per sample.
```
=> fix iomp and add num threads setting

.gitmodules, scripts/analysis.py, se-resnext/pytorch/run_examples.sh, se-resnext/pytorch/run_senet.sh, se-resnext/pytorch/run_vision.sh, seq2seq/paddle/run.sh, seq2seq/tensorflow/run.sh
Paddle model, please test https://github.com/PaddlePaddle/models/pull/3168
=> Add benchmark for seq2seq model

NeuralMachineTranslation/Transformer/fluid/train/run.sh, NeuralMachineTranslation/Transformer/fluid/train/run_benchmark.sh, NeuralMachineTranslation/Transformer/fluid/train/run_with_multi_process.sh
update the run.sh for the model update
=> Transformer revise

static_graph/NeuralMachineTranslation/Transformer/fluid/train/run.sh, static_graph/NeuralMachineTranslation/Transformer/fluid/train/run_benchmark.sh
=> fix multiple process run.sh

scripts/run_model.sh, static_graph/BiDAF/paddle/run_benchmark.sh, static_graph/BiDAF/tensorflow/run_benchmark.sh
Related to [Paddle#19779](https://github.com/PaddlePaddle/Paddle/pull/19779).
=> Refine oom msg grep

.gitmodules, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/NextVlad/tensorflow/run.sh
=> Add nextvlad benchmark

static_graph/NextVlad/paddle/run_benchmark.sh
=> refine nextvlad script

static_graph/Detection/paddle/run_benchmark.sh
refine the run_benchmark script for set the base_lr and batch_size
base_lr for nan problem 
batch_size for alignment with pytorch
=> refine the run_benchmark script 

static_graph/Detection/paddle/run_benchmark.sh
cost time to find https://github.com/PaddlePaddle/Paddle/pull/19780 make cascade performance reduce 
we fix the bug using https://github.com/PaddlePaddle/Paddle/pull/20662
according to PR20662, we make this fix
=> add FLAG to improve performance

scripts/auto_run_paddle.sh, static_graph/BERT/paddle/run_benchmark.sh, static_graph/CycleGAN/paddle/run_benchmark.sh, static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh, static_graph/STGAN/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark.sh, static_graph/seq2seq/paddle/run_benchmark.sh
+ 更新run_benchmark.sh脚本
- 在bert，cyclegan，padding，stgan，seq2seq 模型run_benchmark.sh加上kill Python进程
- 在image_classification的run_benchmark.sh删掉image_shape参数
=> add kill python for models

api/accuracy/abs.py, api/accuracy/args.py, api/accuracy/conv2d.py, api/accuracy/dropout.py, api/accuracy/elementwise_add.py, api/accuracy/embedding.py, api/accuracy/matmul.py, api/accuracy/reduce_sum.py, api/accuracy/run.sh, api/accuracy/transpose.py, api/common/paddle_api_benchmark.py, api/common/tensorflow_api_benchmark.py, api/common/utils.py
- conv2d前向:
```
{
framework: "paddle",
version: "0.0.0",
name: "conv2d",
device: "GPU",
speed: { repeat: 1, start: 0, end: 1, total: 349.17903, feed: 0.00000, compute: 0.00000, fetch: 0.00000 }
}
{
framework: "tensorflow",
version: "1.14.0",
name: "conv2d",
device: "GPU",
speed: { repeat: 1, start: 0, end: 1, total: 989.34293, feed: 0.00000, compute: 0.00000, fetch: 0.00000 }
}
{ name: "conv2d", consistent: "True", num_outputs: 1, diff: 0.00000 }
```
- transpose前向：
```
{
framework: "paddle",
version: "0.0.0",
name: "transpose",
device: "GPU",
speed: { repeat: 1, start: 0, end: 1, total: 7.07603, feed: 0.00000, compute: 0.00000, fetch: 0.00000 }
}
{
framework: "tensorflow",
version: "1.14.0",
name: "transpose",
device: "GPU",
speed: { repeat: 1, start: 0, end: 1, total: 899.75500, feed: …
```
=> Add the accuracy check between tensorflow of some API.

scripts/auto_run_paddle.sh, static_graph/NextVlad/paddle/run_benchmark.sh
* fix ctcn benchmark 脚本
* 修改ctcn对应的yaml文件
* 添加ctcn 数据集
=> fix_ctcn_data_sh

scripts/auto_run_paddle.sh, static_graph/NextVlad/paddle/run_benchmark.sh
=> add_vedio_ben

scripts/auto_run_paddle.sh, static_graph/image_classification/paddle/run_benchmark.sh
=> update the skip_steps and max_iters for image_classification

Inference/c++/ernie/inference.cc
This functionality enables data reader to automatically detect whether we are dealing with 2D or 4D input and parses it accordingly.
=> Support 2D input in data reader

Inference/c++/ernie/mkldnn/README.md
=> Ernie QAT INT8 document [MKLDNN]

api/accuracy/batch_norm.py, api/accuracy/slice.py, api/accuracy/squeeze.py, api/common/utils.py
Adding OP accuracy with tensorflow
=> add api accuracy for BN slice and squeeze OP

api/accuracy/gather.py, api/accuracy/sigmoid.py, api/accuracy/split.py, api/accuracy/stack.py, api/accuracy/topk.py
Add API accuracy for tensorflow and paddle
split OP
gather OP 
topk
sigmoid
stack
=> Add Api accuracy compare for tf and Paddle

scripts/auto_run_paddle.sh, static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh
+ 修改auto_paddle_run.sh的格式问题，删掉libcupti 的export
+ 修改paddingRnn的skip_step=1，fuse后第一个step太慢
+ 修改enable_auto_fusion=True
=> modify_paddingRNN

Inference/c++/ernie/mkldnn/README.md
fix the QAT Ernie MKL-DNN document, command and document
=> fix the QAT Ernie MKL-DNN document

scripts/analysis.py, scripts/auto_run_paddle.sh, scripts/run_model.sh, scripts/save.py, scripts/template.py, static_graph/AttGAN/paddle/run_benchmark.sh, static_graph/BERT/paddle/run_benchmark.sh, static_graph/CycleGAN/paddle/run_benchmark.sh, static_graph/DDPG_Deep_Explore/Fluid_version/run_benchmark.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/GAN_models/PaddleGAN/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh, static_graph/STGAN/paddle/run_benchmark.sh, static_graph/StarGAN/paddle/run_benchmark.sh, static_graph/Transformer/paddle/run_benchmark.sh, static_graph/deeplabv3+/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark.sh, static_graph/seq2seq/paddle/run_benchmark.sh, static_graph/yolov3/paddle/run_benchmark.sh
+ 增加了profiler的数据传输和框架计算信息的提取；
+ 修改原来脚本的index为数据库中的数字，免去在插入数据过程的转换，以及添加指标的时候，字典的更新；
---
**后续todo**
- profiler的匹配有些生硬，需要转成正则表达式，并验证其他模型脚本是否需要改动
=> Restruct scripts

scripts/auto_run_paddle.sh
=> modify profiler file_name

competitive_products/common_scripts/run_model.sh, competitive_products/py_benchmark/py_auto.sh, competitive_products/py_benchmark/scripts/py_final_ana.sh, static_graph/Detection/pytorch/run_detectron.sh, static_graph/GAN_models/PytorchGAN/run.sh, static_graph/StarGAN/pytorch/run_stargan.sh, static_graph/image_classification/pytorch/run_senet.sh, static_graph/image_classification/pytorch/run_vision.sh
* add competitive products of pytorch scripts
*  update the detection, pix2pix, stargan, image_classification pytorch script
* add auto_run script competitive_products/py_benchmark/py_auto.sh
=> add_com_products_benchmark

competitive_products/common_scripts/run_model.sh, competitive_products/py_benchmark/py_auto.sh, competitive_products/py_benchmark/scripts/py_final_ana.sh, competitive_products/tf_benchmark/scripts/tf_final_ana.sh, competitive_products/tf_benchmark/tf_auto.sh, static_graph/CycleGAN/tensorflow/run_cyclegan.sh, static_graph/Detection/pytorch/run_detectron.sh, static_graph/GAN_models/PytorchGAN/run.sh, static_graph/NextVlad/tensorflow/run.sh, static_graph/PaddingRNN/lstm_tf/run.sh, static_graph/STGAN/tensorflow/run_stgan.sh, static_graph/StarGAN/pytorch/run_stargan.sh, static_graph/Transformer/tensor2tensor/train_ende_bpe.sh, static_graph/deeplabv3+/tensorflow/run.sh, static_graph/image_classification/pytorch/run_senet.sh, static_graph/image_classification/pytorch/run_vision.sh, static_graph/seq2seq/tensorflow/run_benchmark.sh
*  add tf auto scripts and final result analysis scripts
*  update the padding, nextvlad, seq2seq, deeplabv3, cyclegan, transformer model run_scripts
*  analysis the result by using the $BENCHMARK_ROOT/scripts/analysis.py
*  fix some  params for analysis
*  add the  stgan run scripts
=> Add com products benchmark

scripts/auto_run_paddle.sh, scripts/docker_run.sh, scripts/template.py
+ rm http_proxy config in scripts
+ rm email config in scripts
=> save delete

.gitmodules
* add PaddleDetection submodels in benchmark
=> add_PaddleDetection_submodels

.gitmodules
* add PaddleSeg submodels in benchmark
=> add_paddleseg_submodel

scripts/auto_run_paddle.sh
=> fix cyclegan scripts

api/common/api_database.py, api/common/api_param.py
将api配置写入数据库：
python api_database.py --log_file=XXX --server_file=XXX
=> Add api info into database

scripts/run_test.sh
=> add run_test.sh

scripts/run_test.sh
完善修改run_test.sh中关于检查代码风格的代码，并添加abort函数
#362
=> modify check coede style script and add abort function.

scripts/run_test.sh
增加 增量op的测试
**说明** CI中的报错：
>[09:25:24][Step 1/1] + cd /benchmark
[09:25:24][Step 1/1] + python scripts/print_signature.py api/tests
[09:25:24][Step 1/1] python: can't open file 'scripts/print_signature.py': [Errno 2] No such file or directory
[09:25:42][Step 1/1] Process exited with code 2
[09:25:42][Step 1/1] Process exited with code 2 (Step: Command Line)
找不到 'scripts/print_signature.py'是由于本次pr新增了该文件 所以在原master分支是没有该文件的。
=> diff op test

api/tests/examples/while_loop.json, api/tests/while_loop.py
=> While loop

scripts/run_test.sh
将docker run命令从teamcity CI配置脚本移出，方便修改paddle镜像
=> add build docker

Inference/c++/ernie/mkldnn/README.md
Update results with release/1.8
=> Update ernie dnnl benchmark

scripts/analysis.py, scripts/config.ini, scripts/run_model.sh, scripts/save.py, static_graph/AttGAN/paddle/run_benchmark.sh, static_graph/BERT/paddle/run_benchmark.sh, static_graph/CycleGAN/paddle/run_benchmark.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/GAN_models/PaddleGAN/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh, static_graph/STGAN/paddle/run_benchmark.sh, static_graph/StarGAN/paddle/run_benchmark.sh, static_graph/Transformer/paddle/run_benchmark.sh, static_graph/deeplabv3+/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark.sh, static_graph/seq2seq/paddle/run_benchmark.sh, static_graph/yolov3/paddle/run_benchmark.sh
+ 在脚本种增加模型所属方向和任务信息
+ 增加一个统一维护的方向信息和任务信息配置文件
+ 统一脚本风格
=> add mission info

dynamic_graph/mobilenet/paddle/run_benchmark.sh
* add mobilenet script for dygraph
=> add_dygraph_mobilenet1

scripts/dynamic_graph_models.sh
+ update submodule
+ modify dy scripts
=> update submodule & modify dy scripts

scripts/docker_run.sh
+ fix http proxy bug 
+ proxy spell error
=> fix http proxy

api/common/api_param.py
错误修复：api参数读取时，string类型到bool类型转换。
=>  Fix character conversion to Boolean

api/common/tensorflow_api_benchmark.py
=> refine the profiler for higher version test=develop

scripts/docker_run.sh, scripts/save.py
+ 修复了邮件生成但是未发送的bug
+ 动态图搜集CPU和GPU信息
=> fix email bug

dynamic_graph/mobilenet/paddle/run_benchmark.sh, dynamic_graph/ptb/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark.sh, dynamic_graph/seq2seq/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
+ add dygraph bencharkk scripts
+ transformer
+ ptb_lm
+ seq2seq
+ resnet
=> add_dymodels benchmark script

dynamic_graph/ptb/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
=> bug_fix in dygraph

api/common/api_param.py, api/common/utils.py
1. 增加对shape中-1的支持，默认转换成16。
2. 误差判断功能，增加输出结果为bool类型的支持。
=> add shape support and compare bool type

api/tests/common_import.py, api/tests/examples/leaky_relu.json, api/tests/examples/logical_not.json, api/tests/examples/sequence_mask.json, api/tests/examples/shape.json, api/tests/leaky_relu.py, api/tests/logical_not.py, api/tests/sequence_mask.py, api/tests/shape.py
add 4 API test：
leaky_relu, logical_not,  sequence_mask, shape
=> add API test

scripts/docker_run.sh
+ if paddle build failed，function named run_models will exit;
+ add annotate for some functions
=> build failed, Don't run models

dynamic_graph/mobilenet/paddle/run_benchmark.sh, dynamic_graph/ptb/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
=> add comments for dygraph

api/tests/examples/increment.json, api/tests/increment.py
添加`fluid.layers.increment`的benchmark测试脚本
=> Add script file to benchmark increment

scripts/save.py, scripts/template.py
+ split email template to speed, profile, memory
=> moidfy email template

api/common/api_param.py, api/common/utils.py, api/tests/main.py
测试结果增加parammeters打印：
- 使用"parameters"关键词
- 根据输入变量和参数的 'name'特征，字母排序打印输出。
- unsqueeze, 普通API
```
{"framework": "paddle", "version": "0.0.0", "name": "unsqueeze", "device": "CPU", "precision": {"stable": true, "diff": 0.0}, "speed": {"repeat": 1, "begin": 0, "end": 1, "total": 0.5812644958496094, "wall_time": 0.026941299438476562, "total_include_wall_time": 0.6082057952880859, "gpu_time": 0}, "parameters": "input (Variable) - dtype: float32, shape: [32, 128, 256]\naxes (int): 1\n"}
```
- conv2d, 复杂参数API
```
{"framework": "paddle", "version": "0.0.0", "name": "conv2d", "device": "CPU", "precision": {"stable": true, "diff": 0.0}, "speed": {"repeat": 1, "begin": 0, "end": 1, "total": 111.09590530395508, "wall_time": 0.030994415283203125, "total_include_wall_time": 111.12689971923828, …
```
=> add print parameters

api/deploy/main_control.sh
=> fix filename

api/deploy/summary.py
fix assignment bug when op running state is error!
=> fix assignment bug

api/tests/examples/softmax_with_cross_entropy.json, api/tests/softmax_with_cross_entropy.py
修复softmax_with_cross_entropy脚本和json文件。
=> Fix bugs of softmax_with_cross_entropy

api/deploy/summary.py
fix parameter not shown when some op case partially run failed
=> fix parameter not shown

api/deploy/summary.py
directory path parameter transferred mode modified
=> discard the fixed path

api/deploy/summary.py
delete logic that  about on duplicate key update...
=> modify database execution statement

dynamic_graph/mobilenet/paddle/run_benchmark.sh, dynamic_graph/ptb/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark.sh, dynamic_graph/seq2seq/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/run_model.sh
1. mobilenet改成使用batch_size=128
2. resnet代码更新之后，可使用ILSVRC2012数据集
3. seq2seq使用de-en数据集测试
4. 所有的动态图模型多卡都使用mp方式，所以删除了sp、mp参数。
5. 增大了一些模型的iter/epoch数
=> Update arguments of dygraph's tesing script files.

dynamic_graph/seq2seq/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
动态图seq2seq使用de-en数据集时，少设置了max_epoch参数。
=> Update the arguments of seq2seq.

dynamic_graph/mobilenet/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark.sh, dynamic_graph/seq2seq/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* update scripts for dygraph
*  update the dataset of seq2seq and mobilnet
*  add the run_mode for 8mp models(mobilenet transformer resnet)
=> update scripts for dygraph

scripts/docker_run.sh, scripts/static_graph_models.sh, static_graph/yolov3/paddle/run_benchmark.sh
* delete ptb param in yolov3
* PaddleDetection repo 目前可视化部分改为依赖visualdl（要求visualdl > 2.0.0.b ，Python>3）该功能在benchmark 用不到，故而删除该参数
* add shm-size param in docker build
=> delete ptb param in yolov3

dynamic_graph/seq2seq/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* update the keyword of dy_seq2seq
* add dy_transformer multi gpu mode
=> Update seq2seq keyword

scripts/docker_run.sh, scripts/save.py, static_graph/AttGAN/paddle/run_benchmark.sh, static_graph/BERT/paddle/run_benchmark.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/STGAN/paddle/run_benchmark.sh, static_graph/StarGAN/paddle/run_benchmark.sh, static_graph/Transformer/paddle/run_benchmark.sh, static_graph/deeplabv3+/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark.sh, static_graph/yolov3/paddle/run_benchmark.sh
* add delete dir before run multi thread mode
* delete the current time train data when analysis results
* remove the cpu docker build
=> fix_mp_bug

api/tests/clip_by_norm.py, api/tests/configs/lstm.json, api/tests/examples/lstm.json, api/tests/lstm.py
=> Add script of lstm.

scripts/static_graph_models.sh, static_graph/Detection/paddle/run_benchmark.sh
* 显存爆掉模型hang住问题暂未修复，暂时去掉 detection 下8卡最大batch_size
* cascade_rcnn_fpn 高概率偶现elementwise_add error和generate_proposals error ，见[DLTP-7102](http://newicafe.baidu.com:80/issue/DLTP-7102/show?from=page)，RD @sunxiaolong 告知降低学习率
=> Update detection lr

competitive_products/pytorch_benchmark/pytorch_auto.sh, competitive_products/tensorflow_benchmark/scripts/tf_final_ana.sh, competitive_products/tensorflow_benchmark/tensorflow_auto.sh, static_graph/Detection/pytorch/run_detectron.sh
* add cascade_rcnn_fpn models in pytorch scripts
=> Update py cascade

api/tests/accuracy.py
Revise Tensorflow Op accuracy's feeding/usage to match Paddle's result
=> Revise TFAccuracy to match Paddle result

api/deploy/docker_run.sh, api/deploy/summary.py
+ 修改原来的本地固定编译容器和编译模式为自动创建容器编译；
+ 修改原来的本地固定容器运行op case为自动创建容器执行；
+ 修改原来的本地固定容器插入数据库；
+ 修改部分bug；
=> add run.sh

api/tests/slice.py
Modify index of starts and ends from axes' value to its count/index
=> Revise index to match TF and Paddle Op slice

api/deploy/docker_run.sh, static_graph/Detection/paddle/run_benchmark.sh
* update the gcc version of compile
* update the batch_size param in detection models
=> Update gcc version of compile and batch_size param in detection models

scripts/static_graph_models.sh
=> rm_CTCN_temporarily

api/deploy/docker_run.sh
=> add cuda_visible

api/tests/case.py, api/tests/switch_case.py
修改`case`和`switch_case`的脚本文件，使其每次运行均执行相同分支，从而避免因随机输入而可能导致的执行结果（性能表现）的不确定。
=> Modify the srcipt files of case and switch

api/deploy/docker_run.sh
+ 当前GPU和CPU任务都是并行跑，其中GPU任务数据正常，CPU任务数据异常，故按照@骆涛老师建议CPU依然为串行跑，待脚本支持后在并行跑，因此改为如下模式：
+ GPU并行
+ CPU串行
=> splist task to GPU & CPU

scripts/run_model.sh, scripts/save.py, scripts/static_graph_models.sh, static_graph/BERT/paddle/run_benchmark.sh, static_graph/CycleGAN/paddle/run_benchmark.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/GAN_models/PaddleGAN/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh, static_graph/STGAN/paddle/run_benchmark.sh, static_graph/StarGAN/paddle/run_benchmark.sh, static_graph/Transformer/paddle/run_benchmark.sh, static_graph/deeplabv3+/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark.sh, static_graph/seq2seq/paddle/run_benchmark.sh, static_graph/yolov3/paddle/run_benchmark.sh
* merge the speed and mem task of  static_graph in save.py and run_models.sh
* delete the corresponding train task in static_graph_models.sh
* update the message in each model
* update the using condition of FLAGS_allocator_strategy in transformer, mask_rcnn, deeeplab
=> Merge mode

api/deploy/docker_run.sh, api/deploy/post_log.py
当前日志保存在本地目录下，如果迁移机器的话，就需要重新部署服务，因此为了方便迁移，后端搭建了一个日志服务器，运行的日志就可以上传上去，前端访问的时候下载即可。
=> add post log

api/deploy/docker_run.sh, api/deploy/post_log.py, api/deploy/summary.py, scripts/auto_run_paddle.sh, scripts/docker_run.sh, scripts/save.py, scripts/template.py
+ 修改template 为通用模板
+ 为op-benchmark 增加例行报警
=> add email alarm for op_benchmark

api/deploy/summary.py
=> split email

api/deploy/summary.py
=> format alarm email

scripts/auto_run_paddle.sh, scripts/docker_run.sh
+ update cuda_version for dynamic_graph mode from 10.0 to 10.1
+ update python version for dynamic_graph mode from 2.7 to 3.7
=> update cuda version for dynamic

.gitmodules
* add PaddleGAN as  a submodel for benchmark
=> Add paddle gan submodel

dynamic_graph/gan_models/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* add gan_models in dygraph
*   pix2pix
*  cyclegan
=> add gan models in dygraph

competitive_products/pytorch_benchmark/pytorch_auto.sh
* add torch models (mobilenet resnet seq2seq transformer ptb)
* 调整格式
=> add_torch_dygraph modles

dynamic_graph/gan_models/pytorch/run_benchmark.sh
* add pytorch gan script in dynamic graph
=> add_torch_dygraph_gan

api/tests/configs/arg.json, api/tests/configs/cumsum.json, api/tests/configs/slice.json
增加cumsum、arg(max/min)、slice的若干个配置，已充分测试Paddle的一些op优化工作。
- cumsum：https://github.com/PaddlePaddle/Paddle/pull/25505
- arg(max/min)：https://github.com/PaddlePaddle/Paddle/pull/25941
=> Add several configs of cumsum, arg(max/min), slice.

api/common/paddle_api_benchmark.py
反向测试时，Paddle会构建一个由`xxx -> shape -> fill_constant -> xxx_grad`组成的Program。比如abs反向测试，master实现构建的main_program和startup_program分别为：
- main_program
```
{ // block 0
persist var x : fluid.VarType.LOD_TENSOR.shape(16, 128, 257, 257).astype(VarType.FP32)
var abs_0.tmp_0 : fluid.VarType.LOD_TENSOR.shape(16, 128, 257, 257).astype(VarType.FP32)
var abs_0.tmp_0@GRAD : fluid.VarType.LOD_TENSOR.shape(16, 128, 257, 257).astype(VarType.FP32)
var x@GRAD : fluid.VarType.LOD_TENSOR.shape(16, 128, 257, 257).astype(VarType.FP32)
var abs_0.tmp_0_shape : fluid.VarType.LOD_TENSOR.shape(4,).astype(VarType.BOOL)
{Out=['abs_0.tmp_0']} = abs(inputs={X=['x']}, op_device = , op_namescope = /, op_role = 0, op_role_var = [], use_cudnn = False, use_mkldnn = False)
{Out=['abs_0.tmp_0_shape']} = …
```
=> Remove shape and fill_constant when benchmarking backward.

dynamic_graph/resnet/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark.sh
* add ResNet50_bs128 in static graph
* add ResNet50_bs32 in dynamic graph
=> add resnet50_128 and resnet50_32

api/deploy/docker_run.sh
* update python version to 3.7
* update tf version to 2.3
=> update python and tf version

dynamic_graph/seg_models/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* add dunamic deeplabv3  single card mode (8cards’  speed is not meeting expectations)
=> add dunamic deeplabv3  single card mode

scripts/auto_run_paddle.sh, scripts/docker_run.sh
* 更新静态图运行环境，升级到CUDA 10.7 python3.7 （暂时先不要合入！！！）
=> Update st images

dynamic_graph/seg_models/paddle/run_benchmark.sh, scripts/static_graph_models.sh
=> bug_fix_seg

api/deploy/docker_run.sh, scripts/docker_run.sh, scripts/save.py, scripts/template.py, static_graph/Detection/paddle/run_benchmark.sh
* add job name and test time in the title of alarm email 
* adjust alarm email content 
the modified email looks like:
pic1:
pic2:
=> adjust email title and content

scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark.sh
* add dali in static resnet50 8mp
* fix dynamic seg models 
new feature and bug_fix
=> add_dali_resnet50 and bug fix

scripts/save.py
=> fix display of fail jobs

scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
* disable profiler in static graph models, because of  [paddleci-307](http://newicafe.baidu.com/v5/issue/paddleci-307/show) and  [DLTP-11074](http://newicafe.baidu.com/v5/issue/paddleci-307/show)
* update models for fixing [DLTP-10905](http://newicafe.baidu.com/v5/issue/DLTP-10905/show)
**from** a00c8af 
**to** a33f081
Bug fixes
=> disable_profiler_st

api/tests_v2/__init__.py, api/tests_v2/common_import.py, api/tests_v2/launch.py, api/tests_v2/main.py, api/tests_v2/run.sh
=> add tests_v2

api/tests_v2/argsort.py, api/tests_v2/configs/argsort.json
=> add argsort 2.0 tests

api/tests_v2/concat.py, api/tests_v2/configs/concat.json
=> add concat 2.0 tests

api/tests_v2/accuracy.py, api/tests_v2/configs/accuracy.json
=> add accuracy 2.0 tests

dynamic_graph/slowfast/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
=> add slowfast script

api/deploy/docker_run.sh, scripts/docker_run.sh, scripts/save.py, scripts/template.py
* add website link
* fix bug in email display
the effect looks like:
=> add website link

dynamic_graph/tsn/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* update for pretrain models in tsn, because of the modification of pretrained models in tsn model code
* add slowfast models in dynamic graph
new fetures
=> update pretrain model and add run slowfast

api/tests_v2/common_import.py, api/tests_v2/configs/linear.json, api/tests_v2/linear.py
=> add linear 2.0 tests

api/tests_v2/avg_pool2d.py, api/tests_v2/configs/avg_pool2d.json, api/tests_v2/run.sh
=> add avg_pool2d 2.0 tests

api/tests_v2/cast.py, api/tests_v2/configs/cast.json
=> add cast api 2.0 tests

scripts/binary_search_pr.py
=> add binary search pr tool

api/common/paddle_api_benchmark.py, api/common/tensorflow_api_benchmark.py, api/tests_v2/arg.py, api/tests_v2/configs/arg.json
=> add arg series 2.0 tests

api/tests_v2/configs/log_softmax.json, api/tests_v2/log_softmax.py
=> add log_softmax 2.0 test

api/tests_v2/log_softmax.py
=> refine log_softmax

dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* add dynamic masc_rcnn
new features
=> add_maskrcnn_dy

api/tests_v2/configs/masked_select.json, api/tests_v2/masked_select.py
add masked_select script for api benchmark
=> add masked_select script for api benchmark

api/tests_v2/configs/inverse.json, api/tests_v2/inverse.py
=> Add the benchmark script of inverse.

api/tests_v2/configs/gather.json, api/tests_v2/gather.py
add add gather api for benchmark
=> add gather api for benchmark test=develop

api/tests_v2/configs/linspace.json, api/tests_v2/linspace.py
new script: add performace script for linspace
=> add performace script for linspace

Inference/c++/ernie/CMakeLists.txt, Inference/c++/ernie/README.md
related https://github.com/PaddlePaddle/Paddle/issues/27453
=> use new paddle_inference name

dynamic_graph/tsm/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
=> add_tsm_dy

api/tests_v2/configs/pad3d.json, api/tests_v2/pad3d.py
=> add pad3d benchmark

api/tests_v2/configs/reshape.json, api/tests_v2/reshape.py
=> Add reshape 2.0 tests

dynamic_graph/yolov3/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* update the data ln
* delete path in run_benchmark
=> fix yolov3 dunamic bug

api/tests_v2/configs/matmul.json, api/tests_v2/matmul.py
=> add matmul 2.0 test

api/tests_v2/configs/expand_as.json, api/tests_v2/configs/tile.json, api/tests_v2/expand.py, api/tests_v2/expand_as.py, api/tests_v2/tile.py
add benchmark scripts for expand, expand_as and tile ops
=> add benchmark scripts for expand, expand_as and tile ops

api/tests_v2/masked_select.py
=> fix the masked_select script

.gitmodules
models和PaddleGAN几个模型更新了计时方式，因为更新一下submodule。
=> Update the commit of models and PaddleGAN

api/deploy/docker_run.sh, scripts/docker_run.sh, scripts/template.py
=> adjust website link

api/common/special_op_list.py, api/tests_v2/configs/remainder.json, api/tests_v2/remainder.py
=> add remainder test for API2.0

api/tests_v2/configs/pixel_shuffle.json, api/tests_v2/pixel_shuffle.py
- This PR add pixel shuffle op benchmark
=> add pixel shuffle benchmark config

api/common/utils.py, api/tests_v2/configs/gather.json, api/tests_v2/gather.py
Add gather OP script for benchmark
=> Add gather OP script for benchmark

api/common/special_op_list.py, api/tests_v2/configs/cumsum.json, api/tests_v2/configs/diag.json, api/tests_v2/cumsum.py, api/tests_v2/diag.py
Add cumsum, diag test for API2.0
=> Add cumsum, diag test for API2.0

api/tests/common_import.py
=> Enable static graph

api/tests_v2/configs/flip.json, api/tests_v2/flip.py
=> add flip test

api/tests_v2/configs/flatten.json, api/tests_v2/configs/roll.json, api/tests_v2/configs/trace.json, api/tests_v2/flatten.py, api/tests_v2/roll.py, api/tests_v2/trace.py
add roll, trace, flatten tests
=> Add roll, trace, flatten tests

static_graph/Detection/paddle/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/yolov3/paddle/run_benchmark.sh
=> fix scripts of detection st

ci/scripts/run_test.sh
=> Add installing tensorflow-probability in run_test.sh:prepare_env

api/tests_v2/configs/max_pool2d.json, api/tests_v2/max_pool2d.py
=> Add max_pool op tests

api/tests_v2/configs/p_norm.json, api/tests_v2/p_norm.py
=> Add benchmark for p_norm.

dynamic_graph/seg_models/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* bug_0928_fix seg  
RD 将模型配置化，故而需要修改脚本
=> bug_0928_fix seg

api/tests_v2/configs/grid_sample.json, api/tests_v2/grid_sample.py
=> add grid sample

api/tests_v2/configs/conv_transpose3d.json, api/tests_v2/configs/depthwise_conv2d_transpose.json, api/tests_v2/conv_transpose3d.py, api/tests_v2/depthwise_conv2d_transpose.py
depwise_conv2d_transpose tf 无对应api
=> add conv3d_transpose and depwise_conv2d_transpose

api/tests_v2/configs/data_norm.json, api/tests_v2/data_norm.py
=> Add data norm

api/deploy/main_control.sh
=> Fix run script 

api/deploy/docker_run.sh
update docker_run scripts, 适配pr：https://github.com/PaddlePaddle/benchmark/pull/629
=> update docker_run scripts

scripts/save.py
* add outlier flag
* update standard value automatically
=> add outlier

ci/scripts/run_test.sh
pip install时，由于代理封禁某些网段，导致超时问题发生，pip安装时屏蔽代理使用
=> fix pip install timeout via proxy

scripts/save.py
=> Fix code style of save.py

api/tests/compare.py, api/tests/logical.py
=> fix compare, logical tests

dynamic_graph/senta/paddle/run_benchmark.sh, dynamic_graph/wavenet/paddle/run_benchmark.sh, scripts/config.ini, scripts/dynamic_graph_models.sh
* 添加SL 方向wavenet 以及Senta
* NOTE： SL 模型托管在gitlab，在任务启动时会先行拉代码，实际训练时只做cp 处理
=> add SL models, notest

api/deploy/api_info_v2.txt, api/tests_v2/add_n.py, api/tests_v2/configs/add_n.json
replace elementwise_sum to add_n
=> replace elementwise_sum to add_n

dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* fix the web mission
from 
to
=> fix_web_mission_dy, notest

dynamic_graph/wavenet/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
=> Fix wavenet

dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/yolov3/paddle/run_benchmark.sh, scripts/static_graph_models.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/yolov3/paddle/run_benchmark.sh
* update scripts of detection（st&dy）
* update scripts of dy-gan
=> update scripts, test=document_fix

dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/senta/paddle/run_benchmark.sh, static_graph/Detection/paddle/run_benchmark.sh
* fix bug
* update the cp-rules from mylog, test
=> bug_fix, test=document_fix

api/deploy/docker_run.sh, api/deploy/main_control.sh, ci/scripts/run_daily.sh
- 优化并行逻辑，任务调度更为细粒度；
- 添加WORKER_NODE_*字段处理多机执行；
- 添加效率云例行任务启动脚本；
=> Optimize task parallel and add daily run script for xly

api/tests/run.sh
Minor modification of the run.sh.
=> Minor modification of the run.sh.

dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/senta/paddle/run_benchmark.sh, scripts/auto_run_paddle.sh
=> fix_add_data, test=document_fix

api/common/special_op_list.py, api/tests_v2/configs/mv.json, api/tests_v2/mv.py
=> add benchmark for mv op

static_graph/BERT/paddle/run_benchmark.sh, static_graph/Transformer/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark.sh, static_graph/seq2seq/paddle/run_benchmark.sh
* update scripts  for "[update the analysis rule](http://agroup.baidu.com/paddle-perf/view/office/3420402)"
=> update_to_adapt_new, test=document_fix

api/deploy/api_info_v2.txt
cos_sim接口和脚本名称发生变化，更新记录文件。
cos_sim->cosine_similarity
=> update api information 2.0

dynamic_graph/gan_models/paddle/run_benchmark.sh
* Update paddlegan 1026 
*  from 359db9c to 942bb211e6c97af7d691646a8037790b3851a6eb
*  for fix [DLTP-14083](http://newicafe.baidu.com/v5/issue/DLTP-14083/show)
=> Update paddlegan 1026

api/deploy/summary.py, api/deploy/write_json.py, ci/scripts/check_approval.sh
- 添加`version`参数来区分1.8、2.0版本并保存到数据库；
- 添加`construct_email`来控制邮件数据生成，等例行任务稳定且数据置信后再打开；
=> Add version argument into summary.py

api/tests/run.sh, api/tests_v2/run.sh, ci/scripts/run_test.sh
添加CI中CPU测试，同时在summary中展示失败api测试运行类型信息。
=> Add cpu test to CI

api/common/special_op_list.py, api/tests_v2/configs/yolo_box.json, api/tests_v2/yolo_box.py
添加yolo_box 的benchmark脚本， yolo_box无反向
=> add benchmark for yolo box

api/tests_v2/configs/temporal_shift.json
add config of temporal_shift json file
=> add config for temporal_shift

api/tests/run.sh, api/tests_v2/run.sh, ci/scripts/run_test.sh
设置`export CUDA_VISIBLE_DEVICES=""`跑CPU任务，其余情况按GPU任务处理。
=> Runing cpu test ONLY when CUDA_VISIBLE_DEVICES=''

comparision_system/pytorch_benchmark/pytorch_auto.sh, dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/senta/pytorch/run_benchmark.sh, dynamic_graph/wavenet/pytorch/run_benchmark.sh, dynamic_graph/yolov3/pytorch/run_benchmark.sh
=> Fix scripts

api/common/special_op_list.py, api/tests_v2/configs/empty.json, api/tests_v2/empty.py
=> add benchmark for empty op

scripts/run_model.sh
=> Add model commit

api/deploy/write_json.py
修改导出json文件格式满足benchmark平台展示使用。
=> Modify json format to show

dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/senta/paddle/run_benchmark.sh
* update PaddleSeg for fix [DLTP-14239](http://newicafe.baidu.com/v5/issue/DLTP-14239/show)
FROM 829d9da TO 9ca3ebd5f27b56847c0633f96cd46c786982a457
* add started_port for senta and mask_rcnn
=> update_PaddleSeg_1029, test=document_fix

scripts/static_graph_models.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark.sh
=> add resnet50 amp, test=document_fix

api/deploy/summary.py
=> Fix check result missing version

dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/mobilenet/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark.sh, dynamic_graph/seg_models/paddle/run_benchmark.sh, scripts/run_model.sh
=> add_start_port, test=document_fix

comparision_system/README.md, comparision_system/mxnet_benchmark/mxnet_auto.sh, static_graph/image_classification/resnet50_fp/mxnet/run_benchmark.sh
=> Add amp resnet50 mxnet

comparision_system/mxnet_benchmark/mxnet_auto.sh, scripts/static_graph_models.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark.sh
* update the bs of ResNet50 amp
=> Update fp16 bsupdate fp16 bs

dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/mobilenet/paddle/run_benchmark.sh, dynamic_graph/ptb/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark.sh, dynamic_graph/seg_models/paddle/run_benchmark.sh, dynamic_graph/senta/paddle/run_benchmark.sh, dynamic_graph/seq2seq/paddle/run_benchmark.sh, dynamic_graph/slowfast/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, dynamic_graph/tsm/paddle/run_benchmark.sh, dynamic_graph/tsn/paddle/run_benchmark.sh, dynamic_graph/wavenet/paddle/run_benchmark.sh, dynamic_graph/yolov3/paddle/run_benchmark.sh, static_graph/BERT/paddle/run_benchmark.sh, static_graph/CycleGAN/paddle/run_benchmark.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/GAN_models/PaddleGAN/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh, static_graph/STGAN/paddle/run_benchmark.sh, static_graph/StarGAN/paddle/run_benchmark.sh, static_graph/Transformer/paddle/run_benchmark.sh, static_graph/deeplabv3+/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark.sh, static_graph/seq2seq/paddle/run_benchmark.sh, static_graph/yolov3/paddle/run_benchmark.sh
=> add running status check

dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/yolov3/paddle/run_benchmark.sh
* update detection case in dygraph, for the updating of config in modesl
=> update detection case, test=document_fix

.gitmodules
* update models **from** 0a4c9c8 **to** 7a951e87c74b7a97ed9ca5cc553834f4c1ff5160  
for fixing the speed of resnet50 with 8cards in dygraph, [#4940](https://github.com/PaddlePaddle/models/pull/4940)
* add PaddleClas submodel  0cc48a2359296315e12c8037c8258d758766304c
=> 1111_update_models_add_paddleclas, test=document_fix

dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/dynamic_graph_models.sh
=> Add resnet152 1112

scripts/dynamic_graph_models.sh
=> add_resnet152_1112, test=document_fix

ci/scripts/run_test.sh
=> Compile paddle whl before run ci test

scripts/static_graph_models.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark.sh
* resnet50 混合精度 bs=128 时 8卡多进程 显存不足挂掉，故而disable bs=208 下的八卡多进程
* 添加 resent50 混合精度 bs=128 的任务监控，包含单卡单、八卡单以及八卡多
=> 1113_update_resnet50fp16_bs, test=document_fix

ci/scripts/run_test.sh
修复判断本地存在安装包，if语句中PADDLE_WHL误写成PADDLE_URL错误。
=> Fix PADDLE_WHL condition error

dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/mobilenet/paddle/run_benchmark.sh, dynamic_graph/ptb/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark.sh, dynamic_graph/seg_models/paddle/run_benchmark.sh, dynamic_graph/senta/paddle/run_benchmark.sh, dynamic_graph/seq2seq/paddle/run_benchmark.sh, dynamic_graph/slowfast/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, dynamic_graph/tsm/paddle/run_benchmark.sh, dynamic_graph/tsn/paddle/run_benchmark.sh, dynamic_graph/wavenet/paddle/run_benchmark.sh, dynamic_graph/yolov3/paddle/run_benchmark.sh, static_graph/BERT/paddle/run_benchmark.sh, static_graph/CycleGAN/paddle/run_benchmark.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/GAN_models/PaddleGAN/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh, static_graph/STGAN/paddle/run_benchmark.sh, static_graph/StarGAN/paddle/run_benchmark.sh, static_graph/Transformer/paddle/run_benchmark.sh, static_graph/deeplabv3+/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark.sh, static_graph/seq2seq/paddle/run_benchmark.sh, static_graph/yolov3/paddle/run_benchmark.sh
=> add timeout settings

scripts/auto_run_paddle.sh, scripts/run_model.sh
* 每个模型开始前，kill 掉上个模型挂掉残留的非预期Python进程（不退出，显存不释放）（挂掉会有返回码报出挂掉的状态），以免影响下一个模型的正常训练
=> add kill python, test=document_fix

api/deploy/main_control.sh
添加`framework`参数，指定框架运行测试，该参数主要用途在Paddle主repo的性能测试流水线中使用。
=> Add framework argument for running special framework

scripts/save.py
* If speed is 0, setting speed and memory result as outlier.
=> setting outlier when speed is 0

api/tests/configs/gather.json
add gather OP script for overwrite=False
=> add config for gather Op

dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/yolov3/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
* 动态图检测库近期重构不断引入问题，故暂时将模型reset 到之前版本
=> update_detec_dy, test=document_fix

scripts/auto_run_paddle.sh
* update models from 7a951e8  to bdacb35542323f72beccde40572a33dd705bd6bb
* fixed nvidia-docker on 21, remvoe the LB export temporarily
=> update_models_1120, test=document_fix

api/deploy/write_excel.py, api/tests_v2/configs/conv2d.json, api/tests_v2/configs/conv2d_transpose.json, api/tests_v2/configs/depthwise_conv2d.json, api/tests_v2/conv2d.py, api/tests_v2/conv2d_transpose.py, api/tests_v2/depthwise_conv2d.py
更新conv2d、conv2d_transpose、depthwise_conv2d的api调用脚本和json配置
=> polish conv2d api 2.0

api/tests/configs/gather.json
=> fix the gather shape for only overwrite diff for config 0 and 2

scripts/analysis.py, scripts/run_model.sh
拆分自https://github.com/PaddlePaddle/benchmark/pull/704 ，主要包含以下功能：
- `analysis.py`脚本
- 允许不指定数据的`position`，默认提取`keyword`后面的第一个数据
- 允许不知道`separator`，默认值为None
- 添加`model_mode`模式-1，表示提取的数据就是ips，此时需要设置ips_unit
- `run_model.sh`脚本
- 添加模型脚本中对是否设置`separator`、`position`、`range`、`model_mode`、`ips_unit`的检查，若没设置，则不传入`analysis.py`脚本
=> Simplify the analysis script and add the support of mode=-1 which means directly distil the ips data from log. 

dynamic_graph/gan_models/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark.sh
- 修改动态图GAN模型，对应https://github.com/PaddlePaddle/PaddleGAN/pull/47 ，修改后解析log如下：
- 以下数据是10月23日所测，标明能够正确提取数据。因这段时间动态图GAN模型有优化，因此当前的benchmark性能比以下log中的要好一些。
- CycleGAN
```
Extract 30 records: separator=None; position=None
average ips of 30 steps, skip 0 step:
Avg: 3.634 images/sec
FPS: 3.634 images/sec
average ips of 30 steps, skip 5 steps:
Avg: 3.754 images/sec
Min: 3.575 images/sec
Max: 3.900 images/sec
FPS: 3.754 images/sec
{"log_file": "/work/models/PaddleGAN/dynamic_CycleGAN_1_1_sp", "model_name": "CycleGAN", "mission_name": "\u56fe\u50cf\u751f\u6210", "direction_id": 0, "run_mode": "sp", "index": 1, "gpu_num": 1, "FINAL_RESULT": 3.754, "log_with_profiler": "/work/models/PaddleGAN/dynamic_CycleGAN_3_1_sp", "profiler_path": "/work/models/PaddleGAN/profiler_dynamic_CycleGAN", "UNIT": …
```
=> Abstract ips from log directly for dynamic GAN models.

dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/dynamic_graph_models.sh
* switch dy_resnet50 to PaddleClas
*  models
*  resnet50_bs32--> 309.676 samples/s   and 2048.765 samples/s
*  resnet50_bs128--> 344.035 samples/s and 2498.073 samples/s
*  PaddleClas
*  resnet50_bs32--> 309.552 samples/s and 2300.360 samples/s
*  resnet50_bs128-->343.033samples/s and  2539.746 samples/s
=> swicth_clas, test=document_fix

scripts/save.py
* build icafe card automatically
=> build icafe

dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/mobilenet/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark.sh, dynamic_graph/seg_models/paddle/run_benchmark.sh, dynamic_graph/senta/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, dynamic_graph/tsm/paddle/run_benchmark.sh
* removed started_port in dist params
=> update_dist_args, test=document_fix

scripts/save.py
=> fix outlier

dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/save.py
* setting as benchmark value only when it is not outlier.
* setting timeout for reset in PaddleClass.
=> change benchmark setting

scripts/save.py
=> fix judge of fail job

scripts/static_graph_models.sh
* remove the enable_static PR in static_graph_models.sh
=> update_scripts, test=document_fix

dynamic_graph/mobilenet/paddle/run_benchmark_mobilenet.sh, scripts/dynamic_graph_models.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark.sh
* update fp_16 case
* 将mobilenet 由models 切换到 paddleclas 
测试结果
```bash
average latency of 101 steps, skip 11 steps:
Avg: 0.123 s/step
Min: 0.121 s/step
Max: 0.136 s/step
FPS: 1039.660 samples/s
{"log_file": "./1201_log/dynamic_MobileNetV1_1_1_sp
```
```bash
average latency of 13 steps, skip 11 steps:
Avg: 0.153 s/step
Min: 0.122 s/step
Max: 0.184 s/step
FPS: 6675.576 samples/s
{"log_file": "./1201_log/dynamic_MobileNetV1_1_8_mp
```
```bash
average latency of 101 steps, skip 11 steps:
Avg: 0.159 s/step
Min: 0.156 s/step
Max: 0.171 s/step
FPS: 806.649 samples/s
{"log_file": "./1201_log/dynamic_MobileNetV2_1_1_sp
```
```bash
average latency of 13 steps, skip 11 steps:
Avg: 0.317 s/step
Min: 0.225 s/step
Max: 0.408 s/step
FPS: 3230.692 samples/s
{"log_file": …
```
=> 1201_update, test=document_fix

ci/scripts/op_benchmark.config
添加Paddle repo中`elementwise_add`的映射到benchmark repo测试脚本`add`。
=> add elementwise_add map to add

scripts/save.py
=> Completing icafe content

scripts/save.py
* sort model list
* fix bug in build icafe
=> Sort model list

api/common/main.py
=> fix accuracy error

scripts/static_graph_models.sh
* enable_profiler in seq2seq bert cyclegan yolov3
=> enable_profiler, test=document_fix

api/dynamic_tests_v2/layer_norm.py, api/tests_v2/configs/layer_norm.json
add layer_norm (paddle vs torch) scripts
=> add layer_norm (paddle vs torch) scripts

api/common/api_param.py, api/common/main.py, api/common/paddle_api_benchmark.py, api/common/paddle_dynamic_api_benchmark.py, api/common/pytorch_api_benchmark.py, api/common/tensorflow_api_benchmark.py, api/dynamic_tests_v2/arg.py, api/dynamic_tests_v2/batch_norm.py, api/dynamic_tests_v2/concat.py, api/dynamic_tests_v2/conv2d.py, api/dynamic_tests_v2/cumsum.py
- 新增batch_norm测试脚本，但功能支持还不完整
- 更新所以已有的测试脚本，适配测试框架的改动
=> Add batch_norm and update all code of dynamic tests

api/deploy/main_control.sh, api/deploy/op_benchmark_unit.py, api/deploy/summary.py, api/deploy/write_excel.py
增加pytorch对齐框架的全量测试和数据处理
- bash main_control.sh ../dynamic_tests_v2 ../tests_v2/configs dynamic_test 2 gpu both dynamic_api.txt both dynamic
- python summary.py dynamic_test/ --compare_framwork=pytorch --dump_to_excel True --dump_to_mysql False
=> add pytorch data handle

dynamic_graph/seg_models/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
=> Add transformer big

api/deploy/summary.py
=> fix bug of summary data

api/deploy/main_control.sh
=> fix bug of main control

scripts/static_graph_models.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark_amp.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark_pure.sh
* update resnet50_fp16 to   resnet50_amp_fp16
* add resnet50 pure fp16
* paddle: e74e1a226ca9b20275d77aa1af069d29cfee2af0
* models:33d65b3150621fdfa4500b9ebac4a8dfcc7e2229
* test results:
* bs128
```bash
average latency of 80 steps, skip 8 steps:
Avg: 0.095 s/step
Min: 0.095 s/step
Max: 0.096 s/step
FPS: 1343.691 samples/s
```
* bs208
```bash
average latency of 80 steps, skip 8 steps:
Avg: 0.146 s/step
Min: 0.145 s/step
Max: 0.148 s/step
FPS: 1422.511 samples/s
```
=> add_resnet50_pure16, test=document_fix

dynamic_graph/lac/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* add lac in dy models(only single card)
* paddle: e74e1a226ca9b20275d77aa1af069d29cfee2af0
* models: 33d65b3150621fdfa4500b9ebac4a8dfcc7e2229
* test results:
```bash
average latency of 40 steps, skip 12 steps:
Avg: 0.234 s/step
Min: 0.228 s/step
Max: 0.242 s/step
FPS: 136.524 samples/s
```
=> add_lac_dy, test=document_fix

scripts/config.ini, scripts/dynamic_graph_models.sh
=> update, enable lac,test=document_fix

scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
* update the Deeplabv3+ dir in static graph, beacuse of the variation in PaddleSeg
* add the check of lsb_release before pip install paddlenlp
=> update_deep_st, test=document_fix

scripts/auto_run_paddle.sh, scripts/docker_run.sh
* update pip version to address  the installation problem of  paddlenlp
* add a compile option  ``` DCUDA_ARCH_NAME=Auto```
=> update_pip_version and  add a compile option , test=document_fix

scripts/docker_run.sh
* update_compile_option ,  
CUDA_ARCH_NAME=Volta
=> update_compile_option, test=document_fix

api/tests_v2/elementwise.py
disable divide fp16
已建divide fp16卡片：http://console.cloud.baidu-int.com/devops/icafe/issue/paddle-perf-628/show
=> disable divide fp16

scripts/auto_run_paddle.sh, scripts/docker_run.sh
=> update, test=document_fix

scripts/dynamic_graph_models.sh
* update dataset to adapt paddlenlp
=> update dataset ,test=document_fix

scripts/dynamic_graph_models.sh
* remove lsb-core, which caused
=> 1224_remove, test=document_fix

scripts/docker_run.sh
=> update_image, test=document_fix

scripts/auto_run_paddle.sh
* add ssl temporarily, to address[ DLTP-19135](http://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-19135/show)
=> add_ssl, test=document_fix

scripts/auto_run_paddle.sh
=> fix libssl

scripts/auto_run_paddle.sh
=> install_opencv, test=document_fix

api/tests_v2/configs/softmax.json
=> add softmax test

scripts/docker_run.sh, static_graph/BERT/paddle/run_benchmark.sh
=> update_time_bert, test=document_fix

scripts/analysis.py, scripts/save.py, scripts/static_graph_models.sh
=> fix judge of fail jobs

api/tests_v2/configs/index_select.json, api/tests_v2/index_select.py
New features
OPs
add index_select
=> test=develop, add index_select

scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
=> update_branch_Clas, test=document_fix

api/tests_v2/bert_base/embedding.json
=> Add json config of embedding in bert_base.

api/deploy/op_benchmark_unit.py, api/deploy/write_excel.py
由于反向测试拿到的时间包括（forward+backward），因此在生成excel的时候，生成（backward-forward）选项卡，作为纯backward时间的参考。
=> Generate a sheet to show the time of (backward - forward).

dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/docker_run.sh, scripts/dynamic_graph_models.sh, static_graph/yolov3/paddle/run_benchmark.sh
* 优化resnet 以及yolo脚本
* 增大docker shm-size
=> fix_and_optimize, test=document_fix

.gitmodules
* update the default_branch of PaddleClas
=> update_class_default_branch, test=document_fix

.gitmodules, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/yolov3/paddle/run_benchmark.sh
* 修改PaddleClas repo 的submodel 分支为默认dygraph-dev，当前静态&动态均在该分支
* Class 此次  commit ID：1cc558
=> update_class_branch_0111, test=document_fix

ci/scripts/op_benchmark.config
添加`tril_triu.cu`文件在benchmark中测试脚本的映射关系
=> add tril_triu.cu -> tril/triu mapping config

scripts/docker_run.sh
=> update_dir, test=document_fix

scripts/auto_run_paddle.sh
=> update_opencv, test=document_fix

api/deploy/write_benchmark.py, ci/scripts/run_daily.sh
=> Save daily task result by requested benchmark API

scripts/auto_run_paddle.sh
=> update_path, test=document_fix

static_graph/image_classification/paddle/run_benchmark_resnet.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh
=> update_resnet_st_single, test=document_fix

ci/scripts/op_benchmark.config
=> fix topk mapping config error

scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh
=> Set the optimization option for ResNet50 and change the batch_size from 96 to 128

api/common/api_param.py, api/common/launch.py, api/common/main.py, api/common/system.py, api/common/utils.py, api/deploy/summary.py, api/dynamic_tests_v2/elementwise.py, api/dynamic_tests_v2/pow.py, api/tests_v2/configs/elementwise.json
- 精度检查时，增加相对误差的计算，但当前还是按照绝对误差来判断
- fp16尾数位只有10位，精度在2e-10级别，对应十进制差不多是0.0009。因此fp16计算的算子，自动将atol设置成0.001。
- 动态图elementwise测试中新增几个测试的op
=> Enhance the check of accuracy

api/tests_v2/configs/gather_nd.json, api/tests_v2/configs/scatter.json, api/tests_v2/configs/scatter_nd_add.json, api/tests_v2/gather_nd.py, api/tests_v2/scatter.py, api/tests_v2/scatter_nd_add.py
add scatter / scatter_nd_add / gather_nd benchmark
=> add scatter / scatter_nd_add / gather_nd benchmark

api/tests_v2/configs/logsumexp.json, api/tests_v2/logsumexp.py
=> add logsumexp API test script with tf

api/common/special_op_list.py, api/deploy/api_info_v2.txt, api/deploy/collect_api_info.py, api/run_op_benchmark.sh, api/tests_v2/add_n.py, api/tests_v2/configs/elementwise.json, static_graph/image_classification/paddle/run_benchmark_resnet.sh
Reverts PaddlePaddle/benchmark#846
=> Revert "Allow specifing the desired operators when generate the api_info list."

api/tests_v2/configs/index_sample.json
Adding  settings in index-sample.json for bug check.
=> Adding more settings for accuracy tests of index_sample OP. 

api/common/special_op_list.py, api/dynamic_tests_v2/arange.py, api/tests_v2/arange.py, api/tests_v2/configs/arange.json
=> Add test script of arange.

scripts/run_model.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh
* update renset fp16 scripts for fixing [DLTP-20055](https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-20055/show)
=> Update fp16 scripts

static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh
=> bug_fix_0127, test=document_fix

api/deploy/main_control.sh
=> fix log file name error

scripts/static_graph_models.sh, static_graph/Transformer/paddle/run_benchmark.sh
=> update_st_transformer, test=document_fix

ci/scripts/op_benchmark.config
补充`pool`、`grid_sampler`对应测试脚本映射关系。
=> add mapping config of PR-CI-OP-benchmark

scripts/config.ini
=> add_cpu_dimension,test=document_fix

scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
* 更新模型脚本到套件
* models---> PaddleNLP
=> update_PaddleNLP_models, test=document_fix

.gitmodules
* add PaddleNLP sumodel
* develop ,commit :8c6d4fd7b926577a23a91dc977281758760c3c22
=> add_sub_PaddleNLP, test=document_fix

dynamic_graph/lac/paddle/run_benchmark.sh, dynamic_graph/mobilenet/paddle/run_benchmark_mobilenet.sh, scripts/auto_run_paddle.sh, scripts/dynamic_graph_models.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh
* 修复lac 模型在套件下的参数配置问题
* 修复分类 amp 模型case
* 修改mobielnet 数据集和其他分类模型保持一致，便于benchmark ci 数据集拷贝
=> update_scripts_models, test=document_fix

api/tests_v2/assign.py
=> fix assign

ci/scripts/op_benchmark.config
添加`pool` OP对应测试API脚本映射关系。
失败CI日志：https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/2444063/job/3431236
=> add Paddle repo config mapping

ci/scripts/op_benchmark.config
op type是range，python api是paddle.arange，测试脚本是arange.py
=> Add map from op type to testing filename for range.

api/tests_v2/configs/softmax.json
修改softmax的一个配置，原配置中有很多-1，改成ernie模型中的一个具体的配置。
=> Change one config of softmax.

ci/scripts/op_benchmark.config
添加`interpolate_v2_op.cu`对应benchmark下测试脚本的映射关系。
=> add Paddle repo op nenchmark ci config mapping

.gitmodules
* update PaddleNLP from 5b35fb9 **to** f4d4eac4b7abd52e2b5b4ee41bc5b442fcd3bc06
* update PaddleClas to develop branch, commit=6619b5584c7c5d171816a3f9c92e65822239f499
* update PaddleDetection from a187703 **to** 84e79e8760ba2ef7fbc3972d865316af9aade014
=> Update submodels 0302

scripts/static_graph_models.sh, static_graph/BERT/paddle/run_benchmark.sh
* 切换bert模型到套件 PaddleNLP
* 测试用paddle commit：91635de3904a0f34e9b8c6aa06cc4e69bf36a41a
* 模型commit：5b35fb9fb9e3c7b45d731dd84bd35d3a0825dcae
* 单卡测试数据(训练速度(单位：sequences/sec)以及显存)如下：
* 其中参数上
base fp16 bs=64
base fp32 bs=32
large fp16 bs=4
large fp32 bs=2
* 数据集上
large: max_seq_length=512
base:max_seq_length=128
=> update_bert_st, test=document_fix

dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
* 更新 mask_rcnn+fpn 到新模型 
* 速度测试如下：
* 测试代码
Model commit is 84e79e8760ba2ef7fbc3972d865316af9aade014
Paddle commit is '91635de3904a0f34e9b8c6aa06cc4e69bf36a41a'
=> Update mask rcnn

dynamic_graph/mobilenet/paddle/run_benchmark_mobilenet.sh, scripts/benchmark_ci/analysis.py, scripts/benchmark_ci/model_ci.sh, scripts/benchmark_ci/run_models.sh
=> fix model benchmark ci

.gitmodules
* update PaddleDetection branch to develop, be4269fbaace8f2dad5a23e60a1451e82b12b946
=> update_detection_branch, test=document_fix

scripts/benchmark_ci/run_models.sh
* remove mobilenetv1 because the large fluctuations in xiaolvyun machines.
=> remove mobilenetv1

dynamic_graph/tsm/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* update TSM scripts 
* 合入前确保PaddleVedio 已添加 [PR-934](https://github.com/PaddlePaddle/benchmark/pull/934)
* 本次测试
Model commit is 2583ebc1a1b9aa5130b261ed0061401a68dabab7
Paddle commit is 5f6213217be6e83f02a6b3cf0e3f18177c4eede7
* 测试数据：instance/s
单卡=40.594 
八卡=285.049 instance/s
* 同时模型存在bug  [DLTP-22440](https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-22440/show) 已修复
* 八卡和原models 下数据差异较大，已和RD 确认属于正常结果
=> update_TSM, test=document_fix

.gitmodules
* update TSM models，add PaddleVideo repo,  commit=2583ebc1a1b9aa5130b261ed0061401a68dabab7
=> add_video_repo, test=document_fix

scripts/dynamic_graph_models.sh
=> add requirement, test=document_fix

api/common/api_param.py, api/common/pytorch_api_benchmark.py, api/common/utils.py, api/dynamic_tests_v2/binary_cross_entropy.py, api/dynamic_tests_v2/binary_cross_entropy_with_logits.py, api/dynamic_tests_v2/softmax_with_cross_entropy.py, api/tests_v2/configs/binary_cross_entropy.json, api/tests_v2/configs/binary_cross_entropy_with_logits.json, api/tests_v2/configs/softmax.json
- 新增binary_cross_entropy的动态图测试脚本，底层使用的是bce_loss op
- 新增binary_cross_entropy_with_logits的动态图测试脚本
=> Add binary_cross_entropy and binary_cross_entropy_with_logits, change the configs of softmax.

ci/scripts/run_test.sh
=> update torch version to 1.8.0

scripts/dynamic_graph_models.sh
=> fix_install_wavenet install, test=document_fix

scripts/dynamic_graph_models.sh
=> update_branch, test=document_fix

dynamic_graph/mask_rcnn/paddle/run_benchmark.sh, dynamic_graph/seg_models/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, dynamic_graph/tsm/paddle/run_benchmark.sh, dynamic_graph/yolov3/paddle/run_benchmark.sh, static_graph/Transformer/paddle/run_benchmark.sh, static_graph/seg_models/paddle/run_benchmark.sh
* 更新模型名字，添加bs
* 动态图
* seg: 2
* TSM：16
* mask_rcnn: 1
* yolov3: 8
* transformer: 4096
* 
* 静态图
* seg: 2 
* transformer: 4096
*
=> update_modle_name add bs, test=document_fix

dynamic_graph/transformer/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/Transformer/paddle/run_benchmark.sh
* transformer 动静加amp 监控
* 动态图 支持fp32 amp_fp16
* 静态图支持 fp32 amp_fp16 以及pure_fp16
=> add_amp_transformer, test=document_fix

api/tests_v2/configs/depthwise_conv2d.json
add config for depthwise_conv2d
=> add config for depthwise_conv2d

scripts/auto_run_paddle.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
=> update_detection_scripts, test=document_fix

scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
=> add_req_clas, test=document_fix

dynamic_graph/bert/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
=> Add bert dy

Inference/c++/ernie/cmake/FindFluid.cmake, Inference/c++/ernie/mkldnn/README.md
Fix paddle lib name and add cryptopp lib support. I verified locally it works now.
@pmajchrzak @jczaja  Please review.
=> Update ernie mkldnn application CMakeLists.txt

ci/scripts/run_daily.sh
=> fix compilation

dynamic_graph/lac/paddle/run_benchmark.sh, scripts/static_graph_models.sh, static_graph/Transformer/paddle/run_benchmark.sh
* add transformer big bs2560 and bs5120
=> Test transformer big bs

scripts/benchmark_ci/model_ci.sh
* Add manual link for model benchmark ci
=> Add manual link for model benchmark ci

scripts/static_graph_models.sh
* Fix data path of transformer
=> Fix data path of transformer

scripts/dynamic_graph_models.sh
* fix data path for dy_transformer
=> Fix data path for dy_transformer

dynamic_graph/bert/paddle/run_benchmark.sh, dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/lac/paddle/run_benchmark.sh, dynamic_graph/ptb/paddle/run_benchmark.sh, dynamic_graph/seq2seq/paddle/run_benchmark.sh, dynamic_graph/slowfast/paddle/run_benchmark.sh, dynamic_graph/tsn/paddle/run_benchmark.sh, dynamic_graph/wavenet/paddle/run_benchmark.sh, static_graph/BERT/paddle/run_benchmark.sh, static_graph/CycleGAN/paddle/run_benchmark.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/GAN_models/PaddleGAN/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/STGAN/paddle/run_benchmark.sh, static_graph/StarGAN/paddle/run_benchmark.sh, static_graph/seq2seq/paddle/run_benchmark.sh
=> update_scripts_0428, test=document_fix

dynamic_graph/wavenet/paddle/run_benchmark.sh, scripts/static_graph_models.sh, static_graph/Detection/paddle/run_benchmark.sh, static_graph/Mask-RCNN/paddle/run_benchmark.sh, static_graph/NextVlad/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh, static_graph/yolov3/paddle/run_benchmark.sh
=> 0429_update_scripts, test=document_fix

dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/lac/paddle/run_benchmark.sh, dynamic_graph/mobilenet/paddle/run_benchmark_mobilenet.sh, dynamic_graph/ptb/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, dynamic_graph/senta/paddle/run_benchmark.sh, dynamic_graph/seq2seq/paddle/run_benchmark.sh, dynamic_graph/slowfast/paddle/run_benchmark.sh, dynamic_graph/tsn/paddle/run_benchmark.sh, dynamic_graph/wavenet/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/CycleGAN/paddle/run_benchmark.sh, static_graph/GAN_models/PaddleGAN/run_benchmark.sh, static_graph/PaddingRNN/lstm_paddle/run_benchmark.sh, static_graph/STGAN/paddle/run_benchmark.sh, static_graph/StarGAN/paddle/run_benchmark.sh, static_graph/seq2seq/paddle/run_benchmark.sh
=> 0430_update_scripts, test=document_fix

scripts/docker_run.sh
=> update compile, test=document_fix

scripts/dynamic_graph_models.sh
* pip install Cython because the change of  Detection requirements
* update Seg models from bcf10a6 to 5a38454adc39711293a5c0bf898bf9c99d2ba244
=> Update seg models 0508

scripts/benchmark_ci/run_models.sh
=> update nlp directory for ci

static_graph/Transformer/paddle/run_benchmark.sh
* fix static transformer multiprocess, added --distribute
=> fix static transformer multiprocess, test=document_fix

dynamic_graph/slowfast/paddle/run_benchmark.sh, dynamic_graph/tsn/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
update tsn and slowfast model benchmark task to PaddleVideo Repo.
=> migrate_tsn_and_slowfast_benchmark, test=document_fix

dynamic_graph/tsm/paddle/run_benchmark.sh, scripts/benchmark_ci/run_models.sh, scripts/static_graph_models.sh, static_graph/BERT/paddle/run_benchmark.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh
* update TSM yaml
* add resnet50 settings
* add bert bs settings
=> add models settings, test=document_fix

dynamic_to_static/mobilenet/paddle/run_benchmark_mobilenet.sh, dynamic_to_static/resnet/paddle/run_benchmark_resnet.sh, dynamic_to_static/yolov3/paddle/run_benchmark.sh, scripts/auto_run_paddle.sh, scripts/dynamic_to_static_models.sh, scripts/save.py
support dynamic to static models run in benchmark.
=> support dynamic_to_static models run, test=document_fix

scripts/dynamic_graph_models.sh, scripts/dynamic_to_static_models.sh, scripts/static_graph_models.sh
update model result file startwith function name, in order to setup relation between result file and function name.
=> update model result file startwith function name, test=document_fix

api/common/feeder.py, api/common/paddle_api_benchmark.py, api/common/tensorflow_api_benchmark.py, api/common/utils.py, api/deploy/write_excel.py, api/deploy/write_json.py, api/dynamic_tests_v2/logical.py, api/dynamic_tests_v2/maths.py, api/tests_v2/activation.py, api/tests_v2/configs/activation.json, api/tests_v2/configs/compare.json, api/tests_v2/configs/elementwise.json, api/tests_v2/configs/logical.json, api/tests_v2/configs/softmax.json, api/tests_v2/configs/softmax_with_cross_entropy.json
=> Adjust the repeat for some configs.

scripts/auto_run_paddle.sh, scripts/docker_run.sh, scripts/run_model.sh, scripts/save.py, scripts/static_graph_models.sh, scripts/template.py
* 新增镜像tag 参数，适配不同cuda版本的paddle 镜像命名
* 修改编译选项，周一到周五auto，适配A100 和V100
* 邮件报警标题新增架构名和cuda 版本
* 细化编包产物cuda 具体版本命名
=> [dont merge] pr_for_adapt_A100, test=document_fix

scripts/git_repo_operate.py, scripts/models.json, scripts/parse_output_get_metrics.py, scripts/pr_run_paddle.sh, scripts/query_latest_daily_benchmark_result.py
=> support pr run, test=document_fix

scripts/parse_output_get_metrics.py
=> support pr run fix static graph report bug, test=document_fix

dynamic_graph/ptb/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* update ptb from models to PaddleNLP. ptb_medium
* speed: 1522.975 words/s
=> update_ptb_models, test=document_fix

dynamic_graph/bert/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
=> add ber-large bs64, test=document_fix

dynamic_to_static/mobilenet/paddle/run_benchmark_mobilenet.sh, dynamic_to_static/resnet/paddle/run_benchmark_resnet.sh, dynamic_to_static/yolov3/paddle/run_benchmark.sh, scripts/dynamic_to_static_models.sh
=> fix_dynamic_to_static_models_bug, test=document_fix

.gitmodules, dynamic_graph/ppocr_mobile_2/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/models.json
=> add dynamic module PPOCR_mobile_2.0, test=document_fix

dynamic_graph/bert/paddle/run_benchmark.sh, scripts/benchmark_ci/run_models.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/BERT/paddle/run_benchmark.sh
* fix bert large, remove the bs settings in run_benchmark.sh
* add seqlen param in bert scripts
* others
=> fix bert, test=document_fix

.gitmodules, dynamic_graph/gan_models/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* update gan branch from master to develop
* disable test in models train
=> Update gan branch 0615

scripts/dynamic_graph_models.sh
=> fix gan dependency, test=document_fix

scripts/dynamic_graph_models.sh
=> add reqire, test=document_fix

api/tests_v2/configs/compare.json, api/tests_v2/configs/elementwise.json
Adding one more settings for elementwise op test.
=> Adding settings for elementwise

scripts/pr_run_paddle.sh, scripts/query_latest_daily_benchmark_result.py
迁移支持指定PR运行的运行机器，支持解析base_dir变量
=> support base_dir variable, test=document_fix

dynamic_graph/faster_rcnn_fpn/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
新增Benchmark模型：动态图Faster R-CNN + FPN
https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-28618/show?source=drawer-header
=> add faster_rcnn_fpn, test=document_fix

scripts/dynamic_graph_models.sh
=> fix faster_rcnn_fpn bug, test=document_fix

.gitmodules, dynamic_graph/mobilenet/paddle/run_benchmark_mobilenet.sh, dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh
PaddleClas Repo 版本升级
from a8f21e0167e4de101cbcd241b575fb09bbcaced9
to 98db91b2118deb0f6f1c0bf90708c1bc34687f8d
=> upgrade clas repo, test=document_fix

.gitmodules, dynamic_graph/mobilenet/paddle/run_benchmark_mobilenet.sh, dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/benchmark_ci/model_ci.sh, scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh
This reverts commit 3bcc1df7b00f3d0efd09385478bacbdfa05fef4e.
=> Revert "upgrade clas repo, test=document_fix (#1034)"

.gitmodules, dynamic_graph/mobilenet/paddle/run_benchmark_mobilenet.sh, dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/benchmark_ci/run_models.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh
=> Update clas and ci

dynamic_graph/mobilenet/paddle/run_benchmark_mobilenet.sh, dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/benchmark_ci/model_ci.sh, scripts/benchmark_ci/run_models.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh
This reverts commit 7a751c613ac244ee37c29cfb499e660cc7325b2e.
=> Revert "Update clas and ci (#1039)"

.gitmodules, dynamic_graph/mobilenet/paddle/run_benchmark_mobilenet.sh, dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/benchmark_ci/run_models.sh, scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh
升级PaddleClas Repo并解决CI不支持分布式模式运行的问题。
=> Update clas and ci fixed

dynamic_to_static/bert/paddle/run_benchmark.sh, scripts/dynamic_to_static_models.sh
=> PaddleNLP增加bert动转静模型

static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh
修复PaddleClas Resnet50 fp16模型的运行异常问题。
=> upgrade paddle clas, test=document_fix

scripts/benchmark_ci/run_models.sh, scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh
回滚PaddleClas静态图模型运行的commit版本号至之前的版本，恢复PaddleClas Repo静态图性能。
=> revert_paddle_clas_static_version, test=document_fix

dynamic_to_static/bert/paddle/run_benchmark.sh, dynamic_to_static/mobilenet/paddle/run_benchmark_mobilenet.sh, dynamic_to_static/resnet/paddle/run_benchmark_resnet.sh, scripts/docker_run.sh, scripts/dynamic_to_static_models.sh, scripts/save.py
=> add dynamic to static for paddle clas, test=document_fix

api/common/api_param.py, api/run_op_benchmark.sh
=> Change the dtype from float16 to float32.

scripts/dynamic_to_static_models.sh
修改PaddleClas的动态图转静态图的commit id为最新ID。
=> dynamic_to_static_add_clas, test=document_fix

scripts/dynamic_graph_models.sh, scripts/query_latest_daily_benchmark_result.py
1、video下全量模型A100上运行报错：定位到是 dy_wavenet 模型强制安装了pandas=1.1.5导致；现去掉 --ignore-installed
=>  change_dy_wavenet, test=document_fix

scripts/docker_run.sh
This reverts commit f177e92ee13e8b39df1dd2553aeee6cb4e999ef2.
=> Revert "delete --privileged,test=document_fix (#1052)"

scripts/benchmark_ci/analysis_dev.py, scripts/benchmark_ci/model_ci.sh, scripts/benchmark_ci/run_models.sh
* remove compile of develop branch
=> remove compile of develop branch

api/common/api_param.py, api/run_op_benchmark.sh
Reverts PaddlePaddle/benchmark#1047
=> Revert "Change the dtype from float16 to float32."

dynamic_graph/seg_models/paddle/run_benchmark.sh, dynamic_graph/yolov3/paddle/run_benchmark.sh, scripts/docker_run.sh, scripts/dynamic_graph_models.sh, static_graph/BERT/paddle/run_benchmark.sh
对齐单机、分布式参数配置，更新 静态图 bert base、动态图 HRnet 、DeepLabv3 、YOLOv3 参数配置
=> change bs for gpu8 0806

dynamic_graph/yolov3/paddle/run_benchmark.sh, scripts/docker_run.sh
对齐单机、分布式参数配置，分布式近期未监控YOLOv3，性能指标无法对齐，故暂不更新该模型单机参数配置
=> Fix bs for gpu8 0811

scripts/auto_run_paddle.sh, scripts/docker_run.sh, scripts/save.py
【单机benchmark】
1、邮件环境配置中添加hostname
2、新增device_type=v100-16g,v100-32g
3、编译的whl包名字中添加commitID信息
=> 【单机benchmark】Add hostname 0811

scripts/benchmark_ci/analysis.py, scripts/benchmark_ci/model_ci.sh
* add errorcode for models_benchmark_ci
=> add errorcode for models_benchmark_ci

scripts/benchmark_ci/analysis.py, scripts/benchmark_ci/model_ci.sh
fix errorcode for model_benchmark_ci
=> fix errorcode for model_benchmark_ci

api/tests_v2/activation.py, api/tests_v2/configs/activation.json, api/tests_v2/configs/compare.json
Adding  test script for lgamma in 『activation.py』 file.
=> Add test script for lgamma

scripts/docker_run.sh
docker run  参数 privileged-》cap-add=ALL
=> Fix privileged 0827

scripts/benchmark_ci/model_ci.sh, scripts/benchmark_ci/run_models.sh
fix the error in model_benchmark_ci
=> fix bert to avoid error in model_benchmark_ci,test=document_fix

scripts/benchmark_ci/model_ci.sh, scripts/benchmark_ci/run_models.sh
* remove transformer in model_benchmark_ci
=> remove transformer in model_benchmark_ci

dynamic_graph/ppocr_mobile_2/paddle/run_benchmark.sh
* modify ppocr model name in benchmark
=> modify ppocr model name in benchmark

dynamic_graph/gan_models/paddle/run_benchmark.sh, dynamic_graph/ppocr_mobile_2/paddle/run_benchmark.sh, dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, dynamic_graph/seg_models/paddle/run_benchmark.sh, dynamic_graph/seq2seq/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, dynamic_graph/tsm/paddle/run_benchmark.sh, scripts/benchmark_ci/run_models.sh
add process killing after model running
=> Add process killing after model running

scripts/analysis.py
=> fix bug in analysis script

scripts/benchmark_ci/model_ci.sh
* Add more models for model_benchmark_ci
=> Add more models for model_benchmark_ci

scripts/benchmark_ci/run_models.sh
* fix cyclegan for model_benchmark_ci
=> fix cyclegan for model_benchmark_ci

scripts/benchmark_ci/model_ci.sh
* model adjust for model benchmark ci
=> model adjust for model benchmark ci

scripts/benchmark_ci/analysis.py, scripts/benchmark_ci/model_ci.sh
fix errorcode in model_benchmark_ci
=> fix errorcode in model_benchmark_ci

scripts/benchmark_ci/analysis.py
=> fix measuring of loss

scripts/benchmark_ci/analysis.py, scripts/benchmark_ci/model_ci.sh
=> fix bug in model_benchmark_ci

scripts/benchmark_ci/model_ci.sh
remove Cyclegan for model_benchmark_ci
=> remove Cyclegan for model_benchmark_ci

scripts/benchmark_ci/run_models.sh
update numpy version for model_benchmark_ci
=> update numpy version for model_benchmark_ci

OtherFrame/seg/PyTorch/scripts/analysis_log.py
consider bs in calculating ips.
=> [bug fix] consider bs in calculating ips

.gitmodules, OtherFrame/nlp/PyTorch/run_PyTorch_xlnet.sh, OtherFrame/nlp/PyTorch/scripts/xlnet/run_benchmark.sh
=> modify XLNet submodule branch

OtherFrame/nlp/PyTorch/scripts/xlnet/analysis_log.py, OtherFrame/nlp/PyTorch/scripts/xlnet/run_benchmark.sh
=> modify xlnet logging steps

api/dynamic_tests_v2/conv1d.py, api/tests_v2/configs/conv1d.json
=> add conv1d op

api/dynamic_tests_v2/bmm.py, api/tests_v2/configs/bmm.json
=> add bmm op test

.gitmodules
=> revert_models, test=document_fix

OtherFrame/nlp/PyTorch/scripts/xlnet/analysis_log.py, OtherFrame/nlp/PyTorch/scripts/xlnet/run_benchmark.sh
=> Update XLNet benchmark script

.gitmodules
=> de_models_1122, test=document_fix

scripts/dynamic_graph_models.sh
=> add_ocr_models, test=document_fix

scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
=> fix_bugs_1123, test=document_fix

scripts/dynamic_graph_models.sh
=> add_dy_clas, test=document_fix

dynamic_graph/tsn/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh
* fix clas branch
* fix tsn yaml
* fix ptb dataset
* fix ocr script name
=> fix bugs, test=document_fix

scripts/auto_run_paddle.sh, scripts/dynamic_graph_models.sh, scripts/save.py, scripts/static_graph_models.sh
* add python config env
* fix log url
* add gan model
* export log_path
=> add_gan_models, test=document_fix

.gitmodules, OtherFrame/detection/PyTorch/models/README.md, OtherFrame/detection/PyTorch/scripts/analysis_log.py, OtherFrame/detection/PyTorch/scripts/run_benchmark.sh
- Add training benchmark for Detection models
=> add detection benchmark

api/dynamic_tests_v2/group_norm.py
=> fix  group_norm op cannot be executed on the GPU

OtherFrame/clas/PyTorch/README.md, OtherFrame/clas/PyTorch/run_Pytorch.sh, OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/PrepareData.sh, OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/scripts/Twins_scripts/PrepareData.sh, OtherFrame/clas/PyTorch/scripts/Twins_scripts/PrepareEnv.sh, OtherFrame/clas/PyTorch/scripts/Twins_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/scripts/mmclassification_scripts/PrepareData.sh, OtherFrame/clas/PyTorch/scripts/mmclassification_scripts/PrepareEnv.sh, OtherFrame/clas/PyTorch/scripts/mmclassification_scripts/run_benchmark.sh
* update torch scripts of clas
=> test_clas_other_frame, test=document_fix

api/tests_v2/model_configs/bmm.json, api/tests_v2/model_configs/elementwise_div.json, api/tests_v2/model_configs/elementwise_mul.json, api/tests_v2/model_configs/index_select.json
添加bmm、index_select、elementwise_mul、elementwise_div 配置repeat times
=> change repeat times for bmm, index_select, elementwise_mul and elementwise_div 

scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
* update nlp  from de616d0 to 4d0642190898ac74dfdc94477de5d1db2ea7ffc3
=> update_nlp, test=document_fix

OtherFrame/clas/PyTorch/README.md, OtherFrame/clas/PyTorch/run_Pytorch.sh, OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/PrepareData.sh, OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/PrepareEnv.sh, OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/analysis_log.py, OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/scripts/Twins_scripts/PrepareData.sh, OtherFrame/clas/PyTorch/scripts/Twins_scripts/PrepareEnv.sh, OtherFrame/clas/PyTorch/scripts/Twins_scripts/analysis_log.py, OtherFrame/clas/PyTorch/scripts/Twins_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/scripts/mmclassification_scripts/PrepareData.sh, OtherFrame/clas/PyTorch/scripts/mmclassification_scripts/PrepareEnv.sh, OtherFrame/clas/PyTorch/scripts/mmclassification_scripts/analysis_log.py, OtherFrame/clas/PyTorch/scripts/mmclassification_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/test_clas.sh, OtherFrame/scripts/auto_run.sh, OtherFrame/scripts/run_model.sh
* 更新torch clas 脚本
* 将训练入口统一放在run_Pytorch.sh,  由该入口调test_clas.sh(各个模型的run 脚本)
* 处理env 和dataset 准备阶段对网速的依赖问题
* 统一json 文件内model命名，保持和paddle 一致，避免无法插入数据库或者前端显示问题
* 添加otherframe 的统一训练入口
=> 【暂不合入】update pytorch clas scripts, test=document_fix

OtherFrame/Speech/PyTorch/wenet/analysis.py, OtherFrame/Speech/PyTorch/wenet/run_analysis_mp.sh, OtherFrame/Speech/PyTorch/wenet/run_analysis_sp.sh
=> revise the analysis.py

api/deploy/op_benchmark_unit.py, api/dynamic_tests_v2/common_import.py, api/run_op_benchmark.sh
=> Fix bug of computing gflops and gbs.

api/tests_v2/model_configs/gelu.json
=> add gelu repeat times

OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/scripts/Twins_scripts/analysis_log.py
* fix other frame scripts of clas
=> otherframe fix_scripts, test=document_fix

OtherFrame/seg/PyTorch/run_PyTorch.sh, OtherFrame/seg/PyTorch/scripts/analysis_log.py, OtherFrame/seg/PyTorch/scripts/run_benchmark.sh
=> fix scripts, test=document_fix

scripts/static_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh
* 静态图模型clas 切换到dev上
* model:098a934f5051b2914101a8c4c714fc0466150dfe
* [分类模型fp32 八卡速度偏高  fp16单卡八卡速度偏低（fp16 的八卡速度降到2位数； fp32 八卡翻了3倍，单卡也有8%左右不等下降）](https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-41487/show?cid=5) 
* 1221-mark
基于[PR1590](https://github.com/PaddlePaddle/PaddleClas/pull/1590/files) 测试结果如下：
=> adapt_dev_clas, test=document_fix

scripts/benchmark_ci/run_models.sh
* fix model_benchmark_ci,test=document_fix
=> fix model_benchmark_ci,test=document_fix

scripts/benchmark_ci/run_models.sh
=> fix model_benchmark_ci

OtherFrame/detection/PyTorch/PrepareEnv_mot.sh, OtherFrame/detection/PyTorch/README_mot.md, OtherFrame/detection/PyTorch/scripts/analysis_log.py, OtherFrame/detection/PyTorch/scripts/analysis_log_mot.py
fix jde fairmot in torch 1.10.1
=> fix detection mot torch

OtherFrame/Speech/PyTorch/PWGAN/PrepareEnv.sh, OtherFrame/Speech/PyTorch/PWGAN/run_PyTorch.sh, OtherFrame/Speech/PyTorch/PWGAN/scripts/Parakeet/PWGAN/analysis_log.py, OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/scripts/Twins_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/scripts/mmclassification_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/test_clas.sh, OtherFrame/scripts/auto_run.sh, OtherFrame/seg/PyTorch/run_PyTorch.sh
* update seg scripts 
* update speech scripts
* update
=> update_other_scripts, test=document_fix

api/common/launch.py, api/run_op_benchmark.sh
Reverts PaddlePaddle/benchmark#1214
https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/4393944/job/10415233 应用了这个PR之后，出现了奇怪的错误，先revert。
=> Revert "Correct the setting of profiler to nvprof to get precise gpu_time."

api/common/launch.py, api/run_op_benchmark.sh
=> Correct the setting of profiler to nvprof to get precise gpu_time.

api/deploy/op_benchmark_unit.py, api/deploy/write_excel.py
=> Fix the bug when writing times information to excel in summary.

OtherFrame/detection/PyTorch/PrepareEnv.sh, OtherFrame/detection/PyTorch/run_PyTorch.sh, OtherFrame/detection/PyTorch/scripts/analysis_log.py, OtherFrame/detection/PyTorch/scripts/analysis_log_mot.py, OtherFrame/detection/PyTorch/scripts/run_benchmark.sh, OtherFrame/detection/PyTorch/scripts/run_benchmark_mot.sh, OtherFrame/scripts/auto_run.sh
=> Test detection models 1228

ci/scripts/check_approval.sh, frame_benchmark/models_path.yaml
=> add models_path.yaml

scripts/benchmark_ci/model_ci.sh, scripts/benchmark_ci/run_models.sh
* adjust model in model_benchmark_ci
=> adjust model in model_benchmark_ci

scripts/benchmark_ci/run_models.sh
display worklog in  model_benchmark_ci
=> display worklog in  model_benchmark_ci

scripts/benchmark_ci/model_ci.sh
add stack log in model_benchmark_ci
=> add stack log in model_benchmark_ci

scripts/dynamic_graph_models.sh
Fix conformer 1231
fix video scikit-image
=> Fix conformer 1231

scripts/dynamic_graph_models.sh
=> update_version, test=document_fix

scripts/docker_run.sh, scripts/git_repo_operate.py, scripts/pr_run_paddle.sh
add pr run scripts,test=document_fix
=> add pr run scripts,test=document_fix

dynamic_graph/seg_models/paddle/run_benchmark.sh, dynamic_graph/transformer/paddle/run_benchmark.sh, dynamic_to_static/seg_models/reademe.txt, dynamic_to_static/transformer/reademe.txt, scripts/dynamic_to_static_models.sh
* add_d2s_models, transformer_base, hrnet, deeplabv3,
* seg Model commit is 82249202100d32ead987c167b54b30e8f2fb70b7
nlp Model commit is  50f71b3f73b8872f857808c9d33b41447cbaf4b9
Paddle commit is 327e5050eb8bdf2548979c39e2a6637beaecadac
* result on single card
* bugs to fix
[DLTP-42017](https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-42017/show)
[DLTP-42021](https://console.cloud.baidu-int.com/devops/icafe/issue/DLTP-42021/show)
* 2022-01-06
* seg Model commit is 186dce26ae4b2a04691ef63b92d979f185059522
nlp Model commit is  3d3bc82c85da3df001d44d36a4caf0291a7d877f
Paddle commit is 36a102f85de37c4d6ade394eb3f552a1dc1a30b7
*
=> 【暂不合入】add_d2s_models, transformer_base, hrnet, deeplabv3,  test=document_fix

scripts/pr_run_paddle.sh
* update pr run submodule init
=> update_pr_scripts, test=document_fix

api/tests_v2/model_configs/depthwise_conv2d.json
=> add depthwise config

OtherFrame/ocr/PyTorch/DB_scripts/pre_ENV.sh, OtherFrame/ocr/PyTorch/DB_scripts/readme.md, OtherFrame/ocr/PyTorch/DB_scripts/run_benchmark.sh, OtherFrame/ocr/PyTorch/PrepareEnv.sh, OtherFrame/ocr/PyTorch/run_PyTorch.sh, OtherFrame/ocr/PyTorch/run_PyTorch_DB.sh, OtherFrame/ocr/PyTorch/scripts/PSENet/run_benchmark.sh, OtherFrame/scripts/auto_run.sh
=> add pse scripts, test=document_fix

OtherFrame/Speech/PyTorch/PWGAN/run_PyTorch.sh, OtherFrame/clas/PyTorch/run_Pytorch.sh, OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/analysis_log.py, OtherFrame/clas/PyTorch/scripts/HRNet-Image-Classification_scripts/run_benchmark.sh, OtherFrame/clas/PyTorch/scripts/mmclassification_scripts/run_benchmark.sh, OtherFrame/detection/PyTorch/run_PyTorch.sh, OtherFrame/detection/PyTorch/run_PyTorch_mot.sh, OtherFrame/gan/PyTorch/fomm/run_PyTorch.sh, OtherFrame/gan/PyTorch/mmedting/run_PyTorch.sh, OtherFrame/gan/PyTorch/styleganv2/run_PyTorch.sh, OtherFrame/nlp/PyTorch/run_PyTorch_gpt.sh, OtherFrame/nlp/PyTorch/run_PyTorch_xlnet.sh, OtherFrame/ocr/PyTorch/DB_scripts/run_benchmark.sh, OtherFrame/ocr/PyTorch/run_PyTorch.sh, OtherFrame/ocr/PyTorch/run_PyTorch_DB.sh, OtherFrame/seg/PyTorch/run_PyTorch.sh, OtherFrame/video/PyTorch/run_PyTorch.sh
=> fix, test=document_fix

api/deploy/write_excel.py
=> Fix bug of writing summary results to excel.

scripts/dynamic_graph_models.sh, scripts/dynamic_to_static_models.sh, scripts/static_graph_models.sh
* drop models
*http://agroup.baidu.com/paddle-perf/view/office/4649769
=> drop_models_0120, test=document_fix

scripts/dynamic_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh
=> fix_models, test=document_fix

scripts/dynamic_graph_models.sh, static_graph/image_classification/paddle/run_benchmark_resnet.sh
* update nlp from 719485c to 078758e1920e2244ed2be40b83a807f051d7360e
* update seg from 186dce2 to  e9c89d5
* update detection from  956726e to ec9bc76
* update video from c046235 to e19be74
* update gan from  fd47ab3 to 940dc26
* update Speech from f8204c9 to b983427
* update ocr from e49e733 to  5876f3f
=> Update submodels 0124

dynamic_graph/seg_models/paddle/run_benchmark.sh, scripts/dynamic_graph_models.sh, scripts/dynamic_to_static_models.sh
=> add seg fp16, test=document_fix

dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, dynamic_to_static/resnet/paddle/run_benchmark_resnet.sh, scripts/dynamic_graph_models.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh
* update clas repo from 0aa85d4 to b5cf03e73eee345bcfc232eb9d050b0c9d8e430a
* update clas scripts 
* 使用参数 AMP.level 替换 AMP.use_pure_fp16，对应关系如下：
* mixed fp16 <-> AMP.use_pure_fp16: False <-> AMP.level: O1
* pure fp16 <-> AMP.use_pure_fp16: True <-> AMP.level: O2
* 配置文件的更新如下：
* R50 mixed fp16 训练：ppcls/configs/ImageNet/ResNet/ResNet50_amp_O1.yaml
* R50 pure fp16 训练：ppcls/configs/ImageNet/ResNet/ResNet50_amp_O2.yaml
* SE_ResNeXt101_32x4d pure fp16 训练：ppcls/configs/ImageNet/SENet/SE_ResNeXt101_32x4d_amp_O2.yaml
* amp 训练的配置文件不再区分动/静态图，以上配置文件均支持动/静态图训练
=> update_clas_scripts_models, test=document_fix

frame_benchmark/docker_images.yaml
Update gan model in pytorch's benchmark
=> add gan benchmark

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/N1C8/TimeSformer_bs14_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/run_benchmark.sh
1. add PaddleVideo's model-TimeSformer's pytorch benchmark
=> add TimeSformer benchmark 

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/N1C1/conformer_bs16_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/N1C1/conformer_bs30_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/N1C8/conformer_bs16_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/N1C8/conformer_bs30_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/benchmark_common/replace/download_and_untar.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/benchmark_common/replace/executor.py, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/benchmark_common/replace/run.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/benchmark_common/run_benchmark.sh
=> [Speech]Benchmark, add conformer

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/N1C1/fastscnn_bs2_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/N1C8/fastscnn_bs2_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/N4C32/fastscnn_bs2_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/benchmark_common/run_benchmark.sh
add pytorch  seg_fastscnn  scripts
=> seg_fastscnn_Dev_0128

api/tests/activation.py, api/tests/affine_grid.py, api/tests/arange.py, api/tests/arg.py, api/tests/argsort.py, api/tests/elementwise.py, api/tests/maths.py, api/tests/matmul.py, api/tests/reduce.py
迁移若干个统一的op测试脚本。
CI执行情况如下，总体不存在本PR引入的问题：
```
2022-02-07 17:52:42 [ci/scripts/run_test.sh:105] [FATAL] Failed API tests: tests/affine_grid(Run on GPU) tests/affine_grid(Run on CPU) tests/argsort(Run on GPU) tests/elementwise(Run on GPU) tests/elementwise(Run on CPU) tests/maths(Run on GPU) tests/maths(Run on CPU) tests/reduce(Run on GPU)
2022-02-07 17:52:42 [ci/scripts/run_test.sh:132] [FATAL] ============================================
2022-02-07 17:52:42 [ci/scripts/run_test.sh:133] [FATAL] Summary problems:
2022-02-07 17:52:42 [ci/scripts/run_test.sh:139] [FATAL] There is 1 error: API test error.
2022-02-07 17:52:42 [ci/scripts/run_test.sh:141] [FATAL] ============================================
2022-02-07 17:52:42 [ci/scripts/run_test.sh:149] [FATAL] === API test error - Please fix …
```
=> Add several unified tests.

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/N1C1/TSM_bs30_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/N1C8/TSM_bs30_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/benchmark_common/run_benchmark.sh
add tsm benchmark bs30_fp32 N1C8
=> add tsm benchmark bs30_fp32

api/tests/flatten.py, api/tests/flip.py, api/tests/floor.py, api/tests/floor_divide.py, api/tests/full.py, api/tests/gather.py, api/tests/gather_nd.py, api/tests/gelu.py, api/tests/grid_sample.py, api/tests/group_norm.py, api/tests/histogram.py, api/tests/index_sample.py, api/tests/index_select.py, api/tests/instance_norm.py, api/tests/inverse.py, api/tests/isfinite_nan_inf.py
第3批动、静态图统一测试脚本。
CI执行情况：
```
2022-02-08 21:03:05 [ci/scripts/run_test.sh:105] [FATAL] Failed API tests: tests/gelu(Run on GPU) tests/gelu(Run on CPU) tests/inverse(Run on GPU) tests/inverse(Run on CPU)
2022-02-08 21:03:05 [ci/scripts/run_test.sh:132] [FATAL] ============================================
2022-02-08 21:03:05 [ci/scripts/run_test.sh:133] [FATAL] Summary problems:
2022-02-08 21:03:05 [ci/scripts/run_test.sh:139] [FATAL] There is 1 error: API test error.
2022-02-08 21:03:05 [ci/scripts/run_test.sh:141] [FATAL] ============================================
2022-02-08 21:03:05 [ci/scripts/run_test.sh:149] [FATAL] === API test error - Please fix the failed API tests accroding to fatal log:
2022-02-08 21:03:05 [ci/scripts/run_test.sh:150] [FATAL] tests/gelu(Run on GPU) tests/gelu(Run …
```
=> Add 3rd part of unified tests.

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fairmot/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/faster_rcnn/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/gfl/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/higherhrnet/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/hrnet/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/jde/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/solov2/benchmark_common/PrepareEnv.sh
=> add dete install matplotlib

scripts/benchmark_ci/run_models.sh
change iters for model benchmark ci
=> change iters for model benchmark ci,test=document_fix

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/N1C1/pwgan_bs26_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/N1C1/pwgan_bs6_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/N1C8/pwgan_bs26_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/N1C8/pwgan_bs6_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/benchmark_common/README.MD, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/benchmark_common/test_pwgan.sh
=> [Speech]add pwg benchmark

frame_benchmark/models_path.yaml
fix models_path.yaml for pwgan
=> [Speech]fix models_path.yaml for pwgan

frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p/N1C1/deeplabv3p_bs4_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p/N1C8/deeplabv3p_bs4_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p/N4C32/deeplabv3p_bs4_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/hrnet_seg/N1C1/hrnet_seg_bs8_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/hrnet_seg/N1C8/hrnet_seg_bs8_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/hrnet_seg/N4C32/hrnet_seg_bs8_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/hrnet_seg/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/hrnet_seg/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/hrnet_seg/benchmark_common/run_benchmark.sh
Add seg models: DeepLabV3p, HRNet
=> Add seg models: DeepLabV3p, HRNet

api/common/registry.py, api/tests/avg_pool2d.py, api/tests/layer_norm.py, api/tests/linspace.py, api/tests/log_softmax.py, api/tests/logical.py, api/tests/logical_not.py, api/tests/logsumexp.py, api/tests/masked_select.py, api/tests/max_pool2d.py, api/tests/mv.py, api/tests/nll_loss.py, api/tests/normalize.py, api/tests/one_hot.py, api/tests/ones_like.py, api/tests/p_norm.py, api/tests/pad2d.py, api/tests/pad3d.py, api/tests/pixel_shuffle.py, api/tests/pow.py
迁移第4批统一测试脚本。
CI执行情况，无本PR引入的脚本问题：
```
2022-02-15 17:22:42 [ci/scripts/run_test.sh:132] [FATAL] ============================================
2022-02-15 17:22:42 [ci/scripts/run_test.sh:133] [FATAL] Summary problems:
2022-02-15 17:22:42 [ci/scripts/run_test.sh:139] [FATAL] There is 1 error: API test error.
2022-02-15 17:22:42 [ci/scripts/run_test.sh:141] [FATAL] ============================================
2022-02-15 17:22:42 [ci/scripts/run_test.sh:149] [FATAL] === API test error - Please fix the failed API tests accroding to fatal log:
2022-02-15 17:22:42 [ci/scripts/run_test.sh:150] [FATAL] tests/layer_norm(Run on GPU) tests/layer_norm(Run on CPU) tests/nll_loss(Run on GPU) tests/nll_loss(Run on CPU) tests/pow(Run on GPU) tests/pow(Run on CPU)
```
=> Add 4-th part of unified tests.

scripts/dynamic_graph_models.sh, scripts/static_graph_models.sh
=> add_py_config, test=document_fix

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt/N1C1/gpt_bs16_fp16_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt/N1C1/gpt_bs8_fp16_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt/N1C1/gpt_bs8_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt/N1C8/gpt_bs16_fp16_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt/N1C8/gpt_bs8_fp16_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt/N1C8/gpt_bs8_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt/benchmark_common/run_benchmark.sh
=> Add megatron GPT

api/dynamic_tests_v2/gather_nd.py, api/dynamic_tests_v2/run.sh, api/tests_v2/configs/gelu.json
=> Polish a test and run script.

frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/hrnet_seg/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/N1C1/ocrnet_hrnetw48_bs2_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/N1C1/ocrnet_hrnetw48_bs4_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/N1C8/ocrnet_hrnetw48_bs2_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/N1C8/ocrnet_hrnetw48_bs4_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/N4C32/ocrnet_hrnetw48_bs2_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/N4C32/ocrnet_hrnetw48_bs4_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer/N1C1/segformer_bs2_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer/N1C1/segformer_bs4_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer/N1C8/segformer_bs2_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer/N1C8/segformer_bs4_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer/N4C32/segformer_bs2_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer/N4C32/segformer_bs4_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer/benchmark_common/run_benchmark.sh
=> add ocrnet, segformer

scripts/benchmark_ci/model_ci.sh, scripts/benchmark_ci/run_models.sh
=> adjust threshold for yolov3,test=document_fix

api/dynamic_tests_v2/avg_pool3d.py, api/dynamic_tests_v2/max_pool3d.py, api/tests_v2/configs/avg_pool3d.json, api/tests_v2/configs/max_pool3d.json
=> Add benchmark for pool3d OP

api/deploy/main_control.sh
Change testing mode from 'stati'c to 'dynamic'
=> Fix CI-OP-Benchmark

frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/N1C8/TSM_bs30_fp32_MultiP_DP.sh
rename TSM_bs30_fp32_MultiP_DP.sh to TSM_bs30_fp32_SingleP_DP.sh
=> rename TSM SingleDP to MultiDP

ci/scripts/op_benchmark.config
Map binary_cross_entropy_with_logits=sigmoid_cross_entropy_with_logits, test=document_fix
=> Map binary_cross_entropy_with_logits=sigmoid_cross_entropy_with_logits

api/dynamic_tests_v2/gaussian_random.py, api/tests_v2/configs/gaussian_random.json
=> Add gaussian_random_op

scripts/benchmark_ci/analysis.py, scripts/benchmark_ci/run_models.sh
* adjust threshold for model benchmark ci,test=document_fix
=> adjust threshold for model benchmark ci

api/dynamic_tests_v2/bitwise.py, api/dynamic_tests_v2/bitwise_not.py, api/dynamic_tests_v2/poisson.py, api/dynamic_tests_v2/triangular_solve.py, api/tests_v2/configs/bitwise.json, api/tests_v2/configs/poisson.json, api/tests_v2/configs/triangular_solve.json
triangular_solve
---
poisson
---
bitwise and/or/xor
---
bitwise_not
---
=> add triangular_solve/poisson/bitwise_and/or/xor/not OP benchmark

api/dynamic_tests_v2/elementwise.py
=> add fmax,fmin op benchmark, test=document_fix

api/dynamic_tests_v2/graph_send_recv.py, api/tests_v2/configs/graph_send_recv.json
=> add the graph_send_recv benchmark

api/dynamic_tests_v2/poisson.py
=> fix poisson op config bug

scripts/benchmark_ci/model_ci.sh
remove yolov3 for model benchmark ci
=> remove yolov3 for model benchmark ci

api/dynamic_tests_v2/bincount.py, api/dynamic_tests_v2/cross.py, api/dynamic_tests_v2/erfinv.py, api/dynamic_tests_v2/eye.py, api/dynamic_tests_v2/lerp.py, api/dynamic_tests_v2/size.py, api/tests_v2/configs/bincount.json, api/tests_v2/configs/cross.json, api/tests_v2/configs/erfinv.json, api/tests_v2/configs/eye.json, api/tests_v2/configs/lerp.json, api/tests_v2/configs/size.json
Add bincount, cross, erfinv, eye, lerp, size
bincount:
corss:
erfinv:
eye:
lerp:
size:
=> Add bincount, cross, erfinv, eye, lerp, size

api/dynamic_tests_v2/multi_dot.py, api/tests_v2/configs/multi_dot.json
add multi_dot benchmark
测试了3个case，结果如下：
case 0
case 1
case2
=> add multi_dot benchmark, test=document_fix

api/dynamic_tests_v2/max_pool2d.py, api/dynamic_tests_v2/max_pool3d.py, api/tests_v2/configs/max_pool2d.json, api/tests_v2/configs/max_pool3d.json
Add benchmark for pool_with_index OP, test results:
=> Add benchmark for pool_with_index OP

api/dynamic_tests_v2/viterbi_decode.py, api/tests_v2/configs/viterbi_decode.json
Add benchmark for viterbi_decode op
config_0 result:
config_1 result:
=> Add benchmark for viterbi_decode op

api/dynamic_tests_v2/gaussian_random.py, api/dynamic_tests_v2/truncated_gaussian_random.py, api/tests_v2/configs/truncated_gaussian_random.json
**truncated_gaussian_random 的测试结果。**
**gaussian_random 的测试结果。**
=> Add truncated_gaussian_random_op, test=document_fix

api/dynamic_tests_v2/psroi_pool.py, api/tests_v2/configs/psroi_pool.json
Add benchmark for psroi_pool_op， test results:
=> Add benchmark for psroi_pool OP

api/dynamic_tests_v2/allclose.py, api/tests_v2/configs/allclose.json
Add allclose test script
run.sh result:
=> Add allclose test script

scripts/dynamic_graph_models.sh, scripts/run_model.sh
=> fix, test=ducument_fix

api/dynamic_tests_v2/set_value.py, api/tests_v2/configs/set_value.json
Add set_value test script。
run.sh result:
=> Add set_value benchmark script

api/dynamic_tests_v2/matrix_power.py, api/tests_v2/configs/matrix_power.json
add matrix_power test
The result is as follows:
case0
case1
case2
=> add matrix_power test

api/dynamic_tests_v2/cholesky_solve.py, api/tests_v2/configs/cholesky_solve.json
add benchmark for cholesky_solve
---
=> add benchmark for cholesky_solve

scripts/dynamic_graph_models.sh, scripts/run_model.sh
* 修复个模型依赖opencv-python 版本不一致，依赖反复卸载安装，卸载残留导致无法再次安装问题
=> fix_opencv_0310, test=document_fix

scripts/benchmark_ci/model_ci.sh, scripts/benchmark_ci/run_models.sh
* add yolov3 for model_benchmark_ci
=> add yolov3 for model_benchmark_ci

api/common/paddle_op_benchmark.py, api/deploy/main_control.sh, api/dynamic_tests_v2/abs.py, api/dynamic_tests_v2/activation.py
添加abs和activation前向gflops、gbs的计算公式。
=> Add the compute of gflops and gbs for abs and activation.

.gitmodules, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/N1C8/TimeSformer_bs1_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/run_benchmark.sh
1. 更新`run_benchmark.sh`，调整为与一般训练模式相同的8次梯度累加
2. 增加bs1多卡脚本
=> add TimeSformer bs1

api/tests_v2/configs/kldiv_loss.json, api/tests_v2/configs/nll_loss.json
fix kldiv_loss and nll_loss don't support float16
=> fix kldiv_loss and nll_loss don't support float16 

api/dynamic_tests_v2/roi_align.py, api/dynamic_tests_v2/roi_pool.py, api/tests_v2/configs/roi_align.json, api/tests_v2/configs/roi_pool.json
Add roi_align and roi_pool test script.
roi_align result:
roi_pool result:
=> Add roi_align and roi_pool benchmark script

api/dynamic_tests_v2/determinant.py, api/tests_v2/configs/determinant.json
=> Add determinant test script

api/dynamic_tests_v2/unstack.py, api/tests_v2/configs/unstack.json
Add unstack op test script
case0:
cas1:
=> Add unstack op test script

api/dynamic_tests_v2/bincount.py, api/dynamic_tests_v2/eye.py, api/dynamic_tests_v2/size.py, api/tests_v2/configs/diagonal.json
Delete backward from unsupported ops
=> Delete backward from unsupported ops

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/benchmark_common/run_benchmark.sh
Fix transformer_big train script path
=> Fix transformer_big train script path

api/dynamic_tests_v2/prelu.py, api/tests_v2/configs/prelu.json
=> Add PRelu op benchmark config

api/dynamic_tests_v2/kthvalue.py, api/tests_v2/configs/kthvalue.json
add op benchmark for kthvalue op
=> add op benchmark for kthvalue op

dynamic_graph/seg_models/paddle/run_benchmark.sh, scripts/docker_run.sh, scripts/dynamic_graph_models.sh, scripts/run_model.sh
* 暂时删除容器 --rm 参数用于debug
* 解决seg 模型精度参数问题
* 添加df -h 用于debug
=> fix_0318_bug, test=document_fix

scripts/docker_run.sh
=> uppdate, test=document_fix

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N1C1/gpt3_bs16_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N1C8/gpt3_bs16_fp32_MultiP_DP.sh
=> [GPT] Add gpt bs16 fp32 mode.

frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/N1C1/det_res18_db_bs16_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/N1C1/det_res18_db_bs8_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/N1C8/det_res18_db_bs16_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/N1C8/det_res18_db_bs8_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/benchmark_common/run_benchmark.sh
=> fix db_res18

frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/N1C1/det_res18_db_bs16_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/N1C1/det_res18_db_bs8_fp32_SingleP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/N1C8/det_res18_db_bs16_fp32_MultiP_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_res18_db/N1C8/det_res18_db_bs8_fp32_MultiP_DP.sh
=> fix db_res18, more trainning step

api/dynamic_tests_v2/warpctc.py, api/tests_v2/configs/warpctc.json
=> Add warpctc OP benchmark

api/dynamic_tests_v2/warpctc.py, api/tests_v2/configs/warpctc.json
=> Refine warpctc for benchmark

api/dynamic_tests_v2/elementwise.py
=> add mod op benchmark

scripts/benchmark_ci/run_models.sh
* update PaddleNLP repo,test=document_fix
=> update PaddleNLP repo

scripts/benchmark_ci/run_models.sh
fix bert in model benchmark ci
=> fix bert in model benchmark ci

scripts/benchmark_ci/run_models.sh
* fix bert in model benchmark ci,test=document_fix
=> fix bert in model benchmark ci,test=document_fix

api/tests_v2/resnet50_fp16/batch_norm.json, api/tests_v2/resnet50_fp16/conv2d.json
=> Add configs of resnet50_fp16.

frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p_resnet50/benchmark_common/detect_cuda.cu, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p_resnet50/benchmark_common/dist_train.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p_resnet50/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p_resnet50/benchmark_common/run_benchmark.sh
增加了PaddleSeg deeplabv3p_resnet50模型的benchmark脚本
=> PaddleSeg deeplabv3p benchmark

frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/benchmark_common/detect_cuda.cu, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/benchmark_common/dist_train.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/benchmark_common/detect_cuda.cu, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/benchmark_common/dist_train.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/benchmark_common/detect_cuda.cu, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/benchmark_common/dist_train.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/benchmark_common/run_benchmark.sh
=> New develop

dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, scripts/auto_run_paddle.sh, scripts/docker_run.sh, scripts/dynamic_graph_models.sh, scripts/dynamic_to_static_models.sh, scripts/pr_run_paddle.sh, scripts/run_model.sh, scripts/save.py, scripts/static_graph_models.sh, static_graph/image_classification/resnet50_fp/paddle/run_benchmark_fp16.sh
1、[PaddleClas @ 7284e3f](https://github.com/PaddlePaddle/PaddleClas/tree/7284e3f9dbc7ae0ea6848982bf95361bc9ce55e5)
-》[PaddleClas @ 68d7abf](https://github.com/PaddlePaddle/PaddleClas/tree/68d7abf5176ccfbf6743292a16f2f1d7a4144751)
2、[PaddleDetection @ 5161d82](https://github.com/PaddlePaddle/PaddleDetection/tree/5161d8251eaac12395db01122cd08e7a3763939c)-》[PaddleDetection @ b98f0df](https://github.com/PaddlePaddle/PaddleDetection/tree/b98f0df3d3e1d4e9c58cc0acb80535f3812231e2)
3、[PaddleGAN @ ba4d065](https://github.com/PaddlePaddle/PaddleGAN/tree/ba4d06510b5c9a0906f74736a232bee41eea828f)-》
[PaddleGAN @ 91dcc90](https://github.com/PaddlePaddle/PaddleGAN/tree/91dcc906fb8fe4a378c10de6b4c0d8525b1176a7)
4、[PaddleNLP @ baf322f](https://github.com/PaddlePaddle/PaddleNLP/tree/baf322f20afbdd0fedc457c5 …
=> 【master】更新模型库代码

api/README.md, api/deploy/op_benchmark_unit.py, api/deploy/summary.py, api/deploy/write_json.py, api/deploy/write_mysql.py, api/deploy/write_text.py
- 修改了summery.py 
- 修复了op_benchmark_unit.py 中的报错 bug fix
- 丰富了 deploy 路径下的 README 文档
- 修复了导出 text 文件时报错 bug fix
- 修复了导出 json 文件时报错 bug fix
- 重写了导出 mysql 数据库的代码
- dump to mysql
- <img width="1439" alt="image" src="https://user-images.githubusercontent.com/105368690/179517087-b9610641-ed1f-490f-9340-08faa82d17c0.png">
- dump to text
- <img width="1227" alt="image" src="https://user-images.githubusercontent.com/105368690/179517630-1758c5a8-339f-4956-9acb-5d4762fa2128.png">
- dump to json files
- ![image](https://user-images.githubusercontent.com/105368690/179518451-29fdea6c-0fe1-4929-b56d-a04281728d5b.png)
1. ~~目前 txt json mysql 没有所有op的summery汇总，只有excel有~~(done)
2. 旧的mysql代码可以考虑删除
3. 与paddleTest系统的入库格式一致未商定下来
=> bug fix for deploy/summery.py when dumping to a text file, json files and to mysql database

frame_benchmark/docker_images.yaml
modify old docker images to new docker images
=> modify old docker images to new docker images

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N4C32/mask_rcnn_r50_fpn_1x_coco_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N4C32/mask_rcnn_r50_fpn_1x_coco_bs4_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov3_darknet53_270e_coco/N4C32/yolov3_darknet53_270e_coco_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov3_darknet53_270e_coco/N4C32/yolov3_darknet53_270e_coco_bs8_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov3_darknet53_270e_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov3_darknet53_270e_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov3_darknet53_270e_coco/benchmark_common/run_benchmark.sh
Add distributed training scripts for mask_rcnn_r50_fpn_1x_coco_bs4_fp32, mask_rcnn_r50_fpn_1x_coco_bs4_fp16, yolov3_darknet53_270e_coco_bs8_fp32 and yolov3_darknet53_270e_coco_bs8_fp16. Now these benchmark can be tested on multi nodes.
=> Distributed Training scripts for PaddleDetection Benchmark

frame_benchmark/pytorch/dynamic/PaddleGAN/scripts/basicvsr/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleGAN/scripts/edvr/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleGAN/scripts/esrgan/benchmark_common/run_benchmark.sh
=> modify mmedit to mmediting

frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/benchmark_common/analysis_log.py
=> fix analysis_log.py

frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/N1C1/TimeSformer_bs14_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/N4C32/TimeSformer_bs14_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TimeSformer/benchmark_common/run_net.py
=> update PaddleVideo's scripts

frame_benchmark/docker_images.yaml, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/gfl_r50_fpn_1x_coco/N4C32/gfl_r50_fpn_1x_coco_bs8_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/gfl_r50_fpn_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/gfl_r50_fpn_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/gfl_r50_fpn_1x_coco/benchmark_common/dist_train.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/gfl_r50_fpn_1x_coco/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/jde_darknet53_30e_1088x608/N4C32/jde_darknet53_30e_1088x608_bs12_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/jde_darknet53_30e_1088x608/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/jde_darknet53_30e_1088x608/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/jde_darknet53_30e_1088x608/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/jde_darknet53_30e_1088x608/benchmark_common/train.py
=> update PaddleDetection's scripts

frame_benchmark/docker_images.yaml, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/deeplabv3p_resnet50/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/fastscnn/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/benchmark_common/prepare.sh
=> fix prepare.sh

frame_benchmark/docker_images.yaml, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N4C32/deformable_detr_r50_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/faster_rcnn_r50_fpn_1x_coco/N4C32/faster_rcnn_r50_fpn_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/faster_rcnn_r50_fpn_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/faster_rcnn_r50_fpn_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/faster_rcnn_r50_fpn_1x_coco/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_1x_coco/benchmark_common/analysis_log.py
=> Add dist train ppdet 0825

frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV2/N4C32/MobileNetV2_bs128_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV2/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV2/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/N4C32/ResNet152_bs32_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/benchmark_common/run_benchmark.sh
support N4C32 for ResNet152 and MobileNetV2
=> support N4C32

frame_benchmark/docker_images.yaml
add det_res50_db docker images
=> add det_res50_db docker images

frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml
modify DBNet.pytorch to DBNet-pytorch for pdc
=> modify DBNet.pytorch to DBNet-pytorch for pdc

frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/benchmark_common/PrepareEnv.sh
It's unstable to download resnet50 checkpoint from official repo.
=> Fix bug of network. 

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C1/transformer_big_bs2560_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C1/transformer_big_bs2560_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C1/transformer_big_bs4096_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C1/transformer_big_bs4096_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C1/transformer_big_bs5120_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C1/transformer_big_bs5120_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C8/transformer_big_bs2560_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C8/transformer_big_bs2560_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C8/transformer_big_bs4096_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C8/transformer_big_bs4096_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C8/transformer_big_bs5120_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N1C8/transformer_big_bs5120_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N4C32/transformer_big_bs2560_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N4C32/transformer_big_bs2560_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N4C32/transformer_big_bs4096_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N4C32/transformer_big_bs4096_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N4C32/transformer_big_bs5120_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/N4C32/transformer_big_bs5120_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/benchmark_common/run_benchmark.sh
- 修复单机单卡，单机多卡运行错误。
- 添加Transformer Big的N4C32多机多卡。
=> add Transformer Big N4C32

frame_benchmark/docker_images.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N1C8/gpt3_bs16_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N1C8/gpt3_bs16_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N1C8/gpt3_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N1C8/gpt3_bs8_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N4C32/gpt3_bs16_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N4C32/gpt3_bs16_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N4C32/gpt3_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/N4C32/gpt3_bs8_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/benchmark_common/__init__.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt3/benchmark_common/run_benchmark.sh
=> add gpt n4c32

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/transformer_big/benchmark_common/analysis_log.py
更新 transformer ips的计算方式，不需要除以GPU的显卡数量。
=> Update transformer-big IPS

api/dynamic_tests_v2/diagonal.py, api/dynamic_tests_v2/transpose.py, api/tests/diagonal.py, api/tests/transpose.py
=> Enhance the test of transpose and diagonal.

dynamic_graph/seg_models/paddle/run_benchmark.sh
fix benchmark ci,test=document_fix
=> fix benchmark ci,test=document_fix

api/common/paddle_op_benchmark.py, api/tests_v2/configs/activation.json, api/tests_v2/configs/gelu.json, api/tests_v2/configs/selu.json, api/tests_v2/configs/size.json
=> Remove some meaningless configs.

api/deploy/write_excel.py
=> Enhance the implementation of writing to excel and add backgroud for bad unit.

api/deploy/write_excel.py, api/dynamic_tests_v2/squared_l2_norm.py, api/tests_v2/configs/squared_l2_norm.json
add fp16 squaredl2norm op benchmark
=> Add fp16 squaredl2norm op benchmark

api/common/paddle_op_benchmark.py, api/run_op_benchmark.sh
=> Enable autotune.

api/tests/depthwise_conv2d.py, api/tests/group_norm.py, api/tests/isclose.py, api/tests/kldiv_loss.py, api/tests/kthvalue.py, api/tests/squared_l2_norm.py, api/tests_v2/configs/kldiv_loss.json
=> Sync several unified tests from dynamic_tests_v2.

api/dynamic_tests_v2/squared_l2_norm.py, api/tests/squared_l2_norm.py
=> Fix import of suqared_l2_norm.

ci/scripts/run_test.sh
=> Remove the tests of dynamic_tests_v2 in ci.

api/tests_v2/configs/eigh.json
=> add eigh test case

api/tests_v2/alpha_fold/matmul.json
=> add matmul config for alpha_fold

api/tests_v2/alpha_fold/eigh.json
=> Add eigh config for alpha_fold model

api/common/launch.py, api/tests/expand.py
1. 修复新版本nsys的日志不能正确解析的问题
2. expand关闭view机制
=> Fix the parsing of new version nsys and disable view of expand.

frame_benchmark/docker_images.yaml, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/N1C1/ResNet152_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/N1C8/ResNet152_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/N1C1/pwgan_bs16_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/pwgan/N1C8/pwgan_bs16_fp32_DP.sh
[develop] fix docker_images.yaml
=> [develop] fix docker_images.yaml

api/tests_v2/alpha_fold/split.json
=> Upload split configs in AF2

.gitmodules, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/N1C1/det_r50_db_v2_0_bs16_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/N1C1/det_r50_db_v2_0_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/N1C8/det_r50_db_v2_0_bs16_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/N1C8/det_r50_db_v2_0_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/N4C32/det_r50_db_v2_0_bs16_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/N4C32/det_r50_db_v2_0_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/benchmark_common/run_benchmark.sh
=>  add fp16 support of db

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_for_question_answering/N1C1/bert_for_question_answering_bs32_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_for_question_answering/N1C1/bert_for_question_answering_bs32_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_for_question_answering/N1C8/bert_for_question_answering_bs32_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_for_question_answering/N1C8/bert_for_question_answering_bs32_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_for_question_answering/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_for_question_answering/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_for_question_answering/benchmark_common/run_benchmark.sh
=> Add bert for qa bench

frame_benchmark/pytorch/dynamic/PaddleSpeech/scripts/conformer/benchmark_common/prepare.sh
=> add conformer benchmark

api/tests_v2/configs/layer_norm.json
=> Add layerNorm configs in AF2 model

api/tests_v2/model_configs/BMN/conv2d.json, api/tests_v2/model_configs/BMN/conv3d.json, api/tests_v2/model_configs/ch_ppocr_server_v2_0_rec/conv2d.json
add some conv2d conv3d configs while analyzing cuda11.2 ——> cuda11.8 models
=> add conv configs while analyzing models

frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CSwinTransformer_tiny/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DenseNet121/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DenseNet121/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/HRNet_W48_C/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV2/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_large_x1_0/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_large_x1_0/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileViT_small/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PVT_V2_B2_Linear/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNeXt50_32x4d/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNeXt50_32x4d/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ShuffleNetV2_x1_0/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/SwinTransformer_tiny_patch4_window7_224/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/SwinTransformer_tiny_patch4_window7_224/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/alt_gvt_base/benchmark_common/analysis_log.py
1. fix parse: xxx_bs128_fp16_DP;
2. replace full imagenet1k with mini dataset;
=> fix parse & replace dataset

scripts/benchmark_ci/model_ci.sh
remove resnet50 fp16 for model benchmark ci
=> remove resnet50 fp16 for model benchmark ci

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov3_darknet53_270e_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov3_darknet53_270e_coco/benchmark_common/run_benchmark.sh
=> mmdetection add torch compile

scripts/benchmark_ci/model_ci.sh
avoid import error in paddle develop for model benchmark ci
=> avoid import error in paddle develop for model benchmark ci

.gitmodules, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/N1C1/stablediffusion_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/N1C1/stablediffusion_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/N1C8/stablediffusion_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/N1C8/stablediffusion_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/n1c1.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/n1c8.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/train_text_to_image.py
=> add sd benchmark

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/train_text_to_image.py
=> StableDIffusion logging every 10 steps

frame_benchmark/pytorch/dynamic/PaddleClas/scripts/TNT_small/N1C1/TNT_small_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/TNT_small/N1C1/TNT_small_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/TNT_small/N1C8/TNT_small_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/TNT_small/N1C8/TNT_small_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/TNT_small/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/TNT_small/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/TNT_small/benchmark_common/run_benchmark.sh
=> [WIP]timm benchmark6

frame_benchmark/docker_images.yaml
=> 【Stablediffusion】Add docker image

frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml
add pytorch  clas model_path, docker images
=> update & add new model

frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/HRNet_W18_C/N1C1/HRNet_W18_C_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/HRNet_W18_C/N1C1/HRNet_W18_C_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/HRNet_W18_C/N1C8/HRNet_W18_C_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/HRNet_W18_C/N1C8/HRNet_W18_C_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/HRNet_W18_C/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/HRNet_W18_C/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/HRNet_W18_C/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/N1C1/ViT_base_patch16_224_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/N1C1/ViT_base_patch16_224_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/N1C8/ViT_base_patch16_224_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/N1C8/ViT_base_patch16_224_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/benchmark_common/run_benchmark.sh
=> [WIP]timm_benchmark7

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/N1C1/mask2former_bs1_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/N1C1/mask2former_bs1_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/N1C4/mask2former_bs1_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/N1C4/mask2former_bs1_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/N1C8/mask2former_bs1_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/N1C8/mask2former_bs1_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/N4C32/mask2former_bs1_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/N4C32/mask2former_bs1_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/benchmark_common/detect_cuda.cu, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/mask2former/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/N1C1/maskformer_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/N1C1/maskformer_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/N1C4/maskformer_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/N1C4/maskformer_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/N1C8/maskformer_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/N1C8/maskformer_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/N4C32/maskformer_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/N4C32/maskformer_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/benchmark_common/detect_cuda.cu, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/maskformer/benchmark_common/run_benchmark.sh
=> [Benchmark] add paddleSeg maskformer and mask2former for benchmark

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C1/deformable_detr_r50_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C8/deformable_detr_r50_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C1/fcos_r50_fpn_1x_coco_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C1/fcos_r50_fpn_1x_coco_bs8_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C8/fcos_r50_fpn_1x_coco_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C1/mask_rcnn_r50_fpn_1x_coco_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C1/mask_rcnn_r50_fpn_1x_coco_bs4_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C8/mask_rcnn_r50_fpn_1x_coco_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C8/mask_rcnn_r50_fpn_1x_coco_bs4_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N4C32/mask_rcnn_r50_fpn_1x_coco_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N4C32/mask_rcnn_r50_fpn_1x_coco_bs4_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/analysis_log.py
fcos_r50_fpn_1x_coco and mask_rcnn_r50_fpn_1x_coco ：
* modify parameters，epoch=2;
* analysis_log.py
* dataset
=> fix fcos_r50_fpn_1x_coco mask_rcnn_r50_fpn_1x_coco

frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/benchmark_common/run_benchmark.sh
=> add tsm compile mode

frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/benchmark_common/run_benchmark.sh
=> update db benchmark

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C1/deformable_detr_r50_1x_coco_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C1/deformable_detr_r50_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C8/deformable_detr_r50_1x_coco_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C8/deformable_detr_r50_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C1/fcos_r50_fpn_1x_coco_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C1/fcos_r50_fpn_1x_coco_bs8_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C8/fcos_r50_fpn_1x_coco_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C1/mask_rcnn_r50_fpn_1x_coco_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C1/mask_rcnn_r50_fpn_1x_coco_bs4_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C8/mask_rcnn_r50_fpn_1x_coco_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C8/mask_rcnn_r50_fpn_1x_coco_bs4_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N4C32/mask_rcnn_r50_fpn_1x_coco_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N4C32/mask_rcnn_r50_fpn_1x_coco_bs4_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/analysis_log.py
=> deformable_detr add fp16

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt_for_sequence_classification/benchmark_common/analysis_log.py
Fix GPTForSequenceClassification analysis.
=> Fix GPTForSequenceClassification analysis

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/N4C32/stablediffusion_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/N4C32/stablediffusion_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/n4c32.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/run_benchmark.sh
add N4C32 benchmark shell for SD
=> add N4C32 for SD

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/gpt_for_sequence_classification/benchmark_common/PrepareEnv.sh
Delete `git checkout .` when preparing.
=> Delete checkout .

frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/benchmark_common/main.py, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/benchmark_common/opts.py, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/TSM/benchmark_common/prepare.sh
=> fix TSM compile bug

.gitmodules
=> fix yolov7 bug

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C1/deformable_detr_r50_1x_coco_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C1/deformable_detr_r50_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C8/deformable_detr_r50_1x_coco_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/N1C8/deformable_detr_r50_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/deformable_detr_r50_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/dino_r50_4scale_1x_coco/N1C1/dino_r50_4scale_1x_coco_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/dino_r50_4scale_1x_coco/N1C1/dino_r50_4scale_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/dino_r50_4scale_1x_coco/N1C8/dino_r50_4scale_1x_coco_bs2_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/dino_r50_4scale_1x_coco/N1C8/dino_r50_4scale_1x_coco_bs2_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/dino_r50_4scale_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/dino_r50_4scale_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C1/fcos_r50_fpn_1x_coco_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C1/fcos_r50_fpn_1x_coco_bs8_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C8/fcos_r50_fpn_1x_coco_bs8_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/N1C8/fcos_r50_fpn_1x_coco_bs8_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/fcos_r50_fpn_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C1/mask_rcnn_r50_fpn_1x_coco_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C1/mask_rcnn_r50_fpn_1x_coco_bs4_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C8/mask_rcnn_r50_fpn_1x_coco_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/N1C8/mask_rcnn_r50_fpn_1x_coco_bs4_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/mask_rcnn_r50_fpn_1x_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov3_darknet53_270e_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov3_darknet53_270e_coco/benchmark_common/analysis_log.py
* change dataset(cocomini)
* fix dino analysisi_log
* fix max_epoch
=> fix some parameter

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/N1C1/yolov5_l_300e_coco_bs16_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/N1C1/yolov5_l_300e_coco_bs16_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/N1C8/yolov5_l_300e_coco_bs16_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/N1C8/yolov5_l_300e_coco_bs16_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/N1C1/yolov7_l_300e_coco_bs32_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/N1C1/yolov7_l_300e_coco_bs32_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/N1C8/yolov7_l_300e_coco_bs32_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/N1C8/yolov7_l_300e_coco_bs32_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/benchmark_common/run_benchmark.sh
*change dataset cocomint; 
*fix yolov7 run bug
=> fix yolov7 run bug

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/stablediffusion/benchmark_common/train_text_to_image.py
=> Update stable diffusion

.gitmodules, frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/VideoSwin/N1C1/VideoSwin_bs1_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/VideoSwin/N1C1/VideoSwin_bs1_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/VideoSwin/N1C8/VideoSwin_bs1_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/VideoSwin/N1C8/VideoSwin_bs1_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/VideoSwin/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/VideoSwin/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleVideo/scripts/VideoSwin/benchmark_common/run_benchmark.sh
=> add videoswin benchmark scripts

Inference/c++/ernie/inference.cc
This PR adds the option to run the QAT once using the EnableMkldnnInt8 option.
=> Add option to test QAT Ernie test

frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DeiT_base_patch16_224/N1C1/DeiT_base_patch16_224_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DeiT_base_patch16_224/N1C1/DeiT_base_patch16_224_bs256_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DeiT_base_patch16_224/N1C8/DeiT_base_patch16_224_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DeiT_base_patch16_224/N1C8/DeiT_base_patch16_224_bs256_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DeiT_tiny_patch16_224/N1C1/DeiT_tiny_patch16_224_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DeiT_tiny_patch16_224/N1C1/DeiT_tiny_patch16_224_bs256_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DeiT_tiny_patch16_224/N1C8/DeiT_tiny_patch16_224_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/DeiT_tiny_patch16_224/N1C8/DeiT_tiny_patch16_224_bs256_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/N1C1/ResNet152_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/N1C1/ResNet152_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/N1C8/ResNet152_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet152/N1C8/ResNet152_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet34/N1C1/ResNet34_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet34/N1C1/ResNet34_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet34/N1C8/ResNet34_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet34/N1C8/ResNet34_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/N1C1/ViT_base_patch16_224_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/N1C1/ViT_base_patch16_224_bs64_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/N1C8/ViT_base_patch16_224_bs64_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ViT_base_patch16_224/N1C8/ViT_base_patch16_224_bs64_fp32_DP.sh
=> set num_workers=24

.gitmodules, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/N1C8/yolov5_l_300e_coco_bs16_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/N1C8/yolov5_l_300e_coco_bs16_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/N1C8/yolov7_l_300e_coco_bs32_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/N1C8/yolov7_l_300e_coco_bs32_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov7_l_300e_coco/benchmark_common/analysis_log.py
=> fix yolov5 yolov7 batch time

frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C1/ResNet50_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C8/ResNet50_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50_NHWC/N1C1/ResNet50_NHWC_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50_NHWC/N1C8/ResNet50_NHWC_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50_NHWC/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50_NHWC/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50_NHWC/benchmark_common/run_benchmark.sh
torch 2.0.0 py38
8*A100:
4*A100:
no_compile:
pytorch-image-models_ResNet50_bs256_fp16_DP_N1C1_speed: 2034.9609993112051
compile:
pytorch-image-models_ResNet50_bs256_fp16_DP_N1C1_speed: 2049.5736062759083
=> add r50 nhwc

frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/N1C1/bert_base_seqlen128_hf_bs128_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/N1C1/bert_base_seqlen128_hf_bs128_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/N1C8/bert_base_seqlen128_hf_bs128_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/N1C8/bert_base_seqlen128_hf_bs128_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/benchmark_common/bert_base_uncased.json, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/benchmark_common/hf_pretrain.py, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/benchmark_common/n1c1.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/benchmark_common/n1c8.yaml, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/bert_base_seqlen128_hf/benchmark_common/run_benchmark.sh
添加Huggingface版本在真实数据集上进行BERT预训练的代码。
=> [BERT] Add hfbert pretrain

frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/N1C1/CLIP_vit_base_patch16_224_finetune_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/N1C1/CLIP_vit_base_patch16_224_finetune_bs256_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/N1C8/CLIP_vit_base_patch16_224_finetune_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/N1C8/CLIP_vit_base_patch16_224_finetune_bs256_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/ocrnet_hrnetw48/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/N1C1/segformer_b0_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/N1C8/segformer_b0_bs4_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleSeg/scripts/segformer_b0/benchmark_common/run_benchmark.sh
segformer model support compile mode and fp16 mode
=> support compile and fp16

frame_benchmark/docker_images.yaml, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/N1C1/CLIP_vit_base_patch16_224_finetune_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/N1C1/CLIP_vit_base_patch16_224_finetune_bs256_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/N1C8/CLIP_vit_base_patch16_224_finetune_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/N1C8/CLIP_vit_base_patch16_224_finetune_bs256_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/benchmark_common/run_benchmark.sh
=> add CLIP_ViT_base_patch16_224_finetune

frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2/benchmark_common/run_benchmark.sh
=> 【Develop】fix petrv2 python

frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C1/ResNet50_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C8/ResNet50_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50_NHWC/N1C1/ResNet50_NHWC_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50_NHWC/N1C8/ResNet50_NHWC_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50_NHWC/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/SwinTransformer_base_patch4_window7_224/benchmark_common/PrepareEnv.sh
set num worker to 32;
fix bug of timm when torch version >= 2.0;
=> num worker = 32

frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/run_benchmark.sh
=> modify prepare

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/dino_r50_4scale_1x_coco/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/benchmark_common/PrepareEnv.sh
=> fix torch installation

frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/petr_vovnet_gridmask_p4_800x320_benchmark_configs/petr_vovnet_gridmask_p4_800x320_bs1_fp32_DP.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/petr_vovnet_gridmask_p4_800x320_benchmark_configs/petr_vovnet_gridmask_p4_800x320_bs1_fp32_MultiP_DP.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/petr_vovnet_gridmask_p4_800x320_benchmark_configs/petr_vovnet_gridmask_p4_800x320_bs1_fp32_SingleP_DP.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/PrepareEnv.sh
=> [WIP]fix_config_bug

frame_benchmark/pytorch/dynamic/PaddleNLP/scripts/llama/benchmark_common/prepare.sh
=> add requirements for llama

frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_benchmark_configs/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_bs1_fp16_DP.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_benchmark_configs/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_bs1_fp16_MultiP_DP.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_benchmark_configs/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_bs1_fp16_SingleP_DP.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_benchmark_configs/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_bs1_fp32_DP.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_benchmark_configs/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_bs1_fp32_MultiP_DP.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_benchmark_configs/petrv2_vovnet_gridmask_p4_800x320_dn_centerview_bs1_fp32_SingleP_DP.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/run_benchmark.sh
=> [petr benchmark]Add http

frame_benchmark/models_path.yaml
=> [benchmark]Fix path

frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/analysis_log.py, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/run_benchmark.sh
=> fix fp_item

frame_benchmark/pytorch/dynamic/PaddleClas/scripts/CLIP_ViT_base_patch16_224_finetune/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/SwinTransformer_base_patch4_window7_224/benchmark_common/PrepareEnv.sh
fix clas python3.10 torch compile bug
=> fix clas python3.10 torch compile bug

frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petr_vovnet_gridmask_p4_800x320/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/Paddle3D/scripts/petrv2_vovnet_gridmask_p4_800x320_dn_centerview/benchmark_common/PrepareEnv.sh
=> [benchmark]Modify proxy

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/dino_r50_4scale_1x_coco/benchmark_common/run_benchmark.sh
=> fix repo name

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/N1C8/yolov5_l_300e_coco_bs16_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/N1C8/yolov5_l_300e_coco_bs16_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/yolov5_l_300e_coco/benchmark_common/run_benchmark.sh
change bs to single gpu setting to consistant with others
=> change bs to single gpu setting to consistant with others

frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/N1C1/MobileNetV3_small_x1_0_bs1024_fp16_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/N1C1/MobileNetV3_small_x1_0_bs1024_fp32_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/N1C8/MobileNetV3_small_x1_0_bs1024_fp16_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/N1C8/MobileNetV3_small_x1_0_bs1024_fp32_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/N1C1/PPLCNet_x1_0_bs1024_fp16_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/N1C1/PPLCNet_x1_0_bs512_fp32_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/N1C8/PPLCNet_x1_0_bs1024_fp16_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/N1C8/PPLCNet_x1_0_bs512_fp32_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C1/ResNet50_bs256_fp16_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C1/ResNet50_bs256_fp32_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C8/ResNet50_bs256_fp16_ultra_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C8/ResNet50_bs256_fp32_ultra_DP.sh
configs consistant with paddle
=> add configs consistant with paddle

frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/N1C1/MobileNetV3_small_x1_0_ultra_bs1024_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/N1C1/MobileNetV3_small_x1_0_ultra_bs1024_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/N1C8/MobileNetV3_small_x1_0_ultra_bs1024_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/MobileNetV3_small_x1_0/N1C8/MobileNetV3_small_x1_0_ultra_bs1024_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/N1C1/PPLCNet_x1_0_ultra_bs1024_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/N1C1/PPLCNet_x1_0_ultra_bs512_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/N1C8/PPLCNet_x1_0_ultra_bs1024_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/PPLCNet_x1_0/N1C8/PPLCNet_x1_0_ultra_bs512_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C1/ResNet50_ultra_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C1/ResNet50_ultra_bs256_fp32_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C8/ResNet50_ultra_bs256_fp16_DP.sh, frame_benchmark/pytorch/dynamic/PaddleClas/scripts/ResNet50/N1C8/ResNet50_ultra_bs256_fp32_DP.sh
=> fix model name

scripts/benchmark_ci/model_ci.sh
=> fix model_ci

dynamic_graph/bert/paddle/run_benchmark.sh, dynamic_graph/ppyolov2/paddle/run_benchmark_ppyolov2.sh, dynamic_graph/resnet/paddle/run_benchmark_resnet.sh, dynamic_graph/seg_models/paddle/run_benchmark.sh, dynamic_graph/yolov3/paddle/run_benchmark.sh, scripts/benchmark_ci/model_ci.sh, scripts/run_model.sh
=> 【master】update models commit 

.gitmodules
- While execute `git submodule update --remote deepxde `, the submodule will be updated improperly
- Now it is fixed to the `master` branch
=> fix deepxde update branch

frame_benchmark/docker_images.yaml, frame_benchmark/models_path.yaml
=> add pytorch llama pretain

frame_benchmark/pytorch/dynamic/PaddleMIX/scripts/stable_diffusion/N1C1/stable_diffusion-098b_pretrain_bs80_bf16O1_DP.sh, frame_benchmark/pytorch/dynamic/PaddleMIX/scripts/stable_diffusion/N1C8/stable_diffusion-098b_pretrain_bs80_bf16O1_DP.sh
=> [SD] add pretrain bs80 bf16 O1

frame_benchmark/pytorch/dynamic/PaddleMIX/scripts/stable_diffusion/N1C1/stable_diffusion-098b_lora_bs96_bf16O1_DP.sh, frame_benchmark/pytorch/dynamic/PaddleMIX/scripts/stable_diffusion/N1C8/stable_diffusion-098b_lora_bs96_bf16O1_DP.sh
=> [SD] Upate bs lora sd

api/common/feeder.py, api/common/paddle_op_benchmark.py, api/tests/batch_norm.py
=> Replace paddle.fluid with paddle.base.

frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/rtdetr_r50vd_4pdx/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleDetection/scripts/rtdetr_r50vd_4pdx/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/crnn_4pdx/benchmark_common/PrepareEnv.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/crnn_4pdx/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0_4pdx/benchmark_common/prepare.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/det_r50_db_v2_0_4pdx/benchmark_common/run_benchmark.sh, frame_benchmark/pytorch/dynamic/PaddleOCR/scripts/table_master/benchmark_common/prepare.sh
=> 【develop】fix  OCR scripts

api/common/feeder.py, api/common/paddle_op_benchmark.py, static_graph/OCR/paddle/ocr_recognition/utility.py
Change core.LoDTensor to core.DenseTensor
https://github.com/PaddlePaddle/Paddle/issues/69305
=> Change core.LoDTensor to core.DenseTensor
